UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{
"Txn Time": "datetime",
"Org": "string",
"reqid": "string",
"Txn ID": "string",
"Txn Type": "string",
"MCC": "string",
"Txn Class": "string",
"Merchant Addr": "string",
"Merchant Type": "string",
"Customer Addr": "string",
"Customer Type": "string",
"Txn Amount": "float",
"Org Txn Id": "string",
"Currency": "string",
"Unique ID": "string",
"New Merchant": "string",
"New Customer": "string",
"Payee VPAID": "string",
"Payer VPAID": "string",
"Skip Processing": "string",
"Seller ID": "string",
"Payer Name": "string",
"Commission": "string",
"Seller Name": "string",
"Instructed Amount": "float",
"Created Date": "datetime",
"Partner Name": "string",
"Payer": "string",
"Country": "string",
"payeeVPA external ID": "string",
"payer VPA external ID": "string",
"Decision Active": "string",
"Txn Date": "datetime",
"Txn Last Modified": "datetime",
"Settlemet Amount": "float",
"Product ID": "string",
"Transaction Amount": "float",
"Decision ID": "string",
"Payee VPA": "string",
"Payer VPA": "string",
"Payee Account ID": "string",
"Channel ID": "string",
"Record Status": "string",
"Account External ID": "string",
"Decision Detail": "string",
"Txn Class Name": "string",
"transactionReferenceNumber": "string",
"PAN": "string",
"City": "string",
"GSTN": "string",
"State": "string",
"Status": "string",
"Channel": "string",
"emailId": "string",
"PinCode": "string",
"District": "string",
"Latitude": "string",
"Longitude": "string",
"Updated By": "string",
"Created By": "string",
"Onboarded by": "string",
"Partner Name": "string",
"addressLine1": "string",
"addressLine2": "string",
"Business Name": "string",
"Merchant type": "string",
"Mobile Number": "string",
"Turnover Type": "string",
"Ownership Type": "string",
"Acceptance Type": "string",
"Limit Account ID": "string",
"Seller Username": "string",
"Last Modified Date": "string",
"seller Identifier": "string",
"due Diligence Status": "string",
"seller ReferenceNumber": "string",
"settlement Account Name": "string",
"partner Reference Number": "string",
"seller Verified Account Name": "string",
"default Settlement Account Id": "string",
"BeneficiaryIFSC_AccountNo": "string",
"IP address": "string",
"Payer Acc No": "string",
"Website url": "string"
}
'::text WHERE
idashboardresultsetid = 59 AND itenantid = 17;

UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{
"Txn Time": "datetime",
"Org": "string",
"reqid": "string",
"Txn ID": "string",
"Txn Type": "string",
"MCC": "string",
"Txn Class": "string",
"Merchant Addr": "string",
"Merchant Type": "string",
"Customer Addr": "string",
"Customer Type": "string",
"Txn Amount": "float",
"Org Txn Id": "string",
"Currency": "string",
"Unique ID": "string",
"New Merchant": "string",
"New Customer": "string",
"Payee VPAID": "string",
"Payer VPAID": "string",
"Skip Processing": "string",
"Seller ID": "string",
"Payer Name": "string",
"Commission": "string",
"Seller Name": "string",
"Instructed Amount": "float",
"Created Date": "datetime",
"Partner Name": "string",
"Payer": "string",
"Country": "string",
"payeeVPA external ID": "string",
"payer VPA external ID": "string",
"Decision Active": "string",
"Txn Date": "datetime",
"Txn Last Modified": "datetime",
"Settlemet Amount": "float",
"Product ID": "string",
"Transaction Amount": "float",
"Decision ID": "string",
"Payee VPA": "string",
"Payer VPA": "string",
"Payee Account ID": "string",
"Channel ID": "string",
"Record Status": "string",
"Account External ID": "string",
"Decision Detail": "string",
"Txn Class Name": "string",
"transactionReferenceNumber": "string",
"PAN": "string",
"City": "string",
"GSTN": "string",
"State": "string",
"Status": "string",
"Channel": "string",
"emailId": "string",
"PinCode": "string",
"District": "string",
"Latitude": "string",
"Longitude": "string",
"Updated By": "string",
"Created By": "string",
"Onboarded by": "string",
"Partner Name": "string",
"addressLine1": "string",
"addressLine2": "string",
"Business Name": "string",
"Merchant type": "string",
"Mobile Number": "string",
"Turnover Type": "string",
"Ownership Type": "string",
"Acceptance Type": "string",
"Limit Account ID": "string",
"Seller Username": "string",
"Last Modified Date": "string",
"seller Identifier": "string",
"due Diligence Status": "string",
"seller ReferenceNumber": "string",
"settlement Account Name": "string",
"partner Reference Number": "string",
"seller Verified Account Name": "string",
"default Settlement Account Id": "string",
"BeneficiaryIFSC_AccountNo": "string",
"IP address": "string",
"Payer Acc No": "string",
"Website url": "string"
}
'::text WHERE
idashboardresultsetid = 59 AND itenantid = 8;

UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{
"Txn Time":"datetime",
"Org":"string",
"reqid":"string",
"Txn ID":"string",
"Txn Type":"string",
"MCC":"string",
"Txn Class":"string",
"Merchant Addr":"string",
"Merchant Type":"string",
"Customer Addr":"string",
"Customer Type":"string",
"Txn Amount":"float",
"Org Txn Id":"string",
"Currency":"string",
"Unique ID":"string",
"New Merchant":"string",
"New Customer":"string",
"Payee VPAID":"string",
"Payer VPAID":"string",
"Skip Processing":"string",
"Seller ID":"string",
"Payer Name":"string",
"Commission":"string",
"Seller Name":"string",
"Instructed Amount":"float",
"Created Date":"datetime",
"Partner Name":"string",
"Payer":"string",
"Country":"string",
"payeeVPA external ID":"string",
"payer VPA external ID":"string",
"Decision Active":"string",
"Txn Date":"datetime",
"Txn Type":"string",
"Txn Last Modified":"datetime",
"Settlemet Amount":"float",
"Product ID":"string",
"Transaction Amount":"float",
"Decision ID":"string",
"Payee VPA":"string",
"Payer VPA":"string",
"Payee Account ID":"string",
"Channel ID":"string",
"Product ID":"string",
"Record Status":"string",
"Account External ID":"string",
"Decision ID":"string",
"Decision Detail":"string",
"Txn Class Name":"string",
"transactionReferenceNumber":"string",
"Seller Name":"string",
"Seller ID":"string",
"MCC":"string",
"PAN":"string",
"City":"string",
"GSTN":"string",
"State":"string",
"Status":"string",
"Channel":"string",
"emailId":"string",
"PinCode":"string",
"District":"string",
"Latitude":"string",
"Longitude":"string",
"Updated By":"string",
"Created By":"string",
"Onboarded by":"string",
"Partner Name":"string",
"addressLine1":"string",
"addressLine2":"string",
"Business Name":"string",
"Merchant type":"string",
"Mobile Number":"string",
"Turnover Type":"string",
"Ownership Type":"string",
"Acceptance Type":"string",
"Limit Account ID":"string",
"Seller Username":"string",
"Last Modified Date":"string",
"seller Identifier":"string",
"due Diligence Status":"string",
"seller ReferenceNumber":"string",
"settlement Account Name":"string",
"partner Reference Number":"string",
"seller Verified Account Name":"string",
"default Settlement Account Id":"string",
"BeneficiaryIFSC_AccountNo":"string",
"IP address":"string",
"Payer Acc No":"string",
"Website url":"string"
}
'::text WHERE
idashboardresultsetid = 70 AND itenantid = 16;