INSERT INTO ui.dashboard (idashboardid, bactive, bdelete, vcdashboardname, iorder, irowcount, imenustructuredesc, itenantid, bdynamic) 
SELECT 22, true, false, 'Closed Cases Report', 22, 1, 536, t.itenantid, true FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20);



INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid) select 72, false, NULL, 'SELECT (NOW()) as "enddate", (NOW() - interval ''2 day'') as "startdate";', NULL, NULL, NULL, NULL, t.itenantid FROM ui.tenants t WHERE itenantid > 4 on conflict do nothing;
INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid) SELECT 71, false, NULL, 'SELECT X.* FROM   (VALUES (''Closed On'', ''ClosedOn''),(''Created On'', ''CreatedOn'')) AS X ("label", "value")', NULL, NULL, NULL, NULL,  t.itenantid FROM ui.tenants t WHERE itenantid > 4 on conflict do nothing;


INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid) SELECT 73, true, '{"Basis":null,"DateRange":null,"CaseType":null}','{
    "All" :{
      "ClosedOn":"select pdef.name_ as \"Case Type\", TicketID.long_ as \"Case ID\", task.assignee_ as \"Closed By\", pinst.end_time_ as \"Closed On\", Alert.text_ as \"Alert\", pinst.start_time_ as \"Ticket Created Date\", Payer.text_ as \"Payer\", Payee.text_ as \"Payee\", Amount.double_/100 as \"Amount\" from camunda.act_re_procdef pdef inner join camunda.act_hi_procinst pinst on pinst.proc_def_id_ = pdef.id_ and pinst.state_=''COMPLETED'' inner join camunda.act_hi_taskinst task on task.id_ = (select id_ from camunda.act_hi_taskinst where proc_inst_id_ = pinst.proc_inst_id_ order by end_time_ desc limit 1) left outer join camunda.act_hi_detail TicketID on TicketID.proc_inst_id_ = pinst.proc_inst_id_ and TicketID.name_=''TicketID'' left outer join camunda.act_hi_detail Alert on Alert.id_ = (select id_ from camunda.act_hi_detail  where proc_inst_id_ = pinst.proc_inst_id_ and name_=''Alert'' order by time_ desc limit 1) left outer join camunda.act_hi_detail Payer on Payer.proc_inst_id_ = pinst.proc_inst_id_ and Payer.name_=''payer'' left outer join camunda.act_hi_detail Payee on Payee.proc_inst_id_ = pinst.proc_inst_id_ and Payee.name_=''payee'' left outer join camunda.act_hi_detail Amount on Amount.proc_inst_id_ = pinst.proc_inst_id_ and Amount.name_=''TransactionAmount'' where cast(pinst.end_time_ as date) between cast(:StartDate as date) and cast(:EndDate as date) and pinst.proc_def_key_ in (with d1 as (select mappingid from ui.webusermapping where webuserid = :loggedinuser AND iorgid =:orgid  and mappingtype = ''Workflow'') (select workflowkey FROM ui.workflowmasters where (workflowid in (select mappingid from d1) or -1 in (select mappingid from d1)) and itenantid=:tenantid and is_filter_display=true)) and pinst.tenant_id_= :tenantidstr ",
      "CreatedOn":"select pdef.name_ as \"Case Type\", TicketID.long_ as \"Case ID\", task.assignee_ as \"Closed By\", pinst.end_time_ as \"Closed On\", Alert.text_ as \"Alert\", pinst.start_time_ as \"Ticket Created Date\", Payer.text_ as \"Payer\", Payee.text_ as \"Payee\", Amount.double_/100 as \"Amount\" from camunda.act_re_procdef pdef inner join camunda.act_hi_procinst pinst on pinst.proc_def_id_ = pdef.id_ and pinst.state_=''COMPLETED'' inner join camunda.act_hi_taskinst task on task.id_ = (select id_ from camunda.act_hi_taskinst where proc_inst_id_ = pinst.proc_inst_id_ order by end_time_ desc limit 1) left outer join camunda.act_hi_detail TicketID on TicketID.proc_inst_id_ = pinst.proc_inst_id_ and TicketID.name_=''TicketID'' left outer join camunda.act_hi_detail Alert on Alert.id_ = (select id_ from camunda.act_hi_detail  where proc_inst_id_ = pinst.proc_inst_id_ and name_=''Alert'' order by time_ desc limit 1) left outer join camunda.act_hi_detail Payer on Payer.proc_inst_id_ = pinst.proc_inst_id_ and Payer.name_=''payer'' left outer join camunda.act_hi_detail Payee on Payee.proc_inst_id_ = pinst.proc_inst_id_ and Payee.name_=''payee'' left outer join camunda.act_hi_detail Amount on Amount.proc_inst_id_ = pinst.proc_inst_id_ and Amount.name_=''TransactionAmount'' where cast(pinst.start_time_ as date) between cast(:StartDate as date) and cast(:EndDate as date) and pinst.proc_def_key_ in (with d1 as (select mappingid from ui.webusermapping where webuserid = :loggedinuser AND iorgid =:orgid  and mappingtype = ''Workflow'') (select workflowkey FROM ui.workflowmasters where (workflowid in (select mappingid from d1) or -1 in (select mappingid from d1)) and itenantid=:tenantid and is_filter_display=true)) and pinst.tenant_id_= :tenantidstr"
    },
    "Other":{
      "ClosedOn":"select pdef.name_ as \"Case Type\", TicketID.long_ as \"Case ID\", task.assignee_ as \"Closed By\", pinst.end_time_ as \"Closed On\", Alert.text_ as \"Alert\", pinst.start_time_ as \"Ticket Created Date\", Payer.text_ as \"Payer\", Payee.text_ as \"Payee\", Amount.double_/100 as \"Amount\" from camunda.act_re_procdef pdef inner join camunda.act_hi_procinst pinst on pinst.proc_def_id_ = pdef.id_ and pinst.state_=''COMPLETED'' inner join camunda.act_hi_taskinst task on task.id_ = (select id_ from camunda.act_hi_taskinst where proc_inst_id_ = pinst.proc_inst_id_ order by end_time_ desc limit 1) left outer join camunda.act_hi_detail TicketID on TicketID.proc_inst_id_ = pinst.proc_inst_id_ and TicketID.name_=''TicketID'' left outer join camunda.act_hi_detail Alert on Alert.id_ = (select id_ from camunda.act_hi_detail  where proc_inst_id_ = pinst.proc_inst_id_ and name_=''Alert'' order by time_ desc limit 1) left outer join camunda.act_hi_detail Payer on Payer.proc_inst_id_ = pinst.proc_inst_id_ and Payer.name_=''payer'' left outer join camunda.act_hi_detail Payee on Payee.proc_inst_id_ = pinst.proc_inst_id_ and Payee.name_=''payee'' left outer join camunda.act_hi_detail Amount on Amount.proc_inst_id_ = pinst.proc_inst_id_ and Amount.name_=''TransactionAmount'' where cast(pinst.end_time_ as date) between cast(:StartDate as date) and cast(:EndDate as date) and pdef.key_ = :CaseType and pinst.tenant_id_= :tenantidstr",
      "CreatedOn":"select pdef.name_ as \"Case Type\", TicketID.long_ as \"Case ID\", task.assignee_ as \"Closed By\", pinst.end_time_ as \"Closed On\", Alert.text_ as \"Alert\", pinst.start_time_ as \"Ticket Created Date\", Payer.text_ as \"Payer\", Payee.text_ as \"Payee\", Amount.double_/100 as \"Amount\" from camunda.act_re_procdef pdef inner join camunda.act_hi_procinst pinst on pinst.proc_def_id_ = pdef.id_ and pinst.state_=''COMPLETED'' inner join camunda.act_hi_taskinst task on task.id_ = (select id_ from camunda.act_hi_taskinst where proc_inst_id_ = pinst.proc_inst_id_ order by end_time_ desc limit 1) left outer join camunda.act_hi_detail TicketID on TicketID.proc_inst_id_ = pinst.proc_inst_id_ and TicketID.name_=''TicketID'' left outer join camunda.act_hi_detail Alert on Alert.id_ = (select id_ from camunda.act_hi_detail  where proc_inst_id_ = pinst.proc_inst_id_ and name_=''Alert'' order by time_ desc limit 1) left outer join camunda.act_hi_detail Payer on Payer.proc_inst_id_ = pinst.proc_inst_id_ and Payer.name_=''payer'' left outer join camunda.act_hi_detail Payee on Payee.proc_inst_id_ = pinst.proc_inst_id_ and Payee.name_=''payee'' left outer join camunda.act_hi_detail Amount on Amount.proc_inst_id_ = pinst.proc_inst_id_ and Amount.name_=''TransactionAmount'' where cast(pinst.start_time_ as date) between cast(:StartDate as date) and cast(:EndDate as date) and pdef.key_ = :CaseType and pinst.tenant_id_= :tenantidstr"
    }
  }', false, false, false, 536,  t.itenantid FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20);
  
  
  
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid) SELECT 115, 'DateRange', 'DateRange', 73, 2, t.itenantid FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid) SELECT 114, 'Basis', 'JsonPath', 73, 1, t.itenantid FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid) SELECT 113, 'CaseType', 'JsonPath', 73, 0,t.itenantid FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20);



INSERT INTO ui.dashboardfilters (idashboardfilterid, ifilterorder, vcdashboardfiltername, idashboardid, vcdashboardfiltertype, idashboardqueryidfordefaultvalue, idashboardqueryidforoptions, itenantid, vcdashboardfilterdisplayname) SELECT 52, 2, 'DateRange', 22, 'DateRangePicker', 72, NULL, t.itenantid, 'Date Range' FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20) ;
INSERT INTO ui.dashboardfilters (idashboardfilterid, ifilterorder, vcdashboardfiltername, idashboardid, vcdashboardfiltertype, idashboardqueryidfordefaultvalue, idashboardqueryidforoptions, itenantid, vcdashboardfilterdisplayname) SELECT 51, 1, 'Basis', 22, 'Select', NULL, 71, t.itenantid, 'Basis'FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20) ;
INSERT INTO ui.dashboardfilters (idashboardfilterid, ifilterorder, vcdashboardfiltername, idashboardid, vcdashboardfiltertype, idashboardqueryidfordefaultvalue, idashboardqueryidforoptions, itenantid, vcdashboardfilterdisplayname) SELECT 50, 0, 'CaseType', 22, 'Select', NULL, 61, t.itenantid, 'Case Type'FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20) ;

INSERT INTO ui.dashboardresultset (idashboardresultsetid, iresultsetorder, vcdashboardresultsetcolumnjson, vcdashboardresultsetlayout, vcdashboardresultsetname, idashboardqueryid, idashboardid, vcdashboardresultsetschema, icolsize, irowno, dtlastupdatedtimestamp, iuserid, imenustructuredesc, itenantid, iorgid)
SELECT 33, NULL, NULL, '{"sizes":[1],"detail":{"main":{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_1"],"currentIndex":0}},"mode":"globalFilters","viewers":{"PERSPECTIVE_GENERATED_ID_1":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":false},"settings":false,"theme":"Pro Dark","title":"Closed Cases Report","group_by":[],"split_by":[],"columns":["Case ID","Case Type","Alert","Payer","Amount","Payee","Closed By","Closed On","Ticket Created Date"],"filter":[],"sort":[],"expressions":[],"aggregates":{},"master":false,"table":"closedcases","linked":false}}}
', 'closedcases', 73, 22, '{
"Case ID":"integer",
  "Case Type":"string",
  "Alert":"string",
  "Payer":"string",
  "Amount":"float",
  "Payee":"string",
  "Closed By":"string",
  "Closed On":"datetime",
  "Ticket Created Date":"datetime"
}', NULL, 1, NULL, NULL, 536, t.itenantid,NULL FROM ui.tenants t WHERE itenantid > 4 and itenantid not in (7,6,20);



