############################################### DB Params ########################################

## Hikari Params
spring.datasource.hikari.maximumPoolSize=100
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000



## JPA Params
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow

##DB Connection properties

jdbc.postgresql.transactional.driverClassName=org.postgresql.Driver
jdbc.postgresql.transactional.url=jdbc:postgresql://10.6.34.7:30763/frmdb?ApplicationName=UI(aniket-local)
jdbc.postgresql.transactional.username=ivan
jdbc.postgresql.transactional.password=vNkBZHEfgD73cMFw7n

jdbc.postgresql.analytics.driverClassName=org.postgresql.Driver
jdbc.postgresql.analytics.url=jdbc:postgresql://10.6.34.7:30763/frmdb?ApplicationName=UI(aniket-local)
jdbc.postgresql.analytics.username=ivan
jdbc.postgresql.analytics.password=vNkBZHEfgD73cMFw7n

#jdbc.postgresql.transactional.driverClassName=org.postgresql.Driver
#jdbc.postgresql.transactional.url=jdbc:postgresql://10.6.34.10:30763/frmdb?ApplicationName=UI(aniket-local)
#jdbc.postgresql.transactional.username=vishnu
#jdbc.postgresql.transactional.password=sVFIXbi2qBQGC34SJW
#
#jdbc.postgresql.analytics.driverClassName=org.postgresql.Driver
#jdbc.postgresql.analytics.url=jdbc:postgresql://10.6.34.10:30763/frmdb?ApplicationName=UI(aniket-local)
#jdbc.postgresql.analytics.username=vishnu
#jdbc.postgresql.analytics.password=sVFIXbi2qBQGC34SJW

jdbc.trino.datalake.driverClassName=io.trino.jdbc.TrinoDriver
jdbc.trino.datalake.url=jdbc:trino://trino.dev.dronapay.net:443
jdbc.trino.datalake.username=dptrino
jdbc.trino.datalake.password=jMnHMFJrde

###################################################### UIServer Security Params #####################################

##JWT Params
jwt.auth.app=dronapay
jwt.auth.secret_key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.auth.expires_in=90000
jwt.auth.refresh_token_expires_in=86400000

##API Key Params
auth.apikey=true
auth.apikeyvalue=f877a5b1-b6d6-4733-9d2e-0509538e536e

##CORS Params
drona.ui.url=http://localhost:3000

##WebUser Password Encryption-Decryption Params
user.login.private.key=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4gly+Nk1D/FPgWW0lWxa23QNC6erAOZQZG42bjRzFR+baZc/iYQXBnPvAzFQI6J9S7R/ZyaT53YaD9J8Hz15Pe6K2GtQgi/GTPXBzFpvTPT6xHLNY0oQe92RhzbYX8Z9cWz2yhW9JSHXnGcGUr5XZe0DQ/TMdwrFED0V9910ThjVr8/vlTwHvEyMnVWWImS8Bl9LLy2EACcobEtBAvvTFderg36StHZ+HSCGoiNuxWogpRyG+6h3eMYaqU6UGba5xcZf8evC3mls7SdgoYT6BbKpY/u8tJ83rGiVnqfAoNfoNmCRq6k5rMs/GKLVtHVBMO1AMcNZ9zWbwFdIgouNDAgMBAAECggEAAJzaiJB1Rvl2Le+Oo7x/Md7h+NUY1L8i0rJt/bOmPQ/pa3Ihf35U9v+blWcOANhf8pCYoUM05W8+rtt5CFIiv/55x0ZSJ1jfEiFMDhefojoJxSpz2pzUH2YcVz/ob3gaj6A01kpDAh2dBm9TEgCMvR32xGEnGhh5XxkEOtGvWypool5aHueddtz51WdKiVsew5y6jDQPtnGc+lwxoP7UDyFOruCLZMIOEe694gVOmHT8Lr8Sf9iK80LecOKDOm178hXGClhX3dvD5A8863O3aBGlhbttqpvt08bzFCZTsT7vwCqhzLA/6rb8UekByrmrLeP7opBxYKFzlnDX3Q3/EQKBgQDd5eixPGgED+o8YNsZPdR+aR1116TqZPp7PhO8gcgfDZg8UhiuTOLNO+65Pemxk5/iieHoO5hfkfQjFHEWG5ueOwZlDPIBAOn/O3VUwbRUPUzgFqyvSNaivFPhsQjschHWfSUxfzqIpqd/FPn8bYlGuHFi0ugy3/tUXwcadKINzQKBgQDU3XijlJuLhPIpVl3QHUh0wcx9Hj1+O2V+Ka+rdHD73kebJDJSirYaKGBbs9sltzHuU/0Hg+e5cdLYV5GgOfGWRrr8R+Mj9qtF5X01Mn6cbF3l3nK0GSwDsk8dQ/85DYCAqvxwkdMUWdv6pcdQzHSsc6YPYhy7Vv9vM5wVPyolTwKBgF4iHFajw5SFk97NT+UjX7PIr+C//IwbDk+eBA1iGR1jTQO56BJ5N3XNSPZ4l1znvVoDGDzGm1tftWv0Tg0M5TV44LuZhEh8tMe714h/LBrYbnZZ6CPsCHG85vDFg32a3opZSJ/400IJQOEeavZ1GVlRAXjk8/AxKJOgRIkqlVy5AoGAI7znMzeRAdSZP51zdKxl7MxYw6zfECFywcLH7pZHHdJM3VwvYrJNLokW3G6O3X8rT+Mj+S4JKpZUmuPg3DC+QcewPwjmtrQEP2DvK45FuYdsIFq/kUMko549MCGpaO++YlvStCeXc7Q+fY91rjgVYpqsB6smPcG2cvoMO3j2X3sCgYAM9mtoBFIwiWwujupGgX5IJ7xbwuecb4gZXaJhy41sAVB7EzQLPyrVzKhg8lvd/QrVnZaHlXhpXvnQ62nbB0+0bkjWkw3LoCdbVd2pOUay87xip51/hDds1yZJYFImc1ONSPExUflzasZ+J15C4UcS+7pvmae4/Mk7TZwFGexSWA==
user.login.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuIJcvjZNQ/xT4FltJVsWtt0DQunqwDmUGRuNm40cxUfm2mXP4mEFwZz7wMxUCOifUu0f2cmk+d2Gg/SfB89eT3uithrUIIvxkz1wcxab0z0+sRyzWNKEHvdkYc22F/GfXFs9soVvSUh15xnBlK+V2XtA0P0zHcKxRA9FffddE4Y1a/P75U8B7xMjJ1VliJkvAZfSy8thAAnKGxLQQL70xXXq4N+krR2fh0ghqIjbsVqIKUchvuod3jGGqlOlBm2ucXGX/Hrwt5pbO0nYKGE+gWyqWP7vLSfN6xolZ6nwKDX6DZgkaupOazLPxii1bR1QTDtQDHDWfc1m8BXSIKLjQwIDAQAB

##Org and Tenant Config Decryption key
drona.key=1234

##Security Audit Config
server.forward-headers-strategy=native
server.use-forward-headers=true
server.tomcat.use-relative-redirects=true
server.tomcat.protocol-header=x-forwarded-proto
server.tomcat.remote-ip-header=x-forwarded-for
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.path=/uiserver
server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.secure=true



################################################Component Config######################################################

##Spring API Params
springapi.server.url=http://main.dev.dronapay.net/springapi/


springapi.server.key.name=X-API-Key

##Simulator API Params
simulation.server.url=http://10.20.49.5:8000
simulation.server.username=simulatoruser
simulation.server.password=100!simulator

##Sanctions API Params
sanctions.api.url=http://10.20.48.111:8000
sanctions.api.username=sanctionsuser
sanctions.api.password=100!sanctions



mlflow.server.url=http://mlflow.prl.dronapay.net
mlflow.api.key=default_api_key

## DIA (Agent related)
dia.server.url=http://10.200.84.28:8000
dia.server.username=batchuser
dia.server.password=100!batch

##Camunda Params
camunda.server.url=http://localhost:8082
camunda.webusers.password=Dr0nap@y#2o22
camunda.frmuser.username=frmuser
camunda.frmuser.password=Dr0n@pay#2o22
camunda.schema=camunda

##Kafka Params

spring.kafka.bootstrap-servers=localhost:9095
spring.kafka.email-topic=email_request
spring.kafka.consumer.group-id=email_consumers
spring.kafka.consumer.max-poll-records=20
spring.kafka.producer.retries=3
spring.kafka.producer.properties.retry.backoff.ms=5000
spring.kafka.consumer.backoff.interval=5000
spring.kafka.consumer.backoff.max_failure=3
spring.kafka.listener.concurrency=1


################################################Organization specific config######################################################
##42C
42c.ivr.manualivr.url=http://172.16.100.221:8811
42c.ivr.ivrprefix=901191
pismo.url=xxx
tenant.id=xxx

##Pinelabs
pinelab.url=http://localhost:8085
pinelab.auth.url=http://localhost:8085
pinelab.tenant.id=1
pinelab.x.source=DronaPay
pinelab.x.operation.type=RiskTxn
pinelab.x.request.type=RISK
pinelab.auth.client.id=ZHJvbmFwYXlfY2xpZW50X2lk
pinelab.auth.client.secret=DronaPay|ClientSecret@Pinelabs
pinelab.auth.grant.type=CLIENT_CREDENTIALS
pinelab.auth.scope=sint Excepteur in elit laborum
pinelab.auth.api.key.name=X-app-clnt-id
pinelab.auth.api.key.value=1234  


############################################Configuration Flags######################################
##Client JWT
UIServer.Client.User.Enabled=false
##Email Service through Kafka
spring.kafka.email.enable=false
##Email response body processing
email.body.processing.enabled=true



###################################################### Application Functionality Params #####################################
##User Management
change.password.expiry=300000
minimum.password.length=8
max.password.length=20
account.lock.attempts=10
token.cleanup.day=7
usermanagement.groupid=usermgmt
password.history.limit=3

##Rule Management
rules.topic=rules
max.rule.ui.create=300

##Case Management and Upload chargeback params
file.upload-dir=/mnt/d/docker_data/uploads
template.download.path=/mnt/d/docker_data/templates
uploadchargeback.file.formats=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel
nonallowable.file.types=application/vnd.microsoft.portable-executable,application/octet-stream,application/x-msdownload,text/javascript,text/html,application/javascript
profilepic.file.types=image/jpeg,image/png
casemanagement.file.formats=image/png,image/jpeg,application/pdf,image/gif,application/msword,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv,application/vnd.openxmlformats-officedocument.wordprocessingml.document
chargeback.ui.upload.recordcount=1000
max.xml.field.length=1000


################################################# Miscellaneous #############################################

##File Storage utility
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

##Server health monitoring properties (for grafana dashboard)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

##Logback xml config file location


logging.config=/mnt/d/docker_data/logback.xml
heartbeat.interval=300000

##Other
codec.buffer.size=20
spring.main.allow-bean-definition-overriding=true
server.server-header=unspecified

##only for local
server.port=8085

bulk.processing.limit=1000
42c.UsfbIvrLink=asd
42c.CubIvrLink=asdf
42c.ESAFIvrLink=asdf
logo.directory=./logo
response.callback.api.url=asdf
idle.token.expiry.time=14
42c.SSFBIvrLink=asd



pinelab.enquiry.operation.type=RiskTxnEnquiry


execution.cache.timeout=10


resttemplate.connection.request.timeout=30
resttemplate.response.timeout=30
resttemplate.connection.timeout=30



##Cache Config
dashboard.error={"131075":"Resource limit reached, please try after some time.", "131074":"Resource limit reached, please try after some time.", "Too Many Records...": "Too Many Records...", "Failed Proccessing": "Error in processing! Please contact administrator...", "default":"Failed To Execute Query" }

#server.tomcat.relaxed-path-chars=|,[,],{,}
#server.tomcat.relaxed-query-chars=|,[,],{,}



server.error.include-stacktrace=never

batch.limit=2000
retry.count=3

batch.data.record.expiry=30


# MinIO Configuration
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=insurance-claims