ESAPI.Encoder=org.owasp.esapi.reference.DefaultEncoder
ESAPI.Logger=org.owasp.esapi.logging.slf4j.Slf4JLogFactory
Logger.ApplicationName=UIServer
Logger.LogEncodingRequired=false
Logger.LogApplicationName=true
Logger.LogServerIP=false
Logger.UserInfo=false
Logger.ClientInfo=false