//Add property in Camunda bpm-platform.xml
<property name="tenantResourceWhitelistPattern">.+</property>


CREATE TABLE IF NOT EXISTS ui.organizations
(
    iorgid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    attribs jsonb,
    dtentrystamp timestamp(6) without time zone,
    irecordstatus integer,
    vcorgid character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT organizations_pkey PRIMARY KEY (iorgid)
);

alter table if exists ui.webuser add column iorgid integer;
alter table if exists ui.webuseraudit add column iorgid integer;

alter table if exists ui.webuser add constraint FKauwaeio0r1wbp3yjufh4mg5tk foreign key (iorgid) references ui.organizations;
alter table if exists ui.webuseraudit add constraint FKio6fk7r3mbf2hdjj0yq1w16xp foreign key (iorgid) references ui.organizations;

//to be modified based on final config
INSERT INTO ui.organization (
vcorgid, vcorgname) VALUES (
'dronapay'::character varying, 'Drona Pay'::character varying)
 returning vcorgid;

INSERT INTO ui.roledesc (
iroleid, dtentrystamp, vcrolename, istatus, vcorgid) VALUES (
'13'::integer, '2023-10-28 12:30:10.223'::timestamp without time zone, 'Admin'::character varying, '1'::integer, 'dronapay'::character varying)
 returning iroleid;

CREATE TABLE IF NOT EXISTS ui.tenants
(
    itenantid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dtapproverstamp timestamp(6) without time zone,
    dtentrystamp timestamp(6) without time zone,
    attribs jsonb,
    irecordstatus integer,
    vctenantid character varying(255) COLLATE pg_catalog."default",
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    iorg_id integer,
    CONSTRAINT tenants_pkey PRIMARY KEY (itenantid),
    CONSTRAINT fkgmbsg8eg5lup1xd9ibnvclbp FOREIGN KEY (iorg_id)
        REFERENCES ui.organizations (iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkhcbfhnfvnmsjyh8byt29qv4dx FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkj2fkft6vglnsnkk0xvfysse0h FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkry8dqjfsrq5c17snj6cw41jis FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS ui.tenantsaudit
(
    itenantauditid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bclosed boolean NOT NULL,
    dtapproverstamp timestamp(6) without time zone,
    dtentrystamp timestamp(6) without time zone,
    vcaction character varying(3) COLLATE pg_catalog."default" NOT NULL,
    vcremark character varying(255) COLLATE pg_catalog."default",
    attribs jsonb,
    irecordstatus integer,
    vctenantid character varying(255) COLLATE pg_catalog."default",
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    iorgid integer,
    CONSTRAINT tenantsaudit_pkey PRIMARY KEY (itenantauditid),
    CONSTRAINT fk3q32e3w6d5bkme9docbxfh5o4 FOREIGN KEY (iorgid)
        REFERENCES ui.organizations (iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk3yj09gmfntacb8ekiplf0dpq0 FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkgpfp6n2jbijrksdq45hu4qdf6 FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkmsm6g5aagpa4b77gfn3oprux9 FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

alter table if exists ui.roledesc add column itenantid integer;
alter table if exists ui.groupdesc add column itenantid integer;
alter table if exists ui.transactionclasses add column itenantid integer;
alter table if exists ui.transactionclassesaudit add column itenantid integer;
alter table if exists ui.workflowmasters add column itenantid integer;

alter table if exists ui.groupdesc add constraint FKblasqgl06b26raossmlotj7xj foreign key (itenantid) references ui.tenants;
alter table if exists ui.roledesc add constraint FKpdoexhlbjvvprec0a3fi18p1o foreign key (itenantid) references ui.tenants;
alter table if exists ui.transactionclasses add constraint FK5s15xeosqycwmb431klvbhi9g foreign key (itenantid) references ui.tenants;
alter table if exists ui.transactionclassesaudit add constraint FKluqs2p5ds0p4tfkaccicyvv5w foreign key (itenantid) references ui.tenants;
alter table if exists ui.workflowmasters add constraint FK3aq7u7wva47mgnqtlf76mw40v foreign key (itenantid) references ui.tenants;

INSERT INTO ui.webuser (dtapproverstamp, dtentrystamp, dtlastlogindate, vcaddress, vccontact, vcdesignation, vcemailid, vcfirstname, vclastname, vcmobile, vcpassword, vcprofileimg, vcusername, iapproveruserid, ientryuserid, istatus, timezones, resetpasswordtoken, dtlastpasswordupdate, loginattempts, iorgid) VALUES ('2023-06-10 13:47:12.625', '2023-03-22 11:17:35.851', '2023-10-30 15:19:06.481', NULL, '9988', 'CEO', 'cadmin@dronapayadmin.com', 'cadmin', 'cadmin', '7219024345', '$2a$10$EoTv5mhWPRxMbRTBYJ0V4ucuG761Lb7Cp8T/pJZOc8/szTepMVNm.', '', 'cadmin@dronapayadmin.com', 2, 1, 1, 'Asia/Kolkata', '6HTThBznzAaZtr52O9YcsSEQ6ZaslB', '2023-10-09 19:46:14.746', 0, 1);
INSERT INTO ui.webuser (dtapproverstamp, dtentrystamp, dtlastlogindate, vcaddress, vccontact, vcdesignation, vcemailid, vcfirstname, vclastname, vcmobile, vcpassword, vcprofileimg, vcusername, iapproveruserid, ientryuserid, istatus, timezones, resetpasswordtoken, dtlastpasswordupdate, loginattempts, iorgid) VALUES ('2023-06-10 13:47:12.625', '2023-03-22 11:17:35.851', '2023-10-30 15:19:06.481', NULL, '9988', 'CEO', 'madmin@dronapayadmin.com', 'madmin', 'madmin', '7219024345', '$2a$10$EoTv5mhWPRxMbRTBYJ0V4ucuG761Lb7Cp8T/pJZOc8/szTepMVNm.', '', 'madmin@dronapayadmin.com', 2, 1, 1, 'Asia/Kolkata', '6HTThBznzAaZtr52O9YcsSEQ6ZaslB', '2023-10-09 19:46:14.746', 0, 1);

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES ((select iroleid from ui.roledesc where vcrolename='Admin'),
'Role', (select iuserid from ui.webuser where vcusername='cadmin@dronapayadmin.com'));

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES ((select iroleid from ui.roledesc where vcrolename='Admin'),
'Role', (select iuserid from ui.webuser where vcusername='madmin@dronapayadmin.com'));

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '482'::integer, '13'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '501'::integer, '13'::integer)
 returning irolemenumapid;

INSERT INTO ui.menustructuredesc (
imenuid, bcollapse, isortorder, vcaction, vccontroller, vclayout, vcmenuname, vcmini, vcpath, iparentmenu, istatus) VALUES (
'579'::integer, false::boolean, '-1'::integer, 'tenantManagement'::character varying, 'tenantManagement'::character varying, '/user'::character varying, 'Tenant Management'::character varying, 'TM'::character varying, '/admin/tenant-management'::character varying, '482'::integer, '1'::integer)
 returning imenuid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '579'::integer, '13'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '513'::integer, '13'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '514'::integer, '13'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '518'::integer, '13'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '519'::integer, '13'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '520'::integer, '13'::integer)
 returning irolemenumapid;

INSERT INTO ui.webuser (dtapproverstamp, dtentrystamp, dtlastlogindate, vcaddress, vccontact, vcdesignation, vcemailid, vcfirstname, vclastname, vcmobile, vcpassword, vcprofileimg, vcusername, iapproveruserid, ientryuserid, istatus, timezones, resetpasswordtoken, dtlastpasswordupdate, loginattempts, iorgid) VALUES ('2023-06-10 13:47:12.625', '2023-03-22 11:17:35.851', '2023-10-30 15:19:06.481', NULL, '9988', 'CEO', 'cadmin@yesbank.com', 'cadmin', 'cadmin', '7219024345', '$2a$10$EoTv5mhWPRxMbRTBYJ0V4ucuG761Lb7Cp8T/pJZOc8/szTepMVNm.', '', 'cadmin@yesbank.com', 2, 1, 1, 'Asia/Kolkata', '6HTThBznzAaZtr52O9YcsSEQ6ZaslB', '2023-10-09 19:46:14.746', 0, 2);
INSERT INTO ui.webuser (dtapproverstamp, dtentrystamp, dtlastlogindate, vcaddress, vccontact, vcdesignation, vcemailid, vcfirstname, vclastname, vcmobile, vcpassword, vcprofileimg, vcusername, iapproveruserid, ientryuserid, istatus, timezones, resetpasswordtoken, dtlastpasswordupdate, loginattempts, iorgid) VALUES ('2023-06-10 13:47:12.625', '2023-03-22 11:17:35.851', '2023-10-30 15:19:06.481', NULL, '9988', 'CEO', 'madmin@yesbank.com', 'madmin', 'madmin', '7219024345', '$2a$10$EoTv5mhWPRxMbRTBYJ0V4ucuG761Lb7Cp8T/pJZOc8/szTepMVNm.', '', 'madmin@yesbank.com', 2, 1, 1, 'Asia/Kolkata', '6HTThBznzAaZtr52O9YcsSEQ6ZaslB', '2023-10-09 19:46:14.746', 0, 2);


INSERT INTO ui.tenants (
itenantid, dtapproverstamp, dtentrystamp, attribs, vctenantid, iapproveruserid, ientryuserid, istatus, iorg_id) VALUES (
'2'::integer, '2023-11-01 19:08:15.102'::timestamp without time zone, '2023-11-01 19:05:24.377'::timestamp without time zone, '{
  "tenantName": "YesBank-AML",
  "inboundEmailSettings": {},
  "outboundEmailSettings": {}
}'::jsonb, 'c2cd1968-e159-408f-819b-549876195871'::character varying, '56'::integer, '55'::integer, '1'::integer, '2'::integer)
 returning itenantid;

 INSERT INTO ui.roledesc (
iroleid, vcrolename, istatus, itenantid) VALUES (
'17'::integer, 'Risk Analyst-AML'::character varying, '1'::integer, '2'::integer)
 returning iroleid;
 INSERT INTO ui.roledesc (
iroleid, vcrolename, istatus, itenantid) VALUES (
'16'::integer, 'Risk Analyst-FRM'::character varying, '1'::integer, '1'::integer)
 returning iroleid;
 INSERT INTO ui.roledesc (
iroleid, vcrolename, istatus, itenantid) VALUES (
'15'::integer, 'God-AML'::character varying, '1'::integer, '1'::integer)
 returning iroleid;
 INSERT INTO ui.roledesc (
iroleid, vcrolename, istatus, itenantid) VALUES (
'14'::integer, 'God-FRM'::character varying, '1'::integer, '1'::integer)
 returning iroleid;

/////god frm role configuration

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '482'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '501'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '513'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '514'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '518'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '519'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '520'::integer, '14'::integer)
 returning irolemenumapid;

 INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '481'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '521'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '522'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '528'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '529'::integer, '14'::integer)
 returning irolemenumapid;


INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '530'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '499'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '511'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '515'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '524'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '525'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '526'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '527'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '563'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '564'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '565'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '566'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '567'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '568'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '569'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '570'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '571'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '547'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '548'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '549'::integer, '14'::integer)
 returning irolemenumapid;
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '550'::integer, '14'::integer)
 returning irolemenumapid; 
INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '551'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '552'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '553'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '554'::integer, '14'::integer)
 returning irolemenumapid;

 INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '555'::integer, '14'::integer)
 returning irolemenumapid;

 INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '556'::integer, '14'::integer)
 returning irolemenumapid;


 INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '557'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '558'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '559'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '560'::integer, '14'::integer)
 returning irolemenumapid;

INSERT INTO ui.rolemenuaccessmap (
badd, bapprove, bdelete, bedit, bpublish, bview, istatus, imenuid, iroleid) VALUES (
true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, true::boolean, '561'::integer, '14'::integer)
 returning irolemenumapid;

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES ((select iroleid from ui.roledesc where vcrolename='God-FRM'),
'Role', (select iuserid from ui.webuser where vcusername='cadmin@yesbank.com'));

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES ((select iroleid from ui.roledesc where vcrolename='God-FRM'),
'Role', (select iuserid from ui.webuser where vcusername='madmin@yesbank.com'));

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES (-1,
'TransactionClass', (select iuserid from ui.webuser where vcusername='madmin@yesbank.com'));

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES (-1,
'TransactionClass', (select iuserid from ui.webuser where vcusername='cadmin@yesbank.com'));

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES (-1,
'Workflow', (select iuserid from ui.webuser where vcusername='madmin@yesbank.com'));

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES (-1,
'Workflow', (select iuserid from ui.webuser where vcusername='cadmin@yesbank.com'));

INSERT INTO ui.groupdesc (
igroupid, vcgroupid, vcgroupname, vcgrouptype, istatus, itenantid) VALUES (
'2003'::integer, 'level2'::character varying, 'L2 AML'::character varying, 'WORKFLOW'::character varying, '1'::integer, '2'::integer)
 returning igroupid;
 INSERT INTO ui.groupdesc (
igroupid, vcgroupid, vcgroupname, vcgrouptype, istatus, itenantid) VALUES (
'2000'::integer, 'riskanalyst'::character varying, 'Risk Analyst FRM'::character varying, 'WORKFLOW'::character varying, '1'::integer, '1'::integer)
 returning igroupid;
 INSERT INTO ui.groupdesc (
igroupid, vcgroupid, vcgroupname, vcgrouptype, istatus, itenantid) VALUES (
'2001'::integer, 'risksupervisor'::character varying, 'Risk Supervisor FRM'::character varying, 'WORKFLOW'::character varying, '1'::integer, '1'::integer)
 returning igroupid;
 INSERT INTO ui.groupdesc (
igroupid, vcgroupid, vcgroupname, vcgrouptype, istatus, itenantid) VALUES (
'2002'::integer, 'level1'::character varying, 'L1 AML'::character varying, 'WORKFLOW'::character varying, '1'::integer, '2'::integer)
 returning igroupid;

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES (1,
'Tenant', (select iuserid from ui.webuser where vcusername='cadmin@yesbank.com'));
insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES (2,
'Tenant', (select iuserid from ui.webuser where vcusername='cadmin@yesbank.com'));

insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES (1,
'Tenant', (select iuserid from ui.webuser where vcusername='madmin@yesbank.com'));
insert into ui.webusermapping (mappingid, mappingtype, webuserid) VALUES (2,
'Tenant', (select iuserid from ui.webuser where vcusername='madmin@yesbank.com'));

alter table if exists ui.decisions add column itenantid integer;
alter table if exists ui.decisionsaudit add column itenantid integer;

alter table if exists ui.decisions add constraint FKo3196afavrgekf3gx4r2y98jh foreign key (itenantid) references ui.tenants;
alter table if exists ui.decisionsaudit add constraint FK1yim5axqjombl3lkuev1uvj0e foreign key (itenantid) references ui.tenants;

alter table if exists ui.decisionsworkflowaudit add column itenantid integer;
alter table if exists ui.decisionsworkflowaudit add constraint FKry7ecqpgfuj59f6yottchr7a8 foreign key (itenantid) references ui.tenants;

alter table if exists ui.listmaster add column itenantid integer;
alter table if exists ui.listmaster add constraint FK8rkg8s6neaa0qy8oyq8nkmbmv foreign key (itenantid) references ui.tenants;

alter table if exists ui.list add column itenantid integer;
alter table if exists ui.list add constraint FKqpje45spmgcwnptm3yu2ifgt0 foreign key (itenantid) references ui.tenants;

alter table if exists ui.listaudit add column itenantid integer;
alter table if exists ui.listaudit add constraint FKa0o2o3gjivwqq27ul0qikterv foreign key (itenantid) references ui.tenants;

alter table if exists ui.observationwindowsuiaudit add column itenantid integer;
alter table if exists ui.observationwindowsui add column itenantid integer;

alter table if exists ui.observationwindowsuiaudit add constraint FK556eb6668ot8da6tmh9ffvcdr foreign key (itenantid) references ui.tenants;
alter table if exists ui.observationwindowsui add constraint FK1rmbw11hhfud0o1h6xx2de7x0 foreign key (itenantid) references ui.tenants;

alter table if exists profiles.metadata add column itenantid integer;

alter table if exists ui.metadata add column itenantid integer;
alter table if exists ui.metadataaudit add column itenantid integer;

alter table if exists ui.metadata add constraint FKep83wispcpxdqsgqntyaiu7yt foreign key (itenantid) references ui.tenants;
alter table if exists ui.metadataaudit add constraint FK8mjwwf9r8gwebjnxcv8rb50ew foreign key (itenantid) references ui.tenants;



-- alter table if exists ui.observationsui add column itenantid integer;
-- alter table if exists ui.observationsuiaudit add column itenantid integer;

-- alter table if exists ui.observationsui add constraint FK11oywdn61ql6cp84ol62di6in foreign key (itenantid) references ui.tenants;
-- alter table if exists ui.observationsuiaudit add constraint FK4kqcxb1ev3rntmu5jry8pk1k foreign key (itenantid) references ui.tenants;