----Admin->Admin Reports

--Audit Report Rules
UPDATE ui.dashboardquery SET
vcdashboardquery = 'SELECT d.vcdecisionname as "Decision Name", r.iruleid as "Rule ID", r.vcrulename as "Rule Name", makeruser.vcusername as "Maker User", r.dtentrystamp at time zone ''asia/kolkata'' as "Maker Time Stamp", r.vcremark as "Maker & Checker Remarks", checkeruser.vcusername as "Checker User", r.dtapproverstamp at time zone ''asia/kolkata'' as "Checker Time Stamp", case when r.vcaction = ''A'' then ''Add'' when r.vcaction = ''M'' then ''Modify'' when r.vcaction = ''X'' then ''Delete'' when r.vcaction = ''N'' then ''No Change'' end as "Action", iversion as "Rule Version", vclabel as "Rule Label", vcruledescription as "Rule Description", vcruledetail as "Rule Detail", vcruleparams as "Rule Params", vcruleorder as "Rule Order" FROM ui.rulesaudit r inner join ui.decisions d on r.idecisionid = d.idecisionid  left join ui.webuser makeruser on makeruser.iuserid = r.ientryuserid left join ui.webuser checkeruser on checkeruser.iuserid = r.iapproveruserid where d.itenantid = :tenantid and cast(r.dtentrystamp as date) between cast(:StartDate as date) and cast(:EndDate as date)-1;'::text WHERE
idashboardqueryid = 82;

--Audit Report Class
UPDATE ui.dashboardquery SET
vcdashboardquery = 'SELECT r.vcclassname as "Class Name", r.iclassid as "Class ID",  d.vcdecisionname as "Decision Name", p.vcproductname as "Product Name", c.vcchannelname as "Channel Name", makeruser.vcusername as "Maker User", r.dtentrystamp at time zone ''asia/kolkata'' as "Maker Time Stamp", r.vcremark as "Maker & Checker Remarks", checkeruser.vcusername as "Checker User", r.dtapproverstamp at time zone ''asia/kolkata'' as "Checker Time Stamp", case when r.vcaction = ''A'' then ''Add'' when r.vcaction = ''M'' then ''Modify'' when r.vcaction = ''X'' then ''Delete'' when r.vcaction = ''N'' then ''No Change'' end as "Action", r.bpayeemandatory as "Payee Mandatory", r.bpayermandatory  as "Payer Mandatory", cast(r.vcdecisionparams as text)   as "Decision Parameters", r.skipprocessing   as "Skip Processing" FROM ui.transactionclassesaudit r left join ui.decisions d on r.idecisionid = d.idecisionid left join masters.products p on r.iproductid = p.iproductid left join masters.channels c on r.ichannelid = c.ichannelid left join ui.webuser makeruser on makeruser.iuserid = r.ientryuserid left join ui.webuser checkeruser on checkeruser.iuserid = r.iapproveruserid where r.itenantid = :tenantid and cast(r.dtentrystamp as date) between cast(:StartDate as date) and cast(:EndDate as date)-1;'::text WHERE
idashboardqueryid = 83;

---Audit Report Decision
UPDATE ui.dashboardquery SET
vcdashboardquery = 'SELECT r.vcdecisionname as "Decision Name", r.vcdecisiondetail  as "Decision Description",  r.idecisionid as "Decision ID", makeruser.vcusername as "Maker User", r.dtentrystamp at time zone ''asia/kolkata'' as "Maker Time Stamp", r.vcremark as "Maker & Checker Remarks", checkeruser.vcusername as "Checker User", r.dtapproverstamp at time zone ''asia/kolkata'' as "Checker Time Stamp", case when r.vcaction = ''A'' then ''Add'' when r.vcaction = ''M'' then ''Modify'' when r.vcaction = ''X'' then ''Delete'' when r.vcaction = ''N'' then ''No Change'' end as "Action", cast(r.vcresultparams as text) as "Decision Parameters", p.vcproductname as "Product Name", cast(r.attribs as text) as "Attributes", r.vcdecisionmapinfo as "Decision Info" FROM ui.decisionsworkflowaudit r left join masters.products p on r.iproductid = p.iproductid left join ui.webuser makeruser on makeruser.iuserid = r.ientryuserid left join ui.webuser checkeruser on checkeruser.iuserid = r.iapproveruserid where r.itenantid = :tenantid and cast(r.dtentrystamp at time zone :timeZone as date) between cast(:StartDate as date) and cast(:EndDate as date)-1;'::text WHERE
idashboardqueryid = 84;

--Audit Report Windows
UPDATE ui.dashboardquery SET
vcdashboardquery = 'SELECT r.wname as  "Window Name", r.wdesc as  "Window Description", r.wid "Window ID", makeruser.vcusername as "Maker User", r.dtentrystamp at time zone ''asia/kolkata'' as "Maker Time Stamp", r.vcremark as "Maker & Checker Remarks", checkeruser.vcusername as "Checker User", r.dtapproverstamp at time zone ''asia/kolkata'' as "Checker Time Stamp", case when r.vcaction = ''A'' then ''Add'' when r.vcaction = ''M'' then ''Modify'' when r.vcaction = ''X'' then ''Delete'' when r.vcaction = ''N'' then ''No Change'' end as "Action", cast(r.selectexpr as text) as "Select", cast(r.whereexpr as text) as "Where", cast(r.groupbyexpr as text) as "Group By", r.wcount as "Window Count", r.wduration as "Window Duration" FROM ui.observationwindowsuiaudit r left join ui.webuser makeruser on makeruser.iuserid = r.ientryuserid left join ui.webuser checkeruser on checkeruser.iuserid = r.iapproveruserid where r.itenantid = :tenantid and cast(r.dtentrystamp at time zone :timeZone as date) between cast(:StartDate as date) and cast(:EndDate as date)-1;'::text WHERE
idashboardqueryid = 85;

--Audit Report Observations
UPDATE ui.dashboardquery SET
vcdashboardquery = 'SELECT r.oname  as "Observation Name", r.odesc as  "Observation Description", r.oid as "Observation ID", w.wname as "Window Name", makeruser.vcusername as "Maker User", r.dtentrystamp at time zone ''asia/kolkata'' as "Maker Time Stamp", r.vcremark as "Maker & Checker Remarks", checkeruser.vcusername as "Checker User", r.dtapproverstamp at time zone ''asia/kolkata'' as "Checker Time Stamp", case when r.vcaction = ''A'' then ''Add'' when r.vcaction = ''M'' then ''Modify'' when r.vcaction = ''X'' then ''Delete'' when r.vcaction = ''N'' then ''No Change'' end as "Action", cast(r.wexpr as text) as "Group By", cast(r.whereexpr as text) as "Where", r.aggregationtype as "Aggregation", r.oduration as "Duration", r.ocount as "Observation Count" FROM ui.observationsuiaudit r left join ui.observationwindowsui w on w.wid = r.wid left join ui.webuser makeruser on makeruser.iuserid = r.ientryuserid left join ui.webuser checkeruser on checkeruser.iuserid = r.iapproveruserid where w.itenantid = :tenantid and cast(r.dtentrystamp at time zone :timeZone as date) between cast(:StartDate as date) and cast(:EndDate as date)-1;'::text WHERE
idashboardqueryid = 86;

--Audit Report User Management
UPDATE ui.dashboardquery SET
vcdashboardquery = 'SELECT r.vcusername as "User Name", r.vcfirstname as  "First Name", r.vclastname as "Last Name", r.vcemailid as "Email ID", r.iuserid as  "User ID", r.vcmobile as "Mobile", makeruser.vcusername as "Maker User", r.dtentrystamp at time zone ''asia/kolkata'' as "Maker Time Stamp", r.vcremark as "Maker & Checker Remarks", checkeruser.vcusername as "Checker User", r.dtapproverstamp at time zone ''asia/kolkata'' as "Checker Time Stamp", case when r.vcaction = ''A'' then ''Add'' when r.vcaction = ''M'' then ''Modify'' when r.vcaction = ''X'' then ''Delete'' when r.vcaction = ''N'' then ''No Change'' end as "Action", r.vcaddress as "Address", r.vccontact as "Contact", r.vcdesignation as "Designation" FROM ui.webuseraudit r left join ui.webuser makeruser on makeruser.iuserid = r.ientryuserid left join ui.webuser checkeruser on checkeruser.iuserid = r.iapproveruserid where r.iuserauditid in (select webuserauditid from ui.webusermappingaudit where mappingid = :tenantid and mappingtype = ''Tenant'') and cast(r.dtentrystamp at time zone :timeZone as date) between cast(:StartDate as date) and cast(:EndDate as date)-1;'::text WHERE
idashboardqueryid = 87;

--Audit Report Metadata
UPDATE ui.dashboardquery SET
vcdashboardquery = 'SELECT r.vccolumnname as "Parameter Name", r.vcdescription as   "Parameter Description", r.vcdtype as "Data Type", cast(r.vcprefix as text) as "Prefix", r.vcpath as "Path", r.vcroot as "Root Level", r.bml as "ML", r.bscore as "Score", r.bui as "UI", cast(r.config as text) as "Config", makeruser.vcusername as "Maker User", r.dtentrystamp at time zone ''asia/kolkata'' as "Maker Time Stamp", r.vcremark as "Maker & Checker Remarks", checkeruser.vcusername as "Checker User", r.dtapproverstamp at time zone ''asia/kolkata'' as "Checker Time Stamp", case when r.vcaction = ''A'' then ''Add'' when r.vcaction = ''M'' then ''Modify'' when r.vcaction = ''X'' then ''Delete'' when r.vcaction = ''N'' then ''No Change'' end as "Action" FROM ui.metadataaudit r left join ui.webuser makeruser on makeruser.iuserid = r.ientryuserid left join ui.webuser checkeruser on checkeruser.iuserid = r.iapproveruserid where r.itenantid = :tenantid and cast(r.dtentrystamp at time zone :timeZone as date) between cast(:StartDate as date) and cast(:EndDate as date)-1;'::text WHERE
idashboardqueryid = 88;

--Audit Report Activity Log
UPDATE ui.dashboardquery SET
vcdashboardquery = 'SELECT makeruser.vcusername as "User Name", r.dtactivity at time zone ''asia/kolkata'' as  "Time stamp", r.vcactivity as "UI", r.vcparameters as "Query Parameter" FROM ui.activitylog r left join ui.webuser makeruser on makeruser.iuserid = r.iuserid where makeruser.iuserid in (select webuserid from ui.webusermapping where mappingid = :tenantid and mappingtype = ''Tenant'') and cast(r.dtactivity at time zone :timeZone as date) between cast(:StartDate as date) and cast(:EndDate as date)-1;'::text WHERE
idashboardqueryid = 89;