CREATE TABLE IF NOT EXISTS ui.tenant
(
    tid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    b_delete boolean,
    createddate timestamp without time zone,
    differentstatemodelid character varying(255) COLLATE pg_catalog."default",
    lastupdatedate timestamp without time zone,
    samesatetmodelid character varying(255) COLLATE pg_catalog."default",
    serverkey character varying(255) COLLATE pg_catalog."default",
    serversceret character varying(255) COLLATE pg_catalog."default",
    status boolean,
    tenantid character varying(255) COLLATE pg_catalog."default",
    tenantlogo character varying(255) COLLATE pg_catalog."default",
    tenantname character varying(255) COLLATE pg_catalog."default",
    tenanttype character varying(255) COLLATE pg_catalog."default",
    ientryuserid integer,
    CONSTRAINT tenant_pkey PRIMARY KEY (tid),
    CONSTRAINT uk_ipglwn180mo0jhsw7b58h092g UNIQUE (tenantid),
    CONSTRAINT fkr1l1lfecev7agnrgak8ax5pce FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

INSERT INTO ui.tenant (tid, b_delete, createddate, differentstatemodelid, lastupdatedate, samesatetmodelid, serverkey, serversceret, status, tenantid, tenantlogo, tenantname, tenanttype, ientryuserid) VALUES (1, false, '2022-09-21 23:39:56.166', '4eaad49f-1740-4f06-8127-72d2267836c8', '2022-09-21 23:39:56.166', '02bbc612-c864-46e8-bc36-ac89558619f1', '172875e27a19dbd224b5814377833c8630316d7a', '}.G4M:.Xo1<F}mA~:8B$X{Y3iSVYcr+4!.H+k,I#>dPPx(:?', true, 'TN-87b1d861-2b07-4cdf-bd24-8a3b3c0354e9', NULL, 'CUB SandBox', 'SandBox', 1);
