--dashboardquery

--PAYTM (17)

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (178, 'true', '{"processinstanceid": null}', 'SELECT ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", ACT_TYPE_ AS "activityType", ACT_NAME_ AS "activityName", ASSIGNEE_ AS "assignee", TASK_ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN ACT_INST_STATE_ = 2 THEN TRUE ELSE FALSE END AS "canceled" FROM t17refined.camunda.ACT_HI_ACTINST WHERE PROC_INST_ID_ = :processinstanceid AND ACT_TYPE_ IN ( ''userTask'', ''noneEndEvent'', ''startEvent'', ''sendTask'', ''receiveTask'' ) ORDER BY START_TIME_ DESC', 'false', 'false', 'false', 494, 17, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (179, 'true', '{"processdefid": null}', 'SELECT PD.ID_ AS "id", FROM_UTF8(BA.BYTES_) AS "bpmn20Xml" FROM postgresql.camunda.ACT_RE_PROCDEF PD JOIN postgresql.camunda.ACT_GE_BYTEARRAY BA ON PD.DEPLOYMENT_ID_ = BA.DEPLOYMENT_ID_ AND PD.RESOURCE_NAME_ = BA.NAME_ WHERE PD.ID_ = :processdefid', 'false', 'false', 'false', 494, 17, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (180, 'true', '{"processinstanceid": null}', 'SELECT RES.ID_ AS "id", RES.PROC_INST_ID_ AS "processInstanceId", RES.TYPE_ AS "type", RES.ACT_INST_ID_ AS "activityInstanceId", RES.TASK_ID_ AS "taskId", RES.NAME_ AS "name", RES.TEXT_ AS "value", RES.TIME_ AS "time", RES.TENANT_ID_ AS "tenantId" FROM t17refined.camunda.ACT_HI_DETAIL RES LEFT JOIN t17refined.camunda.ACT_GE_BYTEARRAY BA ON RES.BYTEARRAY_ID_ = BA.ID_ WHERE RES.PROC_INST_ID_ = :processinstanceid AND ( ( RES.TYPE_ = ''VariableUpdate'' AND RES.NAME_ IN ( ''userActivity'', ''checker_action_whitelist_obj'', ''strHistoryUpdate'', ''AlertIDs'', ''parentProcess'' ) ) OR ( RES.TYPE_ = ''FormProperty'' AND ( RES.NAME_ IN ( ''Remarks'', ''DocumentReviewRemarks'', ''Action1'', ''Action2'', ''Action'', ''Block'' ) OR RES.NAME_ LIKE ''Action%'' ) ) )', 'false', 'false', 'false', 494, 17, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (181, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", TASK_ID_ AS "taskId", TIME_ AS "time", MESSAGE_ AS "message" FROM t17refined.camunda.ACT_HI_COMMENT WHERE TASK_ID_ in (:taskids) AND TYPE_ = ''comment''', 'false', 'false', 'false', 494, 17, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (182, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", NAME_ AS "name", TASK_ID_ AS "taskId", CREATE_TIME_ AS "createTime", DESCRIPTION_ AS "description" FROM t17refined.camunda.ACT_HI_ATTACHMENT WHERE TASK_ID_ IN (:taskids)', 'false', 'false', 'false', 494, 17, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (183, 'true', '{"taskids": null}', 'SELECT ACT_INST_ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", NAME_ AS "activityName", ASSIGNEE_ AS "assignee", ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TASK_DEF_KEY_ AS "activityId", TENANT_ID_ AS "tenantId", CASE WHEN DELETE_REASON_ IS NOT NULL AND LOWER(DELETE_REASON_) LIKE ''%cancel%'' THEN TRUE ELSE FALSE END AS "canceled" FROM t17refined.camunda.ACT_HI_TASKINST WHERE ID_ IN (:taskids)', 'false', 'false', 'false', 494, 17, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (184, 'true', '{"processinstanceid": null}', 'SELECT PROC_DEF_ID_ AS "processDefinitionId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN STATE_ = ''CANCELED'' THEN TRUE ELSE FALSE END AS "canceled" FROM t17refined.camunda.ACT_HI_PROCINST WHERE ID_ = :processinstanceid', 'false', 'false', 'false', 494, 17, 3);

--BAPA (8)

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (178, 'true', '{"processinstanceid": null}', 'SELECT ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", ACT_TYPE_ AS "activityType", ACT_NAME_ AS "activityName", ASSIGNEE_ AS "assignee", TASK_ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN ACT_INST_STATE_ = 2 THEN TRUE ELSE FALSE END AS "canceled" FROM t8refined.camunda.ACT_HI_ACTINST WHERE PROC_INST_ID_ = :processinstanceid AND ACT_TYPE_ IN ( ''userTask'', ''noneEndEvent'', ''startEvent'', ''sendTask'', ''receiveTask'' ) ORDER BY START_TIME_ DESC', 'false', 'false', 'false', 494, 8, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (179, 'true', '{"processdefid": null}', 'SELECT PD.ID_ AS "id", FROM_UTF8(BA.BYTES_) AS "bpmn20Xml" FROM postgresql.camunda.ACT_RE_PROCDEF PD JOIN postgresql.camunda.ACT_GE_BYTEARRAY BA ON PD.DEPLOYMENT_ID_ = BA.DEPLOYMENT_ID_ AND PD.RESOURCE_NAME_ = BA.NAME_ WHERE PD.ID_ = :processdefid', 'false', 'false', 'false', 494, 8, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (180, 'true', '{"processinstanceid": null}', 'SELECT RES.ID_ AS "id", RES.PROC_INST_ID_ AS "processInstanceId", RES.TYPE_ AS "type", RES.ACT_INST_ID_ AS "activityInstanceId", RES.TASK_ID_ AS "taskId", RES.NAME_ AS "name", RES.TEXT_ AS "value", RES.TIME_ AS "time", RES.TENANT_ID_ AS "tenantId" FROM t8refined.camunda.ACT_HI_DETAIL RES LEFT JOIN t8refined.camunda.ACT_GE_BYTEARRAY BA ON RES.BYTEARRAY_ID_ = BA.ID_ WHERE RES.PROC_INST_ID_ = :processinstanceid AND ( ( RES.TYPE_ = ''VariableUpdate'' AND RES.NAME_ IN ( ''userActivity'', ''checker_action_whitelist_obj'', ''strHistoryUpdate'', ''AlertIDs'', ''parentProcess'' ) ) OR ( RES.TYPE_ = ''FormProperty'' AND ( RES.NAME_ IN ( ''Remarks'', ''DocumentReviewRemarks'', ''Action1'', ''Action2'', ''Action'', ''Block'' ) OR RES.NAME_ LIKE ''Action%'' ) ) )', 'false', 'false', 'false', 494, 8, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (181, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", TASK_ID_ AS "taskId", TIME_ AS "time", MESSAGE_ AS "message" FROM t8refined.camunda.ACT_HI_COMMENT WHERE TASK_ID_ in (:taskids) AND TYPE_ = ''comment''', 'false', 'false', 'false', 494, 8, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (182, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", NAME_ AS "name", TASK_ID_ AS "taskId", CREATE_TIME_ AS "createTime", DESCRIPTION_ AS "description" FROM t8refined.camunda.ACT_HI_ATTACHMENT WHERE TASK_ID_ IN (:taskids)', 'false', 'false', 'false', 494, 8, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (183, 'true', '{"taskids": null}', 'SELECT ACT_INST_ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", NAME_ AS "activityName", ASSIGNEE_ AS "assignee", ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TASK_DEF_KEY_ AS "activityId", TENANT_ID_ AS "tenantId", CASE WHEN DELETE_REASON_ IS NOT NULL AND LOWER(DELETE_REASON_) LIKE ''%cancel%'' THEN TRUE ELSE FALSE END AS "canceled" FROM t8refined.camunda.ACT_HI_TASKINST WHERE ID_ IN (:taskids)', 'false', 'false', 'false', 494, 8, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (184, 'true', '{"processinstanceid": null}', 'SELECT PROC_DEF_ID_ AS "processDefinitionId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN STATE_ = ''CANCELED'' THEN TRUE ELSE FALSE END AS "canceled" FROM t8refined.camunda.ACT_HI_PROCINST WHERE ID_ = :processinstanceid', 'false', 'false', 'false', 494, 8, 3);

--PMTAGG (21)

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (178, 'true', '{"processinstanceid": null}', 'SELECT ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", ACT_TYPE_ AS "activityType", ACT_NAME_ AS "activityName", ASSIGNEE_ AS "assignee", TASK_ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN ACT_INST_STATE_ = 2 THEN TRUE ELSE FALSE END AS "canceled" FROM t21refined.camunda.ACT_HI_ACTINST WHERE PROC_INST_ID_ = :processinstanceid AND ACT_TYPE_ IN ( ''userTask'', ''noneEndEvent'', ''startEvent'', ''sendTask'', ''receiveTask'' ) ORDER BY START_TIME_ DESC', 'false', 'false', 'false', 494, 21, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (179, 'true', '{"processdefid": null}', 'SELECT PD.ID_ AS "id", FROM_UTF8(BA.BYTES_) AS "bpmn20Xml" FROM postgresql.camunda.ACT_RE_PROCDEF PD JOIN postgresql.camunda.ACT_GE_BYTEARRAY BA ON PD.DEPLOYMENT_ID_ = BA.DEPLOYMENT_ID_ AND PD.RESOURCE_NAME_ = BA.NAME_ WHERE PD.ID_ = :processdefid', 'false', 'false', 'false', 494, 21, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (180, 'true', '{"processinstanceid": null}', 'SELECT RES.ID_ AS "id", RES.PROC_INST_ID_ AS "processInstanceId", RES.TYPE_ AS "type", RES.ACT_INST_ID_ AS "activityInstanceId", RES.TASK_ID_ AS "taskId", RES.NAME_ AS "name", RES.TEXT_ AS "value", RES.TIME_ AS "time", RES.TENANT_ID_ AS "tenantId" FROM t21refined.camunda.ACT_HI_DETAIL RES LEFT JOIN t21refined.camunda.ACT_GE_BYTEARRAY BA ON RES.BYTEARRAY_ID_ = BA.ID_ WHERE RES.PROC_INST_ID_ = :processinstanceid AND ( ( RES.TYPE_ = ''VariableUpdate'' AND RES.NAME_ IN ( ''userActivity'', ''checker_action_whitelist_obj'', ''strHistoryUpdate'', ''AlertIDs'', ''parentProcess'' ) ) OR ( RES.TYPE_ = ''FormProperty'' AND ( RES.NAME_ IN ( ''Remarks'', ''DocumentReviewRemarks'', ''Action1'', ''Action2'', ''Action'', ''Block'' ) OR RES.NAME_ LIKE ''Action%'' ) ) )', 'false', 'false', 'false', 494, 21, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (181, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", TASK_ID_ AS "taskId", TIME_ AS "time", MESSAGE_ AS "message" FROM t21refined.camunda.ACT_HI_COMMENT WHERE TASK_ID_ in (:taskids) AND TYPE_ = ''comment''', 'false', 'false', 'false', 494, 21, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (182, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", NAME_ AS "name", TASK_ID_ AS "taskId", CREATE_TIME_ AS "createTime", DESCRIPTION_ AS "description" FROM t21refined.camunda.ACT_HI_ATTACHMENT WHERE TASK_ID_ IN (:taskids)', 'false', 'false', 'false', 494, 21, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (183, 'true', '{"taskids": null}', 'SELECT ACT_INST_ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", NAME_ AS "activityName", ASSIGNEE_ AS "assignee", ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TASK_DEF_KEY_ AS "activityId", TENANT_ID_ AS "tenantId", CASE WHEN DELETE_REASON_ IS NOT NULL AND LOWER(DELETE_REASON_) LIKE ''%cancel%'' THEN TRUE ELSE FALSE END AS "canceled" FROM t21refined.camunda.ACT_HI_TASKINST WHERE ID_ IN (:taskids)', 'false', 'false', 'false', 494, 21, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (184, 'true', '{"processinstanceid": null}', 'SELECT PROC_DEF_ID_ AS "processDefinitionId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN STATE_ = ''CANCELED'' THEN TRUE ELSE FALSE END AS "canceled" FROM t21refined.camunda.ACT_HI_PROCINST WHERE ID_ = :processinstanceid', 'false', 'false', 'false', 494, 21, 3);

--GIFTCARD (22)

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (178, 'true', '{"processinstanceid": null}', 'SELECT ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", ACT_TYPE_ AS "activityType", ACT_NAME_ AS "activityName", ASSIGNEE_ AS "assignee", TASK_ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN ACT_INST_STATE_ = 2 THEN TRUE ELSE FALSE END AS "canceled" FROM t22refined.camunda.ACT_HI_ACTINST WHERE PROC_INST_ID_ = :processinstanceid AND ACT_TYPE_ IN ( ''userTask'', ''noneEndEvent'', ''startEvent'', ''sendTask'', ''receiveTask'' ) ORDER BY START_TIME_ DESC', 'false', 'false', 'false', 494, 22, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (179, 'true', '{"processdefid": null}', 'SELECT PD.ID_ AS "id", FROM_UTF8(BA.BYTES_) AS "bpmn20Xml" FROM postgresql.camunda.ACT_RE_PROCDEF PD JOIN postgresql.camunda.ACT_GE_BYTEARRAY BA ON PD.DEPLOYMENT_ID_ = BA.DEPLOYMENT_ID_ AND PD.RESOURCE_NAME_ = BA.NAME_ WHERE PD.ID_ = :processdefid', 'false', 'false', 'false', 494, 22, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (180, 'true', '{"processinstanceid": null}', 'SELECT RES.ID_ AS "id", RES.PROC_INST_ID_ AS "processInstanceId", RES.TYPE_ AS "type", RES.ACT_INST_ID_ AS "activityInstanceId", RES.TASK_ID_ AS "taskId", RES.NAME_ AS "name", RES.TEXT_ AS "value", RES.TIME_ AS "time", RES.TENANT_ID_ AS "tenantId" FROM t22refined.camunda.ACT_HI_DETAIL RES LEFT JOIN t22refined.camunda.ACT_GE_BYTEARRAY BA ON RES.BYTEARRAY_ID_ = BA.ID_ WHERE RES.PROC_INST_ID_ = :processinstanceid AND ( ( RES.TYPE_ = ''VariableUpdate'' AND RES.NAME_ IN ( ''userActivity'', ''checker_action_whitelist_obj'', ''strHistoryUpdate'', ''AlertIDs'', ''parentProcess'' ) ) OR ( RES.TYPE_ = ''FormProperty'' AND ( RES.NAME_ IN ( ''Remarks'', ''DocumentReviewRemarks'', ''Action1'', ''Action2'', ''Action'', ''Block'' ) OR RES.NAME_ LIKE ''Action%'' ) ) )', 'false', 'false', 'false', 494, 22, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (181, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", TASK_ID_ AS "taskId", TIME_ AS "time", MESSAGE_ AS "message" FROM t22refined.camunda.ACT_HI_COMMENT WHERE TASK_ID_ in (:taskids) AND TYPE_ = ''comment''', 'false', 'false', 'false', 494, 22, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (182, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", NAME_ AS "name", TASK_ID_ AS "taskId", CREATE_TIME_ AS "createTime", DESCRIPTION_ AS "description" FROM t22refined.camunda.ACT_HI_ATTACHMENT WHERE TASK_ID_ IN (:taskids)', 'false', 'false', 'false', 494, 22, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (183, 'true', '{"taskids": null}', 'SELECT ACT_INST_ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", NAME_ AS "activityName", ASSIGNEE_ AS "assignee", ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TASK_DEF_KEY_ AS "activityId", TENANT_ID_ AS "tenantId", CASE WHEN DELETE_REASON_ IS NOT NULL AND LOWER(DELETE_REASON_) LIKE ''%cancel%'' THEN TRUE ELSE FALSE END AS "canceled" FROM t22refined.camunda.ACT_HI_TASKINST WHERE ID_ IN (:taskids)', 'false', 'false', 'false', 494, 22, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (184, 'true', '{"processinstanceid": null}', 'SELECT PROC_DEF_ID_ AS "processDefinitionId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN STATE_ = ''CANCELED'' THEN TRUE ELSE FALSE END AS "canceled" FROM t22refined.camunda.ACT_HI_PROCINST WHERE ID_ = :processinstanceid', 'false', 'false', 'false', 494, 22, 3);

--PAYOUTS (23)

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (178, 'true', '{"processinstanceid": null}', 'SELECT ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", ACT_TYPE_ AS "activityType", ACT_NAME_ AS "activityName", ASSIGNEE_ AS "assignee", TASK_ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN ACT_INST_STATE_ = 2 THEN TRUE ELSE FALSE END AS "canceled" FROM t23refined.camunda.ACT_HI_ACTINST WHERE PROC_INST_ID_ = :processinstanceid AND ACT_TYPE_ IN ( ''userTask'', ''noneEndEvent'', ''startEvent'', ''sendTask'', ''receiveTask'' ) ORDER BY START_TIME_ DESC', 'false', 'false', 'false', 494, 23, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (179, 'true', '{"processdefid": null}', 'SELECT PD.ID_ AS "id", FROM_UTF8(BA.BYTES_) AS "bpmn20Xml" FROM postgresql.camunda.ACT_RE_PROCDEF PD JOIN postgresql.camunda.ACT_GE_BYTEARRAY BA ON PD.DEPLOYMENT_ID_ = BA.DEPLOYMENT_ID_ AND PD.RESOURCE_NAME_ = BA.NAME_ WHERE PD.ID_ = :processdefid', 'false', 'false', 'false', 494, 23, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (180, 'true', '{"processinstanceid": null}', 'SELECT RES.ID_ AS "id", RES.PROC_INST_ID_ AS "processInstanceId", RES.TYPE_ AS "type", RES.ACT_INST_ID_ AS "activityInstanceId", RES.TASK_ID_ AS "taskId", RES.NAME_ AS "name", RES.TEXT_ AS "value", RES.TIME_ AS "time", RES.TENANT_ID_ AS "tenantId" FROM t23refined.camunda.ACT_HI_DETAIL RES LEFT JOIN t23refined.camunda.ACT_GE_BYTEARRAY BA ON RES.BYTEARRAY_ID_ = BA.ID_ WHERE RES.PROC_INST_ID_ = :processinstanceid AND ( ( RES.TYPE_ = ''VariableUpdate'' AND RES.NAME_ IN ( ''userActivity'', ''checker_action_whitelist_obj'', ''strHistoryUpdate'', ''AlertIDs'', ''parentProcess'' ) ) OR ( RES.TYPE_ = ''FormProperty'' AND ( RES.NAME_ IN ( ''Remarks'', ''DocumentReviewRemarks'', ''Action1'', ''Action2'', ''Action'', ''Block'' ) OR RES.NAME_ LIKE ''Action%'' ) ) )', 'false', 'false', 'false', 494, 23, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (181, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", TASK_ID_ AS "taskId", TIME_ AS "time", MESSAGE_ AS "message" FROM t23refined.camunda.ACT_HI_COMMENT WHERE TASK_ID_ in (:taskids) AND TYPE_ = ''comment''', 'false', 'false', 'false', 494, 23, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (182, 'true', '{"taskids": null}', 'SELECT ID_ AS "id", NAME_ AS "name", TASK_ID_ AS "taskId", CREATE_TIME_ AS "createTime", DESCRIPTION_ AS "description" FROM t23refined.camunda.ACT_HI_ATTACHMENT WHERE TASK_ID_ IN (:taskids)', 'false', 'false', 'false', 494, 23, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (183, 'true', '{"taskids": null}', 'SELECT ACT_INST_ID_ AS "id", PROC_INST_ID_ AS "processInstanceId", NAME_ AS "activityName", ASSIGNEE_ AS "assignee", ID_ AS "taskId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TASK_DEF_KEY_ AS "activityId", TENANT_ID_ AS "tenantId", CASE WHEN DELETE_REASON_ IS NOT NULL AND LOWER(DELETE_REASON_) LIKE ''%cancel%'' THEN TRUE ELSE FALSE END AS "canceled" FROM t23refined.camunda.ACT_HI_TASKINST WHERE ID_ IN (:taskids)', 'false', 'false', 'false', 494, 23, 3);

INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (184, 'true', '{"processinstanceid": null}', 'SELECT PROC_DEF_ID_ AS "processDefinitionId", START_TIME_ AS "startTime", END_TIME_ AS "endTime", TENANT_ID_ AS "tenantId", CASE WHEN STATE_ = ''CANCELED'' THEN TRUE ELSE FALSE END AS "canceled" FROM t23refined.camunda.ACT_HI_PROCINST WHERE ID_ = :processinstanceid', 'false', 'false', 'false', 494, 23, 3);

--dashboardqueryparamaters

--PAYTM(17)

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 178, NULL, 17, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processdefid', 'String', 179, NULL, 17, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 180, NULL, 17, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 181, NULL, 17, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 182, NULL, 17, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 183, NULL, 17, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 184, NULL, 17, NULL);

--BAPA (8)

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 178, NULL, 8, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processdefid', 'String', 179, NULL, 8, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 180, NULL, 8, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 181, NULL, 8, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 182, NULL, 8, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 183, NULL, 8, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 184, NULL, 8, NULL);

--PMTAGG (21)

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 178, NULL, 21, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processdefid', 'String', 179, NULL, 21, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 180, NULL, 21, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 181, NULL, 21, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 182, NULL, 21, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 183, NULL, 21, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 184, NULL, 21, NULL);

--GIFTCARD (22)

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 178, NULL, 22, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processdefid', 'String', 179, NULL, 22, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 180, NULL, 22, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 181, NULL, 22, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 182, NULL, 22, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 183, NULL, 22, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 184, NULL, 22, NULL);

--PAYOUTS (23)

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 178, NULL, 23, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processdefid', 'String', 179, NULL, 23, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 180, NULL, 23, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 181, NULL, 23, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 182, NULL, 23, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'taskids', 'List<String>', 183, NULL, 23, NULL);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder, itenantid, validation) VALUES ((SELECT MAX(idashboardparameterid) + 1 FROM ui.dashboardqueryparameters), 'processinstanceid', 'String', 184, NULL, 23, NULL);