INSERT INTO ui.rolemenuaccessmap (
    irolemenumapid,
    badd,
    bapprove,
    bdelete,
    bedit,
    bpublish,
    bview,
    dtapproverstamp,
    dtentrystamp,
    istatus,
    iapproveruserid,
    ientryuserid,
    imenuid,
    iroleid,
    itenantid,
    iorgid
)
SELECT 
    COALESCE((SELECT MAX(irolemenumapid) FROM ui.rolemenuaccessmap), 0) + ROW_NUMBER() OVER () AS irolemenumapid,
    TRUE AS badd,
    TRUE AS bapprove,
    TRUE AS bdelete,
    TRUE AS bedit,
    TRUE AS bpublish,
    TRUE AS bview,
    NULL AS dtapproverstamp,
    null AS dtentrystamp,
    TRUE AS istatus,
    NULL AS iapproveruserid,
    null AS ientryuserid, 
    601 AS imenuid,
    r.iroleid,
    t.itenantid, 
    t.iorgid as iorgid
FROM 
    ui.roledesc r
	join ui.tenants t on r.itenantid=t.itenantid
WHERE 
    r.iroleid IN (2,4,5,1,7) and t.itenantid=12;



INSERT INTO ui.rolemenuaccessmap (
    irolemenumapid,
    badd,
    bapprove,
    bdelete,
    bedit,
    bpublish,
    bview,
    dtapproverstamp,
    dtentrystamp,
    istatus,
    iapproveruserid,
    ientryuserid,
    imenuid,
    iroleid,
    itenantid,
    iorgid
)
SELECT 
    COALESCE((SELECT MAX(irolemenumapid) FROM ui.rolemenuaccessmap), 0) + ROW_NUMBER() OVER () AS irolemenumapid,
    TRUE AS badd,
    TRUE AS bapprove,
    TRUE AS bdelete,
    TRUE AS bedit,
    TRUE AS bpublish,
    TRUE AS bview,
    NULL AS dtapproverstamp,
    null AS dtentrystamp,
    TRUE AS istatus,
    NULL AS iapproveruserid,
    null AS ientryuserid, 
    603 AS imenuid,
    r.iroleid,
    t.itenantid, 
    t.iorgid as iorgid
FROM 
    ui.roledesc r
	join ui.tenants t on r.itenantid=t.itenantid
WHERE 
    r.iroleid IN (2,4,5,1,7) and t.itenantid=12;

INSERT INTO ui.dashboard (
idashboardid, bactive, bdelete, vcdashboardname, iorder, irowcount, imenustructuredesc, itenantid, bdynamic) VALUES (
'80'::integer, true::boolean, true::boolean, 'Party Dashboard - DL'::character varying, '1'::integer, '1'::integer, '601'::integer, '12'::integer, null)
 returning idashboardid,itenantid;


 INSERT INTO ui.dashboardquery (
idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, itenantid, dbtype) VALUES (
'172'::integer, true::boolean, '{
   "Request":null,
   "party":null,
   "userType":null,
   "txnClass":null,
   "useraddress":null,
   "date":null
}'::text,  E'
{
    "Initial":{"All":{"All":{"All":"SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", dttrxntime AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", CAST(json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS INTEGER) AS \\"Skip Processing\\" from t12refined.analytics.trans where vcclassname in ( :allClasses ) and itenantid = :tenantid order by tdate desc limit 1"}}},
    "Search":{
    "All": {
        "VPA": {
            "Payer": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeraddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Payee": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeeaddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Both":  "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeeaddr = :useraddress or vcpayeraddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data"
        },
        "Account": {
            "Payer": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeraccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Payee": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeeaccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Both":  "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data"
        }
    },
    "Other": {
        "VPA": {
            "Payer": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeraddr = :useraddress  ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Payee": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeeaddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Both":  "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data"
        },
        "Account": {
            "Payer": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeraccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Payee": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeeaccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Both":  "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data"
        }
    }
    }
} 
'::text, false::boolean, true::boolean, false::boolean, '601'::integer, '12'::integer, '3'::integer)
 returning idashboardqueryid,itenantid;


 INSERT INTO ui.dashboardresultset (
idashboardresultsetid, vcdashboardresultsetlayout, vcdashboardresultsetname, idashboardqueryid, idashboardid, vcdashboardresultsetschema, imenustructuredesc, itenantid, iorgid) VALUES (
(SELECT max(idashboardresultsetid)+1 FROM ui.dashboardresultset),  E'{"sizes":[1],"detail":{"main":{"type":"split-area","orientation":"horizontal","children":[{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_0"],"currentIndex":0},{"type":"split-area","orientation":"vertical","children":[{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_2"],"currentIndex":0},{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_1"],"currentIndex":0}],"sizes":[0.5,0.5]}],"sizes":[0.5506683328599352,0.44933166714006484]}},"mode":"globalFilters","viewers":{"PERSPECTIVE_GENERATED_ID_0":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Pro Dark","title":"Transactions","group_by":[],"split_by":[],"columns":["ILiveMessageID","UniqueID","Class","Type","Time","Amount","Score","FRMPass","PayerVPA","PayeeVPA","PayerName","PayeeName","Payer Account","Payee Account","decisiondetails"],"filter":[],"sort":[["Time","desc"]],
"expressions":{"Type": "if (is_not_null(\\"Payer Account\\") and   is_not_null(\\"Payee Account\\")) {        ''A2A''    } else if (is_not_null(\\"Payer Account\\")) {        ''A2P''    } else if (is_not_null(\\"Payee Account\\")) {        ''P2A''    }else    {        ''-''    }\\n"},"aggregates":{},"master":false,"table":"vpatransaction","linked":false,"selectable":"true"},"PERSPECTIVE_GENERATED_ID_2":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Pro Dark","title":"Summary","group_by":["Date"],"split_by":[],"columns":["Txn Count","Amount","Pass","Fail"],"filter":[],"sort":[],"expressions":["// Txn Count\\ninteger(1)","// Pass \\nif(\\"FRMPass\\" == true) {\\n    integer(1)\\n} else {\\n    integer(0)\\n}\\n","// Fail\\nif(\\"FRMPass\\" == false){\\ninteger(1)\\n} else {\\ninteger(0)}"],"aggregates":{"Fail":"abs sum","Txn Count":"count","Pass":"abs sum"},"master":false,"table":"vpatransaction","linked":false},"PERSPECTIVE_GENERATED_ID_1":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Pro Dark","title":"Decision Details","group_by":[],"split_by":[],"columns":["Rule Name","Score","Order","Remarks"],"filter":[],"sort":[],"expressions":[],"aggregates":{},"master":false,"table":"decisiondetailslive","linked":false}}} '::text, 'vpatransaction'::character varying, '172'::integer, '80'::integer, ' {
      "ILiveMessageID": "string",
      "UniqueID": "string",
      "Class": "string",
      "Time": "datetime",
      "PayerVPA": "string",
      "PayerName": "string",
      "PayeeVPA": "string",
      "PayeeName": "string",
      "Amount": "float",
      "FRMPass": "boolean",
      "Score": "integer",
      "FailedRule": "string",
      "Payer Account": "string",
      "Payee Account": "string",
      "decisiondetails": "string",
      "Date": "date",
	  "Txn Type":"string",
	  "Payee MCC":"integer",
      "Skip Processing":"integer"
 }'::text, 601, '12'::integer, '5'::integer)
 returning idashboardresultsetid,itenantid;

 WITH max_id AS (
    SELECT max(idashboardparameterid) AS current_max FROM ui.dashboardqueryparameters
)
INSERT INTO ui.dashboardqueryparameters (
    idashboardparameterid,
    vcparametername,
    vcparametertype,
    idashboardqueryid,
    iorder,
    itenantid
) VALUES 
    ((SELECT current_max+1 FROM max_id), 'userType', 'JsonPath', 172, 3, 12),
    ((SELECT current_max+2 FROM max_id), 'party', 'JsonPath', 172, 2, 12),
    ((SELECT current_max+3 FROM max_id), 'txnClass', 'JsonPath', 172, 1, 12),
    ((SELECT current_max+4 FROM max_id), 'Request', 'JsonPath', 172, 0, 12),
    ((SELECT current_max+5 FROM max_id), 'date', 'Date', 172, NULL, 12),
    ((SELECT current_max+6 FROM max_id), 'useraddress', 'String', 172, NULL, 12);

UPDATE ui.dashboardquery SET
vcdashboardquery =  E' {
    "Initial":{"All":{"All":{"All":"SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", dttrxntime AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", CAST(json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS INTEGER) AS \\"Skip Processing\\" from t12refined.analytics.trans where vcclassname in ( :allClasses ) and itenantid = :tenantid order by tdate desc limit 1"}}},
    "Search":{
    "All": {
        "VPA": {
            "Payer": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeraddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Payee": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeeaddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Both":  "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeeaddr = :useraddress or vcpayeraddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data"
        },
        "Account": {
            "Payer": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeraccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Payee": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeeaccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Both":  "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname in (:allClasses) and (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data"
        }
    },
    "Other": {
        "VPA": {
            "Payer": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeraddr = :useraddress  ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Payee": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeeaddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Both":  "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data"
        },
        "Account": {
            "Payer": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeraccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Payee": "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeeaccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data",
            "Both":  "WITH _filtered_data AS ( SELECT dttrxntime, vcmsgid, vcuniquetransid, observations,vcpayeraddr,vcpayeeaddr ,ilivemessageid, result, vcclassname, dobservationamount , score,vcpayeraccountexternalid , vcpayeeaccountexternalid, ipayeemccid FROM t12refined.analytics.trans WHERE vcclassname  = (SELECT :txnClass WHERE :txnClass IN ( :allClasses )) and (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress ) and itenantid = :tenantid  and tdate between CAST(DATE(:date ) AS TIMESTAMP) - INTERVAL ''1'' DAY and CAST(DATE(:date ) AS TIMESTAMP) + INTERVAL ''1'' DAY - INTERVAL ''1'' SECOND order by tdate desc limit 50000 ) SELECT json_extract(result, ''$.score.decisiondetails'') AS \\"decisiondetails\\", ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", date (dttrxntime) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CASE WHEN json_extract_scalar(result, ''$.status'') = ''Failed'' THEN ''false'' WHEN json_extract_scalar(result, ''$.status'') = ''Success'' THEN ''true'' WHEN json_extract_scalar(result, ''$.status'') IS NULL THEN CASE WHEN score > 0 THEN ''false'' WHEN score = 0 THEN ''true'' ELSE NULL END END AS \\"FRMPass\\", vcpayeraccountexternalid AS \\"Payer Account\\", vcpayeraddr AS \\"PayerVPA\\", vcpayeeaccountexternalid AS \\"Payee Account\\", vcpayeeaddr AS \\"PayeeVPA\\", NULL AS \\"FailedRule\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"PayerName\\", json_extract_scalar( observations, ''$.observations.payeeVPA.vpaName'') AS \\"PayeeName\\", json_extract(observations, ''$.txn.type'') AS \\"Txn Type\\", ipayeemccid AS \\"Payee MCC\\", json_extract_scalar(observations, ''$.txn.attribs.skip_processing'') AS \\"Skip Processing\\" from _filtered_data"
        }
    }
    }
} 
'::text WHERE
idashboardqueryid = 172 AND itenantid = 12;


UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{
      "ILiveMessageID": "string",
      "UniqueID": "string",
      "UniqueID-DL": "string",
      "Class": "string",
      "Time": "datetime",
      "PayerVPA": "string",
      "PayerVPA-DL": "string",
      "PayerName": "string",
      "PayeeVPA": "string",
      "PayeeVPA-DL": "string",
      "PayeeName": "string",
      "Amount": "float",
      "FRMPass": "boolean",
      "Score": "integer",
      "FailedRule": "string",
      "Payer Account": "string",
      "Payee Account": "string",
      "Payer Account-DL": "string",
      "Payee Account-DL": "string",
      "decisiondetails": "string",
      "Date": "date",
	  "Txn Type":"string",
	  "Payee MCC":"integer",
      "Skip Processing":"string"
 }'::text WHERE
idashboardid = 80 AND itenantid = 12;