UPDATE ui.dashboardquery SET
vcdashboardquery =  E'{
    "All":
    {
        "VPA" : {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans WHERE vcpayeraddr = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans WHERE vcpayeeaddr = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000",
            "Both" :  "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" from t17refined.analytics.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress  ) and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000"
        },
        "Account": {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where vcpayeraccountexternalid = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where vcpayeeaccountexternalid = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress ) and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000"
       }
    },
    "Other":
    {
        "VPA" : {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where vcpayeraddr = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where vcpayeeaddr = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress ) and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000"
        },
        "Account": {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where vcpayeraccountexternalid = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where vcpayeeaccountexternalid = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t17refined.analytics.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress )  and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC limit 50000"
       }
    }
}
'::text, dbtype = '3'::integer WHERE
idashboardqueryid = 46 AND itenantid = 17;


UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{
       "ILiveMessageID":"string",
       "UniqueID":"string",
       "UniqueID-DL":"string",
       "Class":"string",
       "Time":"datetime",
       "PayerVPA":"string",
       "PayerVPA-DL":"string",
       "PayerName":"string",
       "PayeeVPA-DL":"string",
       "PayeeName":"string",
       "Amount":"float",
       "FRMPass":"string",
       "Score":"integer",
       "FailedRule":"string",
       "Payer Account":"string",
       "Payee Account":"string",
       "Payer Account-DL":"string",
       "Payee Account-DL":"string",
       "Rule Score":"integer",
       "Order":"integer",
       "Remarks":"string",
       "RuleName":"string",
       "Date":"date"
    }'::text WHERE
idashboardresultsetid = 22 AND itenantid = 17;

UPDATE ui.dashboardquery SET
vcdashboardquery =  E'{
    "All":
    {
        "VPA" : {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans WHERE vcpayeraddr = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans WHERE vcpayeeaddr = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" :  "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" from t22refined.analytics.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress  ) and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
        },
        "Account": {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where vcpayeraccountexternalid = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where vcpayeeaccountexternalid = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress ) and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
       }
    },
    "Other":
    {
        "VPA" : {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where vcpayeraddr = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where vcpayeeaddr = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress ) and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
        },
        "Account": {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where vcpayeraccountexternalid = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where vcpayeeaccountexternalid = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t22refined.analytics.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress )  and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
       }
    }
}
'::text, dbtype = '3'::integer WHERE
idashboardqueryid = 46 AND itenantid = 22;

UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{
       "ILiveMessageID":"string",
       "UniqueID":"string",
       "UniqueID-DL":"string",
       "Class":"string",
       "Time":"datetime",
       "PayerVPA":"string",
       "PayerVPA-DL":"string",
       "PayerName":"string",
       "PayeeVPA-DL":"string",
       "PayeeName":"string",
       "Amount":"float",
       "FRMPass":"string",
       "Score":"integer",
       "FailedRule":"string",
       "Payer Account":"string",
       "Payee Account":"string",
       "Payer Account-DL":"string",
       "Payee Account-DL":"string",
       "Rule Score":"integer",
       "Order":"integer",
       "Remarks":"string",
       "RuleName":"string",
       "Date":"date"
    }'::text WHERE
idashboardresultsetid = 22 AND itenantid = 22;


UPDATE ui.dashboardquery SET
vcdashboardquery =  E'{
    "All":
    {
        "VPA" : {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans WHERE vcpayeraddr = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans WHERE vcpayeeaddr = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" :  "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" from t21refined.analytics.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress  ) and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
        },
        "Account": {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where vcpayeraccountexternalid = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where vcpayeeaccountexternalid = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress ) and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
       }
    },
    "Other":
    {
        "VPA" : {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where vcpayeraddr = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where vcpayeeaddr = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress ) and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
        },
        "Account": {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where vcpayeraccountexternalid = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where vcpayeeaccountexternalid = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t21refined.analytics.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress )  and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
       }
    }
}
'::text, dbtype = '3'::integer WHERE
idashboardqueryid = 46 AND itenantid = 21;

UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{
       "ILiveMessageID":"string",
       "UniqueID":"string",
       "UniqueID-DL":"string",
       "Class":"string",
       "Time":"datetime",
       "PayerVPA":"string",
       "PayerVPA-DL":"string",
       "PayerName":"string",
       "PayeeVPA-DL":"string",
       "PayeeName":"string",
       "Amount":"float",
       "FRMPass":"string",
       "Score":"integer",
       "FailedRule":"string",
       "Payer Account":"string",
       "Payee Account":"string",
       "Payer Account-DL":"string",
       "Payee Account-DL":"string",
       "Rule Score":"integer",
       "Order":"integer",
       "Remarks":"string",
       "RuleName":"string",
       "Date":"date"
    }'::text WHERE
idashboardresultsetid = 22 AND itenantid = 21;


UPDATE ui.dashboardquery SET
vcdashboardquery =  E'{
    "All":
    {
        "VPA" : {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans WHERE vcpayeraddr = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans WHERE vcpayeeaddr = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" :  "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" from t8refined.analytics.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress  ) and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
        },
        "Account": {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where vcpayeraccountexternalid = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where vcpayeeaccountexternalid = :useraddress and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress ) and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
       }
    },
    "Other":
    {
        "VPA" : {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where vcpayeraddr = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where vcpayeeaddr = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = :useraddress ) and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
        },
        "Account": {
            "Payer" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where vcpayeraccountexternalid = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Payee" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where vcpayeeaccountexternalid = :useraddress and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC",
            "Both" : "SELECT ilivemessageid AS \\"ILiveMessageID\\", vcmsgid as \\"UniqueID\\", vcuniquetransid as \\"UniqueID-DL\\", vcclassname AS \\"Class\\", dttrxntime AS \\"Time\\", CAST(dttrxntime AS date) AS \\"Date\\", dobservationamount AS \\"Amount\\", score AS \\"Score\\", CAST( json_extract_scalar(result, ''$.score.bpass'') AS VARCHAR ) AS \\"FRMPass\\", vcpayeraccountexternalid as \\"Payer Account\\", vcpayeraddr as \\"PayerVPA\\", vcpayeeaccountexternalid as \\"Payee Account\\", vcpayeeaddr as \\"PayeeVPA\\", vcpayeraccountexternalid as \\"Payer Account-DL\\", vcpayeraddr as \\"PayerVPA-DL\\", vcpayeeaccountexternalid as \\"Payee Account-DL\\", vcpayeeaddr as \\"PayeeVPA-DL\\", NULL AS \\"FailedRule\\", CAST( json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS VARCHAR ) AS \\"PayerName\\", CAST( json_extract_scalar(observations, ''$.observations.payeeVPA.vpaName'') AS VARCHAR ) AS \\"PayeeName\\" FROM t8refined.analytics.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = :useraddress )  and vcclassname  = :txnClass and tdate BETWEEN :StartDate  AND :EndDate ORDER BY tdate DESC"
       }
    }
}
'::text, dbtype = '3'::integer WHERE
idashboardqueryid = 46 AND itenantid = 8;

UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{
       "ILiveMessageID":"string",
       "UniqueID":"string",
       "UniqueID-DL":"string",
       "Class":"string",
       "Time":"datetime",
       "PayerVPA":"string",
       "PayerVPA-DL":"string",
       "PayerName":"string",
       "PayeeVPA-DL":"string",
       "PayeeName":"string",
       "Amount":"float",
       "FRMPass":"string",
       "Score":"integer",
       "FailedRule":"string",
       "Payer Account":"string",
       "Payee Account":"string",
       "Payer Account-DL":"string",
       "Payee Account-DL":"string",
       "Rule Score":"integer",
       "Order":"integer",
       "Remarks":"string",
       "RuleName":"string",
       "Date":"date"
    }'::text WHERE
idashboardresultsetid = 22 AND itenantid = 8;