UPDATE ui.dashboardquery SET
vcdashboardquery =  E'
{
  "Multiple":{
    "Payer": "WITH _filtered_data AS ( SELECT vcmsgid, json_extract_scalar(observations, ''$.txn.id'') AS \\"transactionid\\", json_extract_scalar(observations, ''$.txn.attribs.txn_type'') AS \\"txn_type\\", json_extract_scalar(observations, ''$.txn.attribs.acquirer_name'') AS \\"acquirer_name\\", json_extract_scalar(observations, ''$.txn.class'') AS \\"class\\", json_extract_scalar(observations, ''$.txn.ts'') AS \\"transaction_timestamp\\", round(CAST(json_extract_scalar(observations, ''$.payee.amount'') AS INTEGER) / 100.0, 2) AS \\"transaction_amount\\", json_extract_scalar(observations, ''$.payee.addr'') AS \\"payee_vpa\\", json_extract_scalar(observations, ''$.payer.addr'') AS \\"payer_vpa\\", risk_override AS \\"statuscode\\", risk_context AS \\"statusinfo\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"payer_name\\", score FROM t14refined.analytics.trans WHERE itenantid = :tenantid AND vcpayeraddr = :address AND tdate BETWEEN CAST(:date AS DATE) AND date_add(''day'', 1, CAST(:date AS DATE)) AND risk_override != 1 AND vcuniquetransid != :vcuniquetransid ORDER BY tdate LIMIT :limit ) SELECT * FROM _filtered_data",
    "Payee": "WITH _filtered_data AS ( SELECT vcmsgid, json_extract_scalar(observations, ''$.txn.id'') AS \\"transactionid\\", json_extract_scalar(observations, ''$.txn.attribs.txn_type'') AS \\"txn_type\\", json_extract_scalar(observations, ''$.txn.attribs.acquirer_name'') AS \\"acquirer_name\\", json_extract_scalar(observations, ''$.txn.class'') AS \\"class\\", json_extract_scalar(observations, ''$.txn.ts'') AS \\"transaction_timestamp\\", round(CAST(json_extract_scalar(observations, ''$.payee.amount'') AS INTEGER) / 100.0, 2) AS \\"transaction_amount\\", json_extract_scalar(observations, ''$.payee.addr'') AS \\"payee_vpa\\", json_extract_scalar(observations, ''$.payer.addr'') AS \\"payer_vpa\\", risk_override AS \\"statuscode\\", risk_context AS \\"statusinfo\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"payer_name\\", score FROM t14refined.analytics.trans WHERE itenantid = :tenantid AND vcpayeeaddr = :address AND tdate BETWEEN CAST(:date AS DATE) AND date_add(''day'', 1, CAST(:date AS DATE)) AND risk_override != 1 AND vcuniquetransid != :vcuniquetransid ORDER BY tdate LIMIT :limit ) SELECT * FROM _filtered_data"
  },
  "Single":{
    "Payer": "WITH _filtered_data AS ( SELECT vcmsgid, json_extract_scalar(observations, ''$.txn.id'') AS \\"transactionid\\", json_extract_scalar(observations, ''$.txn.attribs.txn_type'') AS \\"txn_type\\", json_extract_scalar(observations, ''$.txn.attribs.acquirer_name'') AS \\"acquirer_name\\", json_extract_scalar(observations, ''$.txn.class'') AS \\"class\\", json_extract_scalar(observations, ''$.txn.ts'') AS \\"transaction_timestamp\\", round(CAST(json_extract_scalar(observations, ''$.payee.amount'') AS INTEGER) / 100.0, 2) AS \\"transaction_amount\\", json_extract_scalar(observations, ''$.payee.addr'') AS \\"payee_vpa\\", json_extract_scalar(observations, ''$.payer.addr'') AS \\"payer_vpa\\", risk_override AS \\"statuscode\\", risk_context AS \\"statusinfo\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"payer_name\\", score FROM t14refined.analytics.trans WHERE itenantid = :tenantid AND vcpayeraddr = :address AND tdate BETWEEN CAST(:date AS DATE) AND date_add(''day'', 1, CAST(:date AS DATE)) AND risk_override != 1 AND vcuniquetransid = :vcuniquetransid ORDER BY tdate LIMIT :limit ) SELECT * FROM _filtered_data",
    "Payee": "WITH _filtered_data AS ( SELECT vcmsgid, json_extract_scalar(observations, ''$.txn.id'') AS \\"transactionid\\", json_extract_scalar(observations, ''$.txn.attribs.txn_type'') AS \\"txn_type\\", json_extract_scalar(observations, ''$.txn.attribs.acquirer_name'') AS \\"acquirer_name\\", json_extract_scalar(observations, ''$.txn.class'') AS \\"class\\", json_extract_scalar(observations, ''$.txn.ts'') AS \\"transaction_timestamp\\", round(CAST(json_extract_scalar(observations, ''$.payee.amount'') AS INTEGER) / 100.0, 2) AS \\"transaction_amount\\", json_extract_scalar(observations, ''$.payee.addr'') AS \\"payee_vpa\\", json_extract_scalar(observations, ''$.payer.addr'') AS \\"payer_vpa\\", risk_override AS \\"statuscode\\", risk_context AS \\"statusinfo\\", json_extract_scalar(observations, ''$.observations.payerVPA.vpaName'') AS \\"payer_name\\", score FROM t14refined.analytics.trans WHERE itenantid = :tenantid AND vcpayeeaddr = :address AND tdate BETWEEN CAST(:date AS DATE) AND date_add(''day'', 1, CAST(:date AS DATE)) AND risk_override != 1 AND vcuniquetransid = :vcuniquetransid ORDER BY tdate LIMIT :limit ) SELECT * FROM _filtered_data"
  }
}
'::text , dbtype=3  WHERE
idashboardqueryid = 168 AND itenantid in (14);
