UPDATE ui.dashboardquery SET
vcdashboardquery =  E'{
  "Multiple":{ 
    "Payer": "SELECT vcmsgid, observations->''txn''->>''id'' as \\"transactionid\\", observations->''txn''->''attribs''->>''txn_type'' as \\"txn_type\\", observations->''txn''->''attribs''->>''acquirer_name'' as \\"acquirer_name\\", observations->''txn''->>''class'' as \\"class\\", observations->''txn''->>''ts'' as \\"transaction_timestamp\\", round(cast(observations->''payee''->>''amount'' as integer)/100, 2) as \\"transaction_amount\\", observations->''payee''->>''addr'' as \\"payee_vpa\\", observations->''payer''->>''addr'' as \\"payer_vpa\\", risk_override as \\"statuscode\\", risk_context as \\"statusinfo\\", observations->''observations''->''payerVPA''->>''vpaName'' as \\"payer_name\\", score FROM analytics.trans WHERE itenantid = :tenantid and vcpayeraddr = :address AND dttrxntime BETWEEN cast(cast(:date as date) as timestamp) AND cast((cast(:date as date) +1) as timestamp) AND risk_override != 1 and vcuniquetransid != :vcuniquetransid order by dttrxntime limit :limit",
    "Payee": "SELECT vcmsgid, observations->''txn''->>''id'' as \\"transactionid\\", observations->''txn''->''attribs''->>''txn_type'' as \\"txn_type\\", observations->''txn''->''attribs''->>''acquirer_name'' as \\"acquirer_name\\", observations->''txn''->>''class'' as \\"class\\", observations->''txn''->>''ts'' as \\"transaction_timestamp\\", round(cast(observations->''payee''->>''amount'' as integer)/100, 2) as \\"transaction_amount\\", observations->''payee''->>''addr'' as \\"payee_vpa\\", observations->''payer''->>''addr'' as \\"payer_vpa\\", risk_override as \\"statuscode\\", risk_context as \\"statusinfo\\", observations->''observations''->''payerVPA''->>''vpaName'' as \\"payer_name\\", score FROM analytics.trans WHERE itenantid = :tenantid and vcpayeeaddr = :address AND dttrxntime BETWEEN cast(cast(:date as date) as timestamp) AND cast((cast(:date as date) +1) as timestamp) AND risk_override != 1 and vcuniquetransid != :vcuniquetransid order by dttrxntime limit :limit"
  },
  "Single":{
    "Payer": "SELECT vcmsgid, observations->''txn''->>''id'' as \\"transactionid\\", observations->''txn''->''attribs''->>''txn_type'' as \\"txn_type\\", observations->''txn''->''attribs''->>''acquirer_name'' as \\"acquirer_name\\", observations->''txn''->>''class'' as \\"class\\", observations->''txn''->>''ts'' as \\"transaction_timestamp\\", round(cast(observations->''payee''->>''amount'' as integer)/100, 2) as \\"transaction_amount\\", observations->''payee''->>''addr'' as \\"payee_vpa\\", observations->''payer''->>''addr'' as \\"payer_vpa\\", risk_override as \\"statuscode\\", risk_context as \\"statusinfo\\", observations->''observations''->''payerVPA''->>''vpaName'' as \\"payer_name\\", score FROM analytics.trans WHERE itenantid = :tenantid and vcpayeraddr = :address AND dttrxntime BETWEEN cast(cast(:date as date) as timestamp) AND cast((cast(:date as date) +1) as timestamp) AND risk_override != 1 and vcuniquetransid = :vcuniquetransid",
    "Payee": "SELECT vcmsgid, observations->''txn''->>''id'' as \\"transactionid\\", observations->''txn''->''attribs''->>''txn_type'' as \\"txn_type\\", observations->''txn''->''attribs''->>''acquirer_name'' as \\"acquirer_name\\", observations->''txn''->>''class'' as \\"class\\", observations->''txn''->>''ts'' as \\"transaction_timestamp\\", round(cast(observations->''payee''->>''amount'' as integer)/100, 2) as \\"transaction_amount\\", observations->''payee''->>''addr'' as \\"payee_vpa\\", observations->''payer''->>''addr'' as \\"payer_vpa\\", risk_override as \\"statuscode\\", risk_context as \\"statusinfo\\", observations->''observations''->''payerVPA''->>''vpaName'' as \\"payer_name\\", score FROM analytics.trans WHERE itenantid = :tenantid and vcpayeeaddr = :address AND dttrxntime BETWEEN cast(cast(:date as date) as timestamp) AND cast((cast(:date as date) +1) as timestamp) AND risk_override != 1 and vcuniquetransid = :vcuniquetransid"
  }
}'::text, dbtype=1  WHERE
idashboardqueryid = 168 AND itenantid in (14);