UPDATE ui.dashboardquery SET
vcdashboardquery = '{
    "Customer":{
        "KC1":"select vcexternalcustid as \"UCIC\", vcexternalcustid as \"Customer ID\", vcattribs->>''panNo'' as \"PAN\", ''NA'' as \"Declaration (If PAN is not available)\", ''NA'' as \"CKYC Number\", ''NA'' as \"Declaration (If CKYC is not available)\", ''NA'' as \"Passport Number\", ''NA'' as \"Voter ID\", ''NA'' as \"Other Occupation\", ''NA'' as \"Drivers License Number\", ''NA'' as \"NREGA Card number of the individual\", ''NA'' as \"DIN / DPIN\", vccustomername as \"First Name\", ''NA'' as \"Middle Name\", ''NA'' as \"Last Name\", ''NA'' as \"Declaration (If Last name is not available)\", ''NA'' as \"Name of Father\", ''NA'' as \"Name of Mother\", vcattribs->>''partnerName'' as \"Spouse/Partner Name\", vcgender as \"Gender\", ''NA'' as \"Date of Birth\", ''NA'' as \"Nationality\", ''NA'' as \"Mobile Number\", ''NA'' as \"Alternate Mobile Number\", ''NA'' as \"Telephone Number\", ''NA'' as \"Email ID\", vcattribs->>''registeredAddress'' as \"Primary Address 1\", ''NA'' as \"Primary Address Country\", ''NA'' as \"Primary Address Pin Code\", ''NA'' as \"Primary Address Locality\", ''NA'' as \"Primary Address State\", ''NA'' as \"Primary Address District\", ''NA'' as \"Primary Address City\", ''NA'' as \"Secondary Address 1\", ''NA'' as \"Secondary Address Country\", ''NA'' as \"Secondary Address Pin Code\", ''NA'' as \"Secondary Address Locality\", ''NA'' as \"Secondary Address State\", ''NA'' as \"Secondary Address District\", ''NA'' as \"Secondary Address City\", ''NA'' as \"Identity verified using Aadhaar ID\", vcattribs->''merchant_type'' as \"Customer Type\", vcattribs->>''upperTurnoverSlab'' as \"Annual Income (INR)\", ''NA'' as \"Occupation\", ''NA'' as \"Employer Name\",  ''NA'' as \"Employer Address 1\", ''NA'' as \"Employer Address Country\", ''NA'' as \"Employer Address Pin Code\", ''NA'' as \"Employer Address Locality\", ''NA'' as \"Employer Address State\", ''NA'' as \"Employer Address District\", ''NA'' as \"Employer Address City\", vcattribs->>''dateOfRegistration'' as \"Date of Customer On-boarding\", ''NA'' as \"Date of Last KYC / re-KYC\", ''NA'' as \"Customer Risk Level\", ''NA'' as \"NPR\", ''NA'' as \"PEKRN\", ''NA'' as \"Primary State Name\", ''NA'' as \"Primary District Name\", ''NA'' as \"Primary City Name\", ''NA'' as \"Secondary State Name\", ''NA'' as \"Secondary District Name\", ''NA'' as \"Secondary City Name\", ''NA'' as \"Employee State Name\", ''NA'' as \"Employee District Name\", ''NA'' as \"Employee City Name\", ''NA'' as \"Other Customer Type\", :Group as \"Report Type\" from masters.customers where vcexternalcustid = :Address and itenantid = :tenantid",
        "KC2":"select vccustomername as \"Full Name\", ''NA'' as \"CIN/ FCRN/ LLPIN/ FLLPIN\", vcattribs->>''panNo'' as \"PAN\", ''NA'' as \"Declaration (If PAN is not available)\", vcattribs->>''gstNumber'' as \"GSTIN\", ''NA'' as \"Mobile Number\", vcattribs->>''registeredAddress'' as \"Registered Address\", ''NA'' as \"Country\", ''NA'' as \"PIN Code\", ''NA'' as \"Locality\", ''NA'' as \"State\", ''NA'' as \"District\", ''NA'' as \"City / Village / Town\", ''NA'' as \"PEKRN\", ''NA'' as \"State Name\", ''NA'' as \"District Name\", ''NA'' as \"City / Village / Town Name\", ''NA'' as \"City Name\", ''NA'' as \"Second Address Line 1\", ''NA'' as \"Second Address Country\", ''NA'' as \"Second Address PIN Code\", ''NA'' as \"Second Address Locality\", ''NA'' as \"Second Address State\", ''NA'' as \"Second Address State Name\", ''NA'' as \"Second Address District\", ''NA'' as \"Second Address District Name\", ''NA'' as \"Second Address City / Village / Town\", ''NA'' as \"Second Address City Name\", ''NA'' as \"Non-Indian PIN Code\", ''NA'' as \"Second Address Non-Indian PIN Code\", ''NA'' as \"Company ID Type\", vcattribs->>''panNo'' as \"Company ID Number\" from masters.customers where vcexternalcustid = :Address and itenantid = :tenantid",
        "Other":"select itenantid from ui.tenants where itenantid is null"
    },
    "Transaction":{
        "TS3":"select ''NA'' as \"Relationship Flag\", vcuniquetransid as \"Transaction ID\", observations->''txn''->>''type'' as \"Transaction Type\", cast(dttrxntime as date) as \"Transaction Date\", cast(dttrxntime as time) as \"Transaction Time\", dobservationamount as \"Transaction Amount\", observations->''observations''->''payerVPA''->>''vpaName'' as \"Sender Name\", vcpayeraddr as \"Sender VPA\", ''NA'' as \"Declaration (If Sender VPA is not available)\", ''NA'' as \"Sender Mobile Number\", observations->''observations''->''payerVPA''->''account''->>''ifsc'' as \"Sender IFSC\", observations->''observations''->''payerVPA''->''account''->>''accountNumber'' as \"Sender Account Number\", observations->''payee''->''attribs''->>''name'' as \"Beneficiary Name\", vcpayeeaddr as \"Beneficiary VPA\", ''NA'' as \"Beneficiary Mobile Number\", observations->''txn''->''attribs''->>''beneAccNo'' as \"Beneficiary Account Number\", :Group as \"Report Type\", observations->''txn''->''attribs''->>''beneifsc'' as \"Beneficiary IFSC\", ''NA'' as \"Beneficiary Account Branch Code\", ''NA'' as \"Narration\", ipayeemccid as \"Merchant Category Code\", ''NA'' as \"Beneficiary Account Type\" from analytics.trans where dttrxntime between :StartDate and :EndDate and itenantid = :tenantid",
        "Other":"select itenantid from ui.tenants where itenantid is null"
    },
    "Account":{
        "Account Detail" :"select :Group as \"Report Type\", ac.iaccounttypeid as \"Account Type\", ac.vcaccount as \"Account Number\", ''NA'' as \"Branch Code of Account\", ac.dtonboardingdate as \"Date of Account Opening\", ''NA'' as \"Date of Account Closing\", ''NA'' as \"Account Status\", ''NA'' as \"Reason for Account Freeze\", prof.val->''totalCount''->''p12m''->>''payer'' as \"No Of Debits (In last 12 months)\", prof.val->''totalValue''->''p12m''->>''payer'' as \"Total Debit Amount (In last 12 months)\", ''NA'' as \"No Of Credits (In last 12 months)\", ''NA'' as \"Total Credit Amount (In last 12 months)\", ''NA'' as \"No Of Cash Transaction (In last 12 months)\", ''NA'' as \"Total Cash Deposit (In last 12 months)\", ''NA'' as \"Total Cash Withdrawal (In last 12 months) Amount\" from profiles.account_monthly as prof join masters.accounts ac on prof.iaccountid=ac.iaccountid where ac.vcexternalaccountid = :Address order by prof.tdate desc limit 1",
        "Account Person Detail" : "select :Group as \"Report Type\", vcaccount as \"Account Number\", ''NA'' as \"Relationship Type\", vcexternalaccountid as \"Unique Reference Number\", ''NA'' as \"Individual / Non-individual\", ''NA'' as \"Name of Non-customer\" from masters.accounts where itenantid = :tenantid and vcexternalaccountid = :Address",
        "Other":"select itenantid from ui.tenants where itenantid is null"
    },
    "Other": {
        "Other":"select itenantid from ui.tenants where itenantid is null"
    }
}
'::text WHERE
idashboardqueryid = 118 AND itenantid = 17;
