INSERT INTO ui.dashboardquery (
idashboardqueryid, bparametersrequired, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc) VALUES (
'76'::integer, false::boolean, 'select ilivemessageid as "ILiveMessageID", vcmsgid as "UniqueID", vcclassname as "Class", dttrxntime at time zone ''Asia/Kolkata'' as "Time",
dobservationamount as "Amount", score as "Score",  cast(result->''score''->>''bpass'' as text)as "FRMPass", vcpayeraccountexternalid as "Payer Account", vcpayeraddr as "PayerVPA",
vcpayeeaccountexternalid as "Payee Account", vcpayeeaddr as "PayeeVPA", null as "FailedRule", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as "PayerName",
cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as "PayeeName" from transactions.trans ORDER BY dttrxntime desc LIMIT 1;'::text, false::boolean, true::boolean, false::boolean, '509'::integer)
 returning idashboardqueryid;

INSERT INTO ui.dashboardquery (
idashboardqueryid, bparametersrequired, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired, imenustructuredesc, vcfilterparametersjson) VALUES (
'77'::integer, true::boolean, '{
    "All": {
        "Account": {
            "Payer": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeraccountexternalid = :vpaAddress AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeraccountexternalid = :vpaAddress AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );",
            "Payee": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeeaccountexternalid = :vpaAddress AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeeaccountexternalid = :vpaAddress AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );",
            "Both": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE (vcpayeraccountexternalid = :vpaAddress or vcpayeeaccountexternalid = :vpaAddress) AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE (vcpayeraccountexternalid = :vpaAddress or vcpayeeaccountexternalid = :vpaAddress) AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );"
        },
        "VPA": {
            "Payer": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeraddr = :vpaAddress AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeraddr = :vpaAddress AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );",
            "Payee": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeeaddr = :vpaAddress AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeeaddr = :vpaAddress AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );",
            "Both": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE (vcpayeraddr = :vpaAddress or vcpayeeaddr = :vpaAddress) AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE (vcpayeraddr = :vpaAddress or vcpayeeaddr = :vpaAddress) AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );"
        }
    },
    "Other": {
        "Account": {
            "Payer": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeraccountexternalid = :vpaAddress and vcclassname = :txnClass AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeraccountexternalid = :vpaAddress and vcclassname = :txnClass AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );",
            "Payee": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeeaccountexternalid = :vpaAddress and vcclassname = :txnClass AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeeaccountexternalid = :vpaAddress and vcclassname = :txnClass AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );",
            "Both": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE (vcpayeraccountexternalid = :vpaAddress or vcpayeeaccountexternalid = :vpaAddress) and vcclassname = :txnClass AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE (vcpayeraccountexternalid = :vpaAddress or vcpayeeaccountexternalid = :vpaAddress) and vcclassname = :txnClass AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );"
        },
        "VPA": {
            "Payer": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeraddr = :vpaAddress and vcclassname = :txnClass AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeraddr = :vpaAddress and vcclassname = :txnClass AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );",
            "Payee": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeeaddr = :vpaAddress and vcclassname = :txnClass AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcpayeeaddr = :vpaAddress and vcclassname = :txnClass AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );",
            "Both": "WITH first_query_result AS ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE vcmsgid = :msgid ) SELECT * FROM first_query_result UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE (vcpayeraddr = :vpaAddress or vcpayeeaddr = :vpaAddress) and vcclassname = :txnClass AND ilivemessageid > (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid ASC LIMIT 20 ) UNION ALL ( SELECT result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' as \"Time\", dobservationamount as \"Amount\", score as \"Score\", cast(result->''score''->>''bpass'' as text) as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\", cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" FROM transactions.trans WHERE (vcpayeraddr = :vpaAddress or vcpayeeaddr = :vpaAddress) and vcclassname = :txnClass AND ilivemessageid < (SELECT \"ILiveMessageID\" FROM first_query_result) ORDER BY ilivemessageid DESC LIMIT 20 );"
        }
    }
}'::text, false::boolean, true::boolean, false::boolean, '509'::integer, '{ "party": null, "vpaType": null, "msgid": null, "vpaAddress": null, "txnClass": null }'::text)
 returning idashboardqueryid;



 INSERT INTO ui.dashboardqueryparameters (
 idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid) VALUES (
 '124'::integer, 'vpaAddress'::character varying, 'String'::character varying, '77'::integer)
  returning idashboardparameterid;


  INSERT INTO ui.dashboardqueryparameters (
  idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (
  '123'::integer, 'vpaType'::character varying, 'JsonPath'::character varying, '77'::integer, '2'::integer)
   returning idashboardparameterid;

   INSERT INTO ui.dashboardqueryparameters (
   idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (
   '122'::integer, 'party'::character varying, 'JsonPath'::character varying, '77'::integer, '1'::integer)
    returning idashboardparameterid;

    INSERT INTO ui.dashboardqueryparameters (
    idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (
    '121'::integer, 'txnClass'::character varying, 'JsonPath'::character varying, '77'::integer, '0'::integer)
     returning idashboardparameterid;

     INSERT INTO ui.dashboardqueryparameters (
     idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid) VALUES (
     '120'::integer, 'msgid'::character varying, 'String'::character varying, '77'::integer)
      returning idashboardparameterid;


 UPDATE ui.dashboardquery SET
 vcdashboardquery = 'SELECT (NOW()) as "enddate", (NOW() - interval ''2 day'') as "startdate";'::text WHERE
 idashboardqueryid = 72;


DROP TABLE IF EXISTS ui.rulesaudit;

ALTER TABLE IF EXISTS ui.rulestempaudit
    RENAME TO rulesaudit;