-- Autogenerated: do not edit this file
CREATE SCHEMA IF NOT EXISTS batch;

CREATE TABLE IF NOT EXISTS batch.BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT ,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE IF NOT EXISTS batch.BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT  ,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references batch.BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE IF NOT EXISTS batch.BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	PARAMETER_NAME VARCHAR(100) NOT NULL ,
	PARAMETER_TYPE VARCHAR(100) NOT NULL ,
	PARAMETER_VALUE VARCHAR(2500) ,
	IDENTIFYING CHAR(1) NOT NULL ,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references batch.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS batch.BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	COMMIT_COUNT BIGINT ,
	READ_COUNT BIGINT ,
	FILTER_COUNT BIGINT ,
	WRITE_COUNT BIGINT ,
	READ_SKIP_COUNT BIGINT ,
	WRITE_SKIP_COUNT BIGINT ,
	PROCESS_SKIP_COUNT BIGINT ,
	ROLLBACK_COUNT BIGINT ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references batch.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS batch.BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT ,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references batch.BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS batch.BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT ,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references batch.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE IF NOT EXISTS batch.BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS batch.BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS batch.BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;

CREATE TABLE IF NOT EXISTS batch.apiserver_keys
(
    iserverid integer NOT NULL,
    baseurl character varying(255) COLLATE pg_catalog."default" NOT NULL,
    keyname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    keyvalue character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT apiserver_keys_pkey PRIMARY KEY (iserverid)
);

CREATE TABLE IF NOT EXISTS batch.feature_config
(
    ifeatureid integer NOT NULL,
    featuredirectory character varying(255) COLLATE pg_catalog."default" NOT NULL,
    featurename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fieldsschema jsonb,
    maxrecords integer NOT NULL,
    maxrowsize integer,
    numthreads integer,
    paramschema jsonb,
    templatepath character varying(255) COLLATE pg_catalog."default" NOT NULL,
    validationsuccesscode integer NOT NULL,
    validationurl character varying(255) COLLATE pg_catalog."default" NOT NULL,
    imenuid integer,
    iserverid integer,
    requestschema jsonb,
    multirequestschema jsonb,
    responseschema jsonb,
    CONSTRAINT feature_config_pkey PRIMARY KEY (ifeatureid),
    CONSTRAINT fkco8u535sehlq908vkjq3t0yc7 FOREIGN KEY (iserverid)
        REFERENCES batch.apiserver_keys (iserverid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkslvetfdf7aqd76vrt521iwtd0 FOREIGN KEY (imenuid)
        REFERENCES ui.menustructuredesc (imenuid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS batch.file_processing_info
(
    uploadfileid integer NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
    completiontimestamp timestamp without time zone,
    errorlog character varying(255) COLLATE pg_catalog."default",
    error_msg character varying(255) COLLATE pg_catalog."default",
    failedrecords integer,
    filename character varying(255) COLLATE pg_catalog."default",
    param_values jsonb,
    passedrecords integer,
    status character varying(255) COLLATE pg_catalog."default",
    totalrecords integer,
    uploadfile character varying(255) COLLATE pg_catalog."default",
    uploadtimestamp timestamp without time zone,
    ifeatureid integer,
    CONSTRAINT file_processing_info_pkey PRIMARY KEY (uploadfileid),
    CONSTRAINT fkgdt12njyt37vurxuibcsbk806 FOREIGN KEY (ifeatureid)
        REFERENCES batch.feature_config (ifeatureid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS batch.batch_job_types
(
    jobtypeid integer NOT NULL,
    jobtype character varying(255) COLLATE pg_catalog."default" NOT NULL,
    maxrecords integer NOT NULL,
    maxrowsize integer,
    numthreads integer,
    processing_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    iserverid integer,
    CONSTRAINT batch_job_types_pkey PRIMARY KEY (jobtypeid),
    CONSTRAINT fk9otepeuhuxbae5wwaoav3ihol FOREIGN KEY (iserverid)
        REFERENCES batch.apiserver_keys (iserverid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS batch.batch_job
(
    jobid integer NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
    createdtimestamp timestamp(6) without time zone,
    endtimestamp timestamp(6) without time zone,
    failedrecords integer,
    jobparams jsonb,
    jobstatus character varying(255) COLLATE pg_catalog."default" NOT NULL,
    passedrecords integer,
    startedtimestamp timestamp(6) without time zone,
    totalrecords integer,
    jobtypeid integer,
    itenantid integer,
    CONSTRAINT batch_job_pkey PRIMARY KEY (jobid),
    CONSTRAINT fkdp0etasxykgtniut1heated3b FOREIGN KEY (jobtypeid)
        REFERENCES batch.batch_job_types (jobtypeid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);



CREATE TABLE IF NOT EXISTS batch.batch_job_data
(
    jobdataid integer NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
    jobdata jsonb,
    processresponse jsonb,
    status character varying(255) COLLATE pg_catalog."default",
    jobid integer,
    CONSTRAINT batch_job_data_pkey PRIMARY KEY (jobdataid),
    CONSTRAINT fkd0utrr46oto3j62fpfpcctf8f FOREIGN KEY (jobid)
        REFERENCES batch.batch_job (jobid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


INSERT INTO batch.apiserver_keys(iserverid, baseurl, keyname, keyvalue)	VALUES (3, 'http://localhost:8085', 'X-API-Key', 'f877a5b1-b6d6-4733-9d2e-0509538e536e');

INSERT INTO batch.batch_job_types (jobtypeid, jobtype, maxrecords, maxrowsize, numthreads,   iserverid, processing_url) VALUES (1, 'Process Bulk', 1, 500, 8, 3, '/api/v1/case-management/process-bulk-tickets/submit-bulk/external');
INSERT INTO batch.batch_job_types (jobtypeid, jobtype, maxrecords, maxrowsize, numthreads,  iserverid, processing_url) VALUES (2, 'Reassignment', 1, 500, 8,  3, '/api/v1/case-management/process-bulk-tickets/reassign-task/external');