UPDATE ui.dashboardquery
	SET  vcdashboardquery='{
    "Account": {
        "Payer": "with recursive livetrn as ( select * from transactions.trans l where  l.vcpayeraccountexternalid = :VpaAddress  and  dttrxntime between :StartDate  and :EndDate ) ,  flat (ilivemessageid, key, value) as ( select ilivemessageid, ''trans'',cast(format(''{\"ilivemessageid\":%s}'',cast(ilivemessageid as text)) as jsonb) as value from livetrn union select ilivemessageid ,  key, value from livetrn, jsonb_each(observations) union select ilivemessageid,''score.decisiondetails'' as key , to_jsonb(''''''{'' ||((result->''score'')->>''decisiondetails'') ||''}'''''')-- to_json((''''''''||((result->''score''::text)->''decisiondetails''::text)||'''''''')::text) \n as value from livetrn union select ilivemessageid,  key, value from livetrn, jsonb_each(result #- ''{score,observations}'' #- ''{score,decisiondetails}'') union select f.ilivemessageid, concat(f.key, ''.'', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) select cast(json_agg(data) as text) from ( select jsonb_object_agg(key, value) as data from flat where jsonb_typeof(value) <> ''object'' group by ilivemessageid ) a ;",
        "Payee": "with recursive livetrn as ( select * from transactions.trans l where l.vcpayeeaccountexternalid = :VpaAddress  and dttrxntime between :StartDate and  :EndDate ) ,  flat (ilivemessageid, key, value) as ( select ilivemessageid, ''trans'',cast(format(''{\"ilivemessageid\":%s}'',cast(ilivemessageid as text)) as jsonb) as value from livetrn union select ilivemessageid ,  key, value from livetrn, jsonb_each(observations) union select ilivemessageid,''score.decisiondetails'' as key , to_jsonb(''''''{'' ||((result->''score'')->>''decisiondetails'') ||''}'''''')-- to_json((''''''''||((result->''score''::text)->''decisiondetails''::text)||'''''''')::text) \n as value from livetrn union select ilivemessageid,  key, value from livetrn, jsonb_each(result #- ''{score,observations}'' #- ''{score,decisiondetails}'') union select f.ilivemessageid, concat(f.key, ''.'', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) select cast(json_agg(data) as text) from ( select jsonb_object_agg(key, value) as data from flat where jsonb_typeof(value) <> ''object'' group by ilivemessageid ) a ;",
        "Both": "with recursive livetrn as ( select * from transactions.trans l where (l.vcpayeraccountexternalid = :VpaAddress or l.vcpayeeaccountexternalid=:VpaAddress ) and  dttrxntime  between :StartDate  and  :EndDate  ) ,  flat (ilivemessageid, key, value) as ( select ilivemessageid, ''trans'',cast(format(''{\"ilivemessageid\":%s}'',cast(ilivemessageid as text)) as jsonb) as value from livetrn union select ilivemessageid ,  key, value from livetrn, jsonb_each(observations) union select ilivemessageid,''score.decisiondetails'' as key , to_jsonb(''''''{'' ||((result->''score'')->>''decisiondetails'') ||''}'''''')-- to_json((''''''''||((result->''score''::text)->''decisiondetails''::text)||'''''''')::text) \n as value from livetrn union select ilivemessageid,  key, value from livetrn, jsonb_each(result #- ''{score,observations}'' #- ''{score,decisiondetails}'') union select f.ilivemessageid, concat(f.key, ''.'', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) select cast(json_agg(data) as text) from ( select jsonb_object_agg(key, value) as data from flat where jsonb_typeof(value) <> ''object'' group by ilivemessageid ) a ;"
    },
    "VPA": {
        "Payer": "with recursive livetrn as ( select * from transactions.trans l where l.vcpayeraddr = :VpaAddress  and  dttrxntime  between :StartDate and :EndDate ) ,  flat (ilivemessageid, key, value) as ( select ilivemessageid, ''trans'',cast(format(''{\"ilivemessageid\":%s}'',cast(ilivemessageid as text)) as jsonb) as value from livetrn union select ilivemessageid ,  key, value from livetrn, jsonb_each(observations) union select ilivemessageid,''score.decisiondetails'' as key , to_jsonb(''''''{'' ||((result->''score'')->>''decisiondetails'') ||''}'''''')-- to_json((''''''''||((result->''score''::text)->''decisiondetails''::text)||'''''''')::text) \n as value from livetrn union select ilivemessageid,  key, value from livetrn, jsonb_each(result #- ''{score,observations}'' #- ''{score,decisiondetails}'') union select f.ilivemessageid, concat(f.key, ''.'', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) select cast(json_agg(data) as text) from ( select jsonb_object_agg(key, value) as data from flat where jsonb_typeof(value) <> ''object'' group by ilivemessageid ) a ;",
        "Payee": "with recursive livetrn as ( select * from transactions.trans l where l.vcpayeeaddr = :VpaAddress  and dttrxntime between :StartDate  and :EndDate ) ,  flat (ilivemessageid, key, value) as ( select ilivemessageid, ''trans'',cast(format(''{\"ilivemessageid\":%s}'',cast(ilivemessageid as text)) as jsonb) as value from livetrn union select ilivemessageid ,  key, value from livetrn, jsonb_each(observations) union select ilivemessageid,''score.decisiondetails'' as key , to_jsonb(''''''{'' ||((result->''score'')->>''decisiondetails'') ||''}'''''')-- to_json((''''''''||((result->''score''::text)->''decisiondetails''::text)||'''''''')::text) \n as value from livetrn union select ilivemessageid,  key, value from livetrn, jsonb_each(result #- ''{score,observations}'' #- ''{score,decisiondetails}'') union select f.ilivemessageid, concat(f.key, ''.'', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) select cast(json_agg(data) as text) from ( select jsonb_object_agg(key, value) as data from flat where jsonb_typeof(value) <> ''object'' group by ilivemessageid ) a ;",
        "Both": "with recursive livetrn as ( select * from transactions.trans l where (l.vcpayeeaddr = :VpaAddress or l.vcpayeraddr = :VpaAddress) and  dttrxntime between :StartDate  and :EndDate  ),  flat (ilivemessageid, key, value) as ( select ilivemessageid, ''trans'',cast(format(''{\"ilivemessageid\":%s}'',cast(ilivemessageid as text)) as jsonb) as value from livetrn union select ilivemessageid ,  key, value from livetrn, jsonb_each(observations) union select ilivemessageid,''score.decisiondetails'' as key , to_jsonb(''''''{'' ||((result->''score'')->>''decisiondetails'') ||''}'''''')-- to_json((''''''''||((result->''score''::text)->''decisiondetails''::text)||'''''''')::text) \n as value from livetrn union select ilivemessageid,  key, value from livetrn, jsonb_each(result #- ''{score,observations}'' #- ''{score,decisiondetails}'') union select f.ilivemessageid, concat(f.key, ''.'', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) select cast(json_agg(data) as text) from ( select jsonb_object_agg(key, value) as data from flat where jsonb_typeof(value) <> ''object'' group by ilivemessageid ) a ;"
    }
}'	WHERE idashboardqueryid=30;

