alter table if exists ui.perspectivequery add column formattingrequiered boolean;

alter table if exists ui.perspectivequery add column runonanalytics boolean;

alter table if exists ui.perspectivequeryparameters add column iorder int4;

UPDATE ui.menustructuredesc SET   vcaction='TransactionDBOld', vccontroller='TransactionDBOld', vcmenuname='Transaction DB Old', vcmini='TDO', vcpath='/analytics/transaction-dashboard-old' WHERE imenuid=507;

INSERT INTO ui.menustructuredesc(
	imenuid, bcollapse, dtapproverstamp, dtentrystamp, isortorder, vcaction, vccontroller, vchelptip, vcicon, vclayout, vcmenuname, vcmini, vcpath, vcrtlmini, vcrtlname, vcstate, ispproveruserid, ientryuserid, iparentmenu, istatus)
	VALUES (544, false, null, null, 6, 'TransactionDBNew', 'TransactionDBNew', null, null, '/user',
			'Transaction DB New', 'TDN', '/analytics/transaction-dashboard-new', null, null, null, null, null, 478, 1);

INSERT INTO ui.rolemenuaccessmap(
	irolemenumapid, badd, bapprove, bdelete, bedit, bpublish, bview, dtapproverstamp, dtentrystamp, istatus, iapproveruserid, ientryuserid, imenuid, iroleid)
	VALUES (657, true, true, true, true, true, true, null, null, true, null, null, 544, 1);


UPDATE ui.menustructuredesc SET   vcaction='PartyDashboardOld', vccontroller='PartyDashboardOld', vcmenuname='Party Dashboard Old', vcmini='PDO', vcpath='/analytics/party-dashboard-old' WHERE imenuid=508;

INSERT INTO ui.menustructuredesc(
	imenuid, bcollapse, dtapproverstamp, dtentrystamp, isortorder, vcaction, vccontroller, vchelptip, vcicon, vclayout, vcmenuname, vcmini, vcpath, vcrtlmini, vcrtlname, vcstate, ispproveruserid, ientryuserid, iparentmenu, istatus)
	VALUES (545, false, null, null, 7, 'PartyDashboardNew', 'PartyDashboardNew', null, null, '/user',
			'Party Dashboard New', 'PDN', '/analytics/party-dashboard-new', null, null, null, null, null, 478, 1);

INSERT INTO ui.rolemenuaccessmap(
	irolemenumapid, badd, bapprove, bdelete, bedit, bpublish, bview, dtapproverstamp, dtentrystamp, istatus, iapproveruserid, ientryuserid, imenuid, iroleid)
	VALUES (658, true, true, true, true, true, true, null, null, true, null, null, 545, 1);


INSERT INTO ui.perspectivequery (iperspectivequeryid, vcquery, vctablename, formattingrequiered, runonanalytics) VALUES (37, '{
    "All":
    {
        "VPA" : {
            "Payer" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where vcpayeraddr = :useraddress and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and  CURRENT_DATE) order by dttrxntime desc;",
            "Payee" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where vcpayeeaddr = :useraddress and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and  CURRENT_DATE) order by dttrxntime desc;",
            "Both" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = vcpayeraddr ) and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and CURRENT_DATE) order by dttrxntime desc;"
        },
        "Account": {
            "Payer" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where vcpayeraccountexternalid = :useraddress and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and CURRENT_DATE) order by dttrxntime desc;",
            "Payee" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where vcpayeeaccountexternalid = :useraddress and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and  CURRENT_DATE) order by dttrxntime desc;",
            "Both" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = vcpayeraccountexternalid ) and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and CURRENT_DATE) order by dttrxntime desc;"
       }
    },
    "Other":
    {
        "VPA" : {
            "Payer" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where vcpayeraddr = :useraddress and vcclassname  = :txnClass and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and  CURRENT_DATE) order by dttrxntime desc;",
            "Payee" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where vcpayeeaddr = :useraddress and vcclassname  = :txnClass and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and  CURRENT_DATE) order by dttrxntime desc;",
            "Both" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where (vcpayeraddr = :useraddress or vcpayeeaddr = vcpayeraddr ) and vcclassname  = :txnClass and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and  CURRENT_DATE) order by dttrxntime desc;"
        },
        "Account": {
            "Payer" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where vcpayeraccountexternalid = :useraddress and vcclassname  = :txnClass and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and  CURRENT_DATE) order by dttrxntime desc;",
            "Payee" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where vcpayeeaccountexternalid = :useraddress and vcclassname  = :txnClass and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and  CURRENT_DATE) order by dttrxntime desc;",
            "Both" : "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where (vcpayeraccountexternalid = :useraddress or vcpayeeaccountexternalid = vcpayeraccountexternalid )  and vcclassname  = :txnClass and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and CURRENT_DATE) order by dttrxntime desc;"
       }
    }
}', 'PartyTrans', false, true);
INSERT INTO ui.perspectivequery (iperspectivequeryid, vcquery, vctablename, formattingrequiered, runonanalytics) VALUES (36, 'SELECT * from transactions.getdecisiondetails(
	:vcMsgID
)', 'DecisionDetailsAna', false, true);
INSERT INTO ui.perspectivequery (iperspectivequeryid, vcquery, vctablename, formattingrequiered, runonanalytics) VALUES (35, '{
    "All": "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans  where score >= :score and ilivemessageid > :iLiveMessageID order by dttrxntime desc;",
    "Other": "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans  where score >= :score and vcclassname  = :className and ilivemessageid > :iLiveMessageID order by dttrxntime desc limit 50;"
}
', 'LiveTransAutoRefresh', false, true);
INSERT INTO ui.perspectivequery (iperspectivequeryid, vcquery, vctablename, formattingrequiered, runonanalytics) VALUES (38, 'select ilivemessageid as "ILiveMessageID", vcmsgid as "UniqueID", vcclassname as "Class", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as "Time",
dobservationamount as "Amount", score as "Score",  cast(result->''score''->>''bpass'' as text)as "FRMPass", vcpayeraccountexternalid as "Payer Account", vcpayeraddr as "PayerVPA",
vcpayeeaccountexternalid as "Payee Account", vcpayeeaddr as "PayeeVPA", null as "FailedRule", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as "PayerName",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as "PayeeName" from transactions.trans
where vcpayeraddr = (select vcpayeraddr from transactions.trans order by dttrxntime desc limit 1) and (CAST(dttrxntime AS date) between CURRENT_DATE-1 and CURRENT_DATE) order by dttrxntime desc;
', 'PartyTransInitial', false, true);
INSERT INTO ui.perspectivequery (iperspectivequeryid, vcquery, vctablename, formattingrequiered, runonanalytics) VALUES (34, '{
    "All": "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where score >= :score order by dttrxntime desc limit 50;",
    "Other": "select ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where score >= :score and vcclassname  = :className order by dttrxntime desc limit 50;"
}
', 'LiveTrans50', false, true);

INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (76, 0, 'className', 'JsonPath', 34, 0);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (77, 1, 'score', 'Integer', 34, NULL);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (78, 0, 'className', 'JsonPath', 35, 0);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (79, 1, 'score', 'Integer', 35, NULL);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (80, 2, 'iLiveMessageID', 'Integer', 35, NULL);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (81, 0, 'vcMsgID', 'String', 36, NULL);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (83, 1, 'party', 'JsonPath', 37, 1);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (84, 2, 'userType', 'JsonPath', 37, 2);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (85, 3, 'useraddress', 'String', 37, NULL);
INSERT INTO ui.perspectivequeryparameters (iperspectiveparameterid, iposition, vcparametername, vcparametertype, iperspectivequeryid, iorder) VALUES (82, 0, 'txnClass', 'JsonPath', 37, 0);
