
INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired) VALUES (56, true, '{"iLiveMessageID":null,"className":null,"score":null}', '{
    "All": "select result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans  where score >= :score and ilivemessageid > :iLiveMessageID order by dttrxntime desc;",
    "Other": "select result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans  where score >= :score and vcclassname  = :className and ilivemessageid > :iLiveMessageID order by dttrxntime desc;"
}
', false, true, false);


INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired) VALUES (55, true, '{"className":null,"score":null}', '{"All": "select result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where score >= :score order by dttrxntime desc limit 50;",
"Other": "select result->''score''->>''decisiondetails'' as \"decisiondetails\", ilivemessageid as \"ILiveMessageID\", vcmsgid as \"UniqueID\", vcclassname as \"Class\", dttrxntime at time zone ''Asia/Kolkata'' at time zone :timeZone as \"Time\", dobservationamount as \"Amount\", score as \"Score\",  cast(result->''score''->>''bpass'' as text)as \"FRMPass\", vcpayeraccountexternalid as \"Payer Account\", vcpayeraddr as \"PayerVPA\", vcpayeeaccountexternalid as \"Payee Account\", vcpayeeaddr as \"PayeeVPA\", null as \"FailedRule\", cast(observations->''observations''->''payerVPA''->>''vpaName'' as text) as \"PayerName\",  cast(observations->''observations''->''payeeVPA''->>''vpaName'' as text) as \"PayeeName\" from transactions.trans where score >= :score and vcclassname  = :className order by dttrxntime desc limit 50;"}', false, true, false);



INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (88, 'score', 'Integer', 55, NULL);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (89, 'className', 'JsonPath', 55, 0);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (91, 'score', 'Integer', 56, NULL);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (92, 'iLiveMessageID', 'Integer', 56, NULL);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (90, 'className', 'JsonPath', 56, 0);


INSERT INTO ui.dashboardresultset (idashboardresultsetid, iresultsetorder, vcdashboardresultsetcolumnjson, vcdashboardresultsetlayout, vcdashboardresultsetname, idashboardqueryid, idashboardid, vcdashboardresultsetschema, icolsize, irowno, dtlastupdatedtimestamp, iuserid) VALUES (25, NULL, NULL, '{"sizes":[0.8,0.2],"detail":{"main":{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_0"],"currentIndex":0}},"mode":"globalFilters","master":{"widgets":["PERSPECTIVE_GENERATED_ID_2"],"sizes":[1]},"viewers":{"PERSPECTIVE_GENERATED_ID_2":{"plugin":"Custom Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Material Dark","group_by":[],"split_by":[],"columns":["ILiveMessageID","UniqueID","Class","Type","Time","Amount","Score","FRMPass","Payer Account","PayerVPA","Payee Account","PayeeVPA","PayerName","PayeeName","decisiondetails"],"filter":[],"sort":[["Time","desc"]],"expressions":["//Type\n    if (is_not_null(\"Payer Account\") and   is_not_null(\"Payee Account\")) {\n        ''A2A''\n    } else if (is_not_null(\"Payer Account\")) {\n        ''A2P''\n    } else if (is_not_null(\"Payee Account\")) {\n        ''P2A''\n    }else\n    {\n        ''-''\n    }"],"aggregates":{},"master":true,"name":"Live Transaction","table":"livetransaction","linked":false,"selectable":"true"},"PERSPECTIVE_GENERATED_ID_0":{"plugin":"Custom Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":true},"settings":false,"theme":"Material Dark","group_by":[],"split_by":[],"columns":["Rule Name","Score","Order","Remarks"],"filter":[],"sort":[["Order","asc"]],"expressions":[],"aggregates":{},"master":false,"name":"Decision Detail","table":"decisiondetailslive","linked":false}}}', 'livetransaction', 55, NULL, '{"ILiveMessageID":"string","UniqueID":"string","Class":"string","Time":"datetime","Payer Account":"string","PayerVPA":"string","PayerName":"string","Payee Account":"string","PayeeVPA":"string","PayeeName":"string","Amount":"float","FRMPass":"string","Score":"integer","FailedRule":"string", "decisiondetails":"string"}', NULL, NULL, NULL, NULL);


UPDATE ui.dashboardquery SET
vcdashboardquery = '{
      "Account":"with recursive profile as ( SELECT * FROM masters.accounts limit 1000), flat ( iaccountid, key, value) as ( select iaccountid,'''', cast(format(''{\"iaccountid\":\"%s\",\"icustomerid\":\"%s\",\"vcexternalaccountid\":\"%s\",\"iaccounttypeid\":\"%s\" ,\"vcaccount\":\"%s\" ,\"vcifsc\":\"%s\",\"vcaccountproviderid\":\"%s\",\"vcaccountname\":\"%s\",\"dtonboardingdate\":\"%s\",\"dtexpirydate\":\"%s\" ,\"bmerchant\":\"%s\",\"irecordstatus\":\"%s\",\"dtentrydatetime\":\"%s\",\"imcc\":\"%s\",\"bverified\":\"%s\"}'',cast(iaccountid as text),cast(icustomerid as text),vcexternalaccountid, cast(iaccounttypeid as text),vcaccount, vcifsc, vcaccountproviderid, vcaccountname, dtonboardingdate, dtexpirydate, bmerchant, irecordstatus,dtentrydatetime, cast(imcc as text), cast(bverified as text)) as jsonb) as value from profile \n union select  iaccountid,concat( ''attrib.'', key), value from profile, jsonb_each(vcattribs) \n union select  iaccountid,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select iaccountid,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by iaccountid) a;",
      "VPA": "with recursive profile as ( SELECT * FROM masters.vpa limit 1000), flat ( ivpaid, key, value) as ( select ivpaid,'''', cast(format(''{\"ivpaid\":\"%s\",\"iaccountid\":\"%s\",\"vcexternaladdressid\":\"%s\",\"vcaddress\":\"%s\" ,\"iproductid\":\"%s\" ,\"vcvpaname\":\"%s\",\"bverified\":\"%s\",\"imcc\":\"%s\",\"dtonboardingdate\":\"%s\",\"dtexpirydate\":\"%s\" ,\"bmerchant\":\"%s\",\"irecordstatus\":\"%s\",\"dtentrydatetime\":\"%s\",\"ivpaproviderid\":\"%s\",\"bprofiled\":\"%s\",\"dtfirsttransaction\":\"%s\" ,\"dtlasttransaction\":\"%s\"}'', cast(ivpaid as text),cast(iaccountid as text), vcexternaladdressid,vcaddress, cast(iproductid as text), vcvpaname,bverified, cast(imcc as text),dtonboardingdate, dtexpirydate,  bmerchant, irecordstatus, dtentrydatetime,ivpaproviderid, bprofiled,  dtfirsttransaction,dtlasttransaction) as jsonb) as value from profile \n union select  ivpaid,concat( ''attrib.'', key), value from profile, jsonb_each(vcattribs) \n union select  ivpaid,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select ivpaid,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by ivpaid) a;"
  }'::text WHERE
idashboardqueryid = 48;