-- Party Profile

INSERT INTO ui.dashboard_17 VALUES (77, true, false, 'Party Profile - DL', 17, 1, 510, 17, true);


INSERT INTO ui.dashboardfilters_17 VALUES ((SELECT max(idashboardfilterid)+1 FROM ui.dashboardfilters), 0, 'DateRange', 77, 'DateRangePicker', 32, NULL, 17, 'Date Range');
INSERT INTO ui.dashboardfilters_17 VALUES ((SELECT max(idashboardfilterid)+1 FROM ui.dashboardfilters), 2, 'VpaAddress', 77, 'Input', NULL, NULL, 17, 'Address');
INSERT INTO ui.dashboardfilters_17 VALUES ((SELECT max(idashboardfilterid)+1 FROM ui.dashboardfilters), 1, 'Party', 77, 'Select', NULL, 27, 17, 'Level');

INSERT INTO ui.dashboardquery_17 VALUES (163, true, '{"DateRange" : null, "VpaAddress":null, "Party": null}', '{
    "Account": "WITH RECURSIVE profile (iaccountid, tdate, val) AS (SELECT pv.iaccountid, pv.tdate, json_parse(pv.val || format(''{\"Address\":\"%s\",\"Name\":\"%s\",\"Last Update\":\"%s\"}'', v.vcexternalaccountid, v.vcaccountname, pv.last_updated)) AS val FROM landing.profiles.account pv LEFT JOIN landing.masters.accounts v ON v.iaccountid = pv.iaccountid AND v.itenantid = :tenantid WHERE pv.tdate BETWEEN DATE :StartDate AND DATE :EndDate - INTERVAL ''1'' DAY AND v.vcexternalaccountid = ''12''), flat (iaccountid, tdate, key, value) AS (SELECT iaccountid, tdate, key, value FROM profile, UNNEST(CAST(map_keys(CAST(json_extract(val, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<VARCHAR>), CAST(map_values(CAST(json_extract(val, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<JSON>)) AS t(key, value) UNION ALL SELECT f.iaccountid, f.tdate, f.key || ''.'' || j.key, j.value FROM flat f, UNNEST(CAST(map_keys(CAST(json_extract(f.value, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<VARCHAR>), CAST(map_values(CAST(json_extract(f.value, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<JSON>)) AS j(key, value) WHERE typeof(f.value) = ''json'') SELECT CAST(json_format(json_parse(''['' || array_join(array_agg(json_format(CAST(data AS JSON))), '','') || '']'')) AS VARCHAR) FROM (SELECT f.iaccountid, f.tdate, map_agg(COALESCE(m.vccolumnname, f.key), f.value) AS data FROM flat f LEFT JOIN landing.profiles.metadata m ON m.vcpath = f.key AND m.vcroot = ''account'' AND m.itenantid = :tenantid WHERE typeof(f.value) <> ''json'' GROUP BY f.iaccountid, f.tdate) a LIMIT 1000;",
    "VPA": "WITH RECURSIVE profile (ivpaid, tdate, val) AS (SELECT pv.ivpaid, pv.tdate, json_parse(pv.val || format(''{\"Address\":\"%s\",\"Name\":\"%s\",\"Last Update\":\"%s\"}'', v.vcexternaladdressid, v.vcvpaname, pv.last_updated)) AS val FROM landing.profiles.vpa pv LEFT JOIN landing.masters.vpa v ON v.ivpaid = pv.ivpaid and v.itenantid=:tenantid WHERE pv.tdate BETWEEN DATE :StartDate AND DATE :EndDate - INTERVAL ''1'' DAY AND v.vcexternaladdressid = :VpaAddress), flat (ivpaid, tdate, key, value) AS (SELECT ivpaid, tdate, key, value FROM profile, UNNEST(CAST(map_keys(CAST(json_extract(val, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<VARCHAR>), CAST(map_values(CAST(json_extract(val, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<JSON>)) AS t(key, value) UNION ALL SELECT f.ivpaid, f.tdate, f.key || ''.'' || j.key, j.value FROM flat f, UNNEST(CAST(map_keys(CAST(json_extract(f.value, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<VARCHAR>), CAST(map_values(CAST(json_extract(f.value, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<JSON>)) AS j(key, value) WHERE typeof(f.value) = ''json'') SELECT CAST(json_format(json_parse(''['' || array_join(array_agg(json_format(CAST(data AS JSON))), '','') || '']'')) AS VARCHAR) FROM (SELECT f.ivpaid, f.tdate, map_agg(COALESCE(m.vccolumnname, f.key), f.value) AS data FROM flat f LEFT JOIN landing.profiles.metadata m ON m.vcpath = f.key AND m.vcroot = ''vpa'' AND m.itenantid = :tenantid WHERE typeof(f.value) <> ''json'' GROUP BY f.ivpaid, f.tdate) a LIMIT 1000;"
}', true, true, false, 510, 17, 2);


INSERT INTO ui.dashboardqueryparameters_17 VALUES ((SELECT max(idashboardparameterid)+1 FROM ui.dashboardqueryparameters), 'DateRange', 'DateRange', 163, NULL, 17);
INSERT INTO ui.dashboardqueryparameters_17 VALUES ((SELECT max(idashboardparameterid)+1 FROM ui.dashboardqueryparameters), 'VpaAddress', 'String', 163, NULL, 17);
INSERT INTO ui.dashboardqueryparameters_17 VALUES ((SELECT max(idashboardparameterid)+1 FROM ui.dashboardqueryparameters), 'Party', 'JsonPath', 163, 0, 17);

INSERT INTO ui.dashboardresultset_17 VALUES (236, NULL, NULL, '{"sizes":[1],"detail":{"main":{"type":"tab-area","widgets":["PERSPECTIVE_GENERATED_ID_1"],"currentIndex":0}},"mode":"globalFilters","viewers":{"PERSPECTIVE_GENERATED_ID_1":{"plugin":"Datagrid","plugin_config":{"columns":{},"editable":false,"scroll_lock":false},"settings":false,"theme":"Pro Dark","title":"Party Profile","group_by":[],"split_by":[],"columns":["Name","tdate","Address","iaccountid","Last Update","Acc Activation Dt","Total Count_Payee","Total Count_Payer","dormantDays.payee","dormantDays.payer","Avg Value_P90_Payee","Avg Value_P90_Payer","Max Value_P5D_Payer","Max Value_P90_Payee","Max Value_P90_Payer","Total Value_P7_Payee","Total Value_P7_Payer","totalCount.p5d.payee","totalCount.p5d.payer","totalValue.p5d.payee","totalValue.p5d.payer","Active Days_P30_Payee","Active Days_P30_Payer","Last Trans Date_Payee","Last Trans Date_Payer","Total Count_P30_Payee","Total Count_P30_Payer","Total Value_P15_Payee","Total Value_P15_Payer","Total Value_P30_Payee","Total Value_P30_Payer","Total Value_P90_Payee","Total Value_P90_Payer","totalCount.p20d.payee","totalCount.p20d.payer","First Trans Date_Payee","First Trans Date_Payer","Max Value P5D_PayeeAcc","Total Value_PAll_Payee","Total Value_PAll_Payer","Days In The System_Payee","Days In The System_Payer","Distinct Payer_P30_Payee","Disctinct Payee_P30_Payer","location.p30d.countries.IN","location.p30d.states.IN-KA","totalCount.p7d.above100.payee","totalCount.p7d.above100.payer","totalCount.p4d.byP2X.payee.P2P","totalCount.p4d.byP2X.payer.P2P","totalValue.p4d.byP2X.payee.P2P","totalValue.p4d.byP2X.payer.P2P","relationships.p30d.payee.105805","relationships.p30d.payer.105805","totalCount.p7d.byClass.payer.UPI","totalValue.p7d.byClass.payer.UPI","totalCount.p7d.byClass.payee.CARD","totalCount.p7d.byClass.payer.CARD","totalValue.p7d.byClass.payee.CARD","totalValue.p7d.byClass.payer.CARD","totalCount.p3d.below2K_CARD_P2P.payee","totalCount.p3d.below2K_CARD_P2P.payer"],"filter":[],"sort":[],"expressions":[],"aggregates":{},"master":false,"table":"partyprofile","linked":false}}} ', 'partyprofile', 163, 77, NULL, 12, 1, NULL, NULL, 510, 17, 5);

UPDATE ui.dashboardquery SET
vcdashboardquery =  E'{
    "Account": "WITH RECURSIVE profile (iaccountid, tdate, val) AS (SELECT pv.iaccountid, pv.tdate, json_parse(pv.val || format(''{\\"Address\\":\\"%s\\",\\"Name\\":\\"%s\\",\\"Last Update\\":\\"%s\\"}'', v.vcexternalaccountid, v.vcaccountname, pv.last_updated)) AS val FROM t17landingtest.profiles.account pv LEFT JOIN t17landingtest.masters.accounts v ON v.iaccountid = pv.iaccountid AND v.itenantid = :tenantid WHERE pv.tdate BETWEEN cast(:StartDate as TIMESTAMP) AND cast(:EndDate as TIMESTAMP) - INTERVAL ''1'' DAY AND v.vcexternalaccountid = :VpaAddress), flat (iaccountid, tdate, key, value) AS (SELECT iaccountid, tdate, key, value FROM profile, UNNEST(CAST(map_keys(CAST(json_extract(val, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<VARCHAR>), CAST(map_values(CAST(json_extract(val, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<JSON>)) AS t(key, value) UNION ALL SELECT f.iaccountid, f.tdate, f.key || ''.'' || j.key, j.value FROM flat f, UNNEST(CAST(map_keys(CAST(json_extract(f.value, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<VARCHAR>), CAST(map_values(CAST(json_extract(f.value, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<JSON>)) AS j(key, value) WHERE typeof(f.value) = ''json'') SELECT CAST(json_format(json_parse(''['' || array_join(array_agg(json_format(CAST(data AS JSON))), '','') || '']'')) AS VARCHAR) FROM (SELECT f.iaccountid, f.tdate, map_agg(COALESCE(m.vccolumnname, f.key), f.value) AS data FROM flat f LEFT JOIN t17landingtest.profiles.metadata m ON m.vcpath = f.key AND m.vcroot = ''account'' AND m.itenantid = :tenantid WHERE typeof(f.value) <> ''json'' GROUP BY f.iaccountid, f.tdate) a LIMIT 1000",
    "VPA": "WITH RECURSIVE profile (ivpaid, tdate, val) AS (SELECT pv.ivpaid, pv.tdate, json_parse(pv.val || format(''{\\"Address\\":\\"%s\\",\\"Name\\":\\"%s\\",\\"Last Update\\":\\"%s\\"}'', v.vcexternaladdressid, v.vcvpaname, pv.last_updated)) AS val FROM t17landingtest.profiles.vpa pv LEFT JOIN t17landingtest.masters.vpa v ON v.ivpaid = pv.ivpaid and v.itenantid=:tenantid WHERE pv.tdate BETWEEN cast(:StartDate as TIMESTAMP) AND cast(:EndDate as TIMESTAMP) - INTERVAL ''1'' DAY AND v.vcexternaladdressid = :VpaAddress), flat (ivpaid, tdate, key, value) AS (SELECT ivpaid, tdate, key, value FROM profile, UNNEST(CAST(map_keys(CAST(json_extract(val, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<VARCHAR>), CAST(map_values(CAST(json_extract(val, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<JSON>)) AS t(key, value) UNION ALL SELECT f.ivpaid, f.tdate, f.key || ''.'' || j.key, j.value FROM flat f, UNNEST(CAST(map_keys(CAST(json_extract(f.value, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<VARCHAR>), CAST(map_values(CAST(json_extract(f.value, ''$'') AS MAP<VARCHAR, JSON>)) AS ARRAY<JSON>)) AS j(key, value) WHERE typeof(f.value) = ''json'') SELECT CAST(json_format(json_parse(''['' || array_join(array_agg(json_format(CAST(data AS JSON))), '','') || '']'')) AS VARCHAR) FROM (SELECT f.ivpaid, f.tdate, map_agg(COALESCE(m.vccolumnname, f.key), f.value) AS data FROM flat f LEFT JOIN t17landingtest.profiles.metadata m ON m.vcpath = f.key AND m.vcroot = ''vpa'' AND m.itenantid = :tenantid WHERE typeof(f.value) <> ''json'' GROUP BY f.ivpaid, f.tdate) a LIMIT 1000"
}'::text WHERE
idashboardqueryid = 163 AND itenantid = 17;