-- 1. rename existing table to old table
ALTER TABLE ui.transactionclasses
    RENAME TO old_transactionclasses;

CREATE TABLE IF NOT EXISTS ui.transactionclasses
(
    iclassid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bactive boolean,
    bpayeemandatory boolean,
    bpayermandatory boolean,
    dtentrydatetime timestamp without time zone,
    ichannelid integer NOT NULL,
    irecordstatus integer,
    vcclassname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vcdecisionparams jsonb,
    iproductid integer,
    dtapproverstamp timestamp without time zone,
    dtentrystamp timestamp without time zone,
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    laststatus character varying(255) COLLATE pg_catalog."default",
    latestremark character varying(255) COLLATE pg_catalog."default",
    idecisionid integer,
    attribs jsonb,
    skipprocessing integer,
    itenantid integer NOT NULL,
    CONSTRAINT transactionclasses_pk PRIMARY KEY (itenantid, iclassid),
    CONSTRAINT fk5s15xeosqycwmb431klvbhi9g FOREIGN KEY (itenantid)
        REFERENCES ui.tenants (itenantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk9c1uqffstrhgvks6qnugth5gn FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkc1qahv5nl41ewrnnj5mey7efx FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkfo6cvrkar9bkaj3o0www5e5go FOREIGN KEY (iproductid)
        REFERENCES masters.products (iproductid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkt8s16le35wsd2w11kno2ovt0j FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)PARTITION BY LIST(itenantid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_vcclassname
    ON ui.transactionclasses USING btree
    (itenantid ASC, vcclassname ASC);


CREATE TABLE ui.transactionclasses_1 PARTITION OF ui.transactionclasses
    FOR VALUES IN(1);

CREATE TABLE ui.transactionclasses_2 PARTITION OF ui.transactionclasses
    FOR VALUES IN(2);

CREATE TABLE ui.transactionclasses_3 PARTITION OF ui.transactionclasses
    FOR VALUES IN(3);


CREATE TABLE ui.transactionclasses_4 PARTITION OF ui.transactionclasses
    FOR VALUES IN(4);


CREATE TABLE ui.transactionclasses_5 PARTITION OF ui.transactionclasses
    FOR VALUES IN(5);


CREATE TABLE ui.transactionclasses_6 PARTITION OF ui.transactionclasses
    FOR VALUES IN(6);


CREATE TABLE ui.transactionclasses_7 PARTITION OF ui.transactionclasses
    FOR VALUES IN(7);


CREATE TABLE ui.transactionclasses_8 PARTITION OF ui.transactionclasses
    FOR VALUES IN(8);


CREATE TABLE ui.transactionclasses_9 PARTITION OF ui.transactionclasses
    FOR VALUES IN(9);


CREATE TABLE ui.transactionclasses_10 PARTITION OF ui.transactionclasses
    FOR VALUES IN(10);


CREATE TABLE ui.transactionclasses_11 PARTITION OF ui.transactionclasses
    FOR VALUES IN(11);


CREATE TABLE ui.transactionclasses_12 PARTITION OF ui.transactionclasses
    FOR VALUES IN(12);


CREATE TABLE ui.transactionclasses_13 PARTITION OF ui.transactionclasses
    FOR VALUES IN(13);


CREATE TABLE ui.transactionclasses_14 PARTITION OF ui.transactionclasses
    FOR VALUES IN(14);


CREATE TABLE ui.transactionclasses_15 PARTITION OF ui.transactionclasses
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.transactionclasses(
	iclassid, bactive, bpayeemandatory, bpayermandatory, dtentrydatetime, ichannelid, irecordstatus, vcclassname, vcdecisionparams, iproductid, dtapproverstamp, dtentrystamp, iapproveruserid, ientryuserid, istatus, laststatus, latestremark, idecisionid, attribs, skipprocessing, itenantid)
SELECT iclassid, bactive, bpayeemandatory, bpayermandatory, dtentrydatetime, ichannelid, irecordstatus, vcclassname, vcdecisionparams, iproductid, dtapproverstamp, dtentrystamp, iapproveruserid, ientryuserid, istatus, laststatus, latestremark, idecisionid, attribs, skipprocessing, COALESCE(itenantid,1) itenantid
	FROM ui.old_transactionclasses; 


-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('ui.transactionclasses', 'iclassid'), 
    (SELECT MAX(iclassid) FROM ui.transactionclasses)
);



-- 1. rename existing table to old table
ALTER TABLE ui.decisions
    RENAME TO old_decisions;

CREATE TABLE IF NOT EXISTS ui.decisions
(
    idecisionid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dtapproverstamp timestamp without time zone,
    dtentrystamp timestamp without time zone,
    bactive boolean,
    dtentrydatetime timestamp without time zone,
    irecordstatus integer,
    laststatus character varying(255) COLLATE pg_catalog."default",
    latestremark character varying(255) COLLATE pg_catalog."default",
    vcdecisiondetail character varying(255) COLLATE pg_catalog."default",
    vcdecisionmapinfo character varying(255) COLLATE pg_catalog."default",
    vcdecisionname character varying(20) COLLATE pg_catalog."default",
    vcresultparams jsonb,
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    iproductid integer,
    iuserid integer,
    masterdecisionid integer,
    attribs jsonb,
    itenantid integer NOT NULL,
    CONSTRAINT decisions_pk PRIMARY KEY (itenantid, idecisionid),
    CONSTRAINT fk9k7iendf5jgu2ggcx24qu96xb FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkbu43gtxyehe2mv4mymymjspx6 FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkfajpc35yl8kg85x6plwrmu6n6 FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkk56ah9unhyk26uma8sh43giih FOREIGN KEY (iuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fko3196afavrgekf3gx4r2y98jh FOREIGN KEY (itenantid)
        REFERENCES ui.tenants (itenantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkr9ds06q3yq6pgstpv8v1jk1vi FOREIGN KEY (iproductid)
        REFERENCES masters.products (iproductid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
PARTITION BY LIST(itenantid);

-- CREATE UNIQUE INDEX IF NOT EXISTS uk_vcdecisionname
--     ON ui.decisions USING btree
--     (itenantid ASC, vcdecisionname ASC);


-- create partitions
CREATE TABLE ui.decisions_1 PARTITION OF ui.decisions
    FOR VALUES IN(1);

CREATE TABLE ui.decisions_2 PARTITION OF ui.decisions
    FOR VALUES IN(2);

CREATE TABLE ui.decisions_3 PARTITION OF ui.decisions
    FOR VALUES IN(3);


CREATE TABLE ui.decisions_4 PARTITION OF ui.decisions
    FOR VALUES IN(4);


CREATE TABLE ui.decisions_5 PARTITION OF ui.decisions
    FOR VALUES IN(5);


CREATE TABLE ui.decisions_6 PARTITION OF ui.decisions
    FOR VALUES IN(6);


CREATE TABLE ui.decisions_7 PARTITION OF ui.decisions
    FOR VALUES IN(7);


CREATE TABLE ui.decisions_8 PARTITION OF ui.decisions
    FOR VALUES IN(8);


CREATE TABLE ui.decisions_9 PARTITION OF ui.decisions
    FOR VALUES IN(9);


CREATE TABLE ui.decisions_10 PARTITION OF ui.decisions
    FOR VALUES IN(10);


CREATE TABLE ui.decisions_11 PARTITION OF ui.decisions
    FOR VALUES IN(11);


CREATE TABLE ui.decisions_12 PARTITION OF ui.decisions
    FOR VALUES IN(12);


CREATE TABLE ui.decisions_13 PARTITION OF ui.decisions
    FOR VALUES IN(13);


CREATE TABLE ui.decisions_14 PARTITION OF ui.decisions
    FOR VALUES IN(14);


CREATE TABLE ui.decisions_15 PARTITION OF ui.decisions
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.decisions(
	idecisionid, dtapproverstamp, dtentrystamp, bactive, dtentrydatetime, irecordstatus, laststatus, latestremark, vcdecisiondetail, vcdecisionmapinfo, vcdecisionname, vcresultparams, iapproveruserid, ientryuserid, istatus, iproductid, iuserid, masterdecisionid, attribs, itenantid)
SELECT idecisionid, dtapproverstamp, dtentrystamp, bactive, dtentrydatetime, irecordstatus, laststatus, latestremark, vcdecisiondetail, vcdecisionmapinfo, vcdecisionname, vcresultparams, iapproveruserid, ientryuserid, istatus, iproductid, iuserid, masterdecisionid, attribs, COALESCE(itenantid,1) itenantid
	FROM ui.old_decisions;


-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('ui.decisions', 'idecisionid'), 
    (SELECT MAX(idecisionid) FROM ui.decisions)
);



-- 1. rename existing table to old table
ALTER TABLE ui.rules
    RENAME TO old_rules;

CREATE TABLE IF NOT EXISTS ui.rules
(
    iruleid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bactive boolean,
    bcustom boolean,
    bdelete boolean,
    dtentrydatetime timestamp without time zone,
    dtstartdate timestamp without time zone,
    iversion integer,
    vcbpmnfilelocation character varying(255) COLLATE pg_catalog."default",
    vcruledescription character varying(1000) COLLATE pg_catalog."default",
    vcruledetail text COLLATE pg_catalog."default",
    vcrulemapinfo character varying(255) COLLATE pg_catalog."default",
    vcrulename character varying(255) COLLATE pg_catalog."default",
    vcruleorder character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vcruleparams text COLLATE pg_catalog."default",
    idecisionid integer NOT NULL,
    iuserid integer,
    iruleavailableid integer,
    vclabel text COLLATE pg_catalog."default",
    ruledimension character varying(255) COLLATE pg_catalog."default",
    rulestate character varying(255) COLLATE pg_catalog."default",
    vcruletype character varying(255) COLLATE pg_catalog."default",
    iinstance integer,
    dtapproverstamp timestamp without time zone,
    dtentrystamp timestamp without time zone,
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    vcquery text COLLATE pg_catalog."default",
    bapicall boolean,
    bexecutequery boolean,
    vcqueryresultmap jsonb,
    vcqueryfilterparams jsonb,
    vcresponseapiattribs jsonb,
    itenantid integer NOT NULL,
    CONSTRAINT rules_pk PRIMARY KEY (iruleid, idecisionid, itenantid),
    CONSTRAINT fk62hmehc3f53o4p6ddnh54pokg FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkegde6r59g6mie8f1qyr0w0d1f FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fksy7v9wykm1xdo7v0g8cft34kq FOREIGN KEY (iuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkt0cstkqnev0tajwow4ygh97nq FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
PARTITION BY LIST(itenantid);


-- create partitions
CREATE TABLE ui.rules_1 PARTITION OF ui.rules
    FOR VALUES IN(1);

CREATE TABLE ui.rules_2 PARTITION OF ui.rules
    FOR VALUES IN(2);

CREATE TABLE ui.rules_3 PARTITION OF ui.rules
    FOR VALUES IN(3);


CREATE TABLE ui.rules_4 PARTITION OF ui.rules
    FOR VALUES IN(4);


CREATE TABLE ui.rules_5 PARTITION OF ui.rules
    FOR VALUES IN(5);


CREATE TABLE ui.rules_6 PARTITION OF ui.rules
    FOR VALUES IN(6);


CREATE TABLE ui.rules_7 PARTITION OF ui.rules
    FOR VALUES IN(7);


CREATE TABLE ui.rules_8 PARTITION OF ui.rules
    FOR VALUES IN(8);


CREATE TABLE ui.rules_9 PARTITION OF ui.rules
    FOR VALUES IN(9);


CREATE TABLE ui.rules_10 PARTITION OF ui.rules
    FOR VALUES IN(10);


CREATE TABLE ui.rules_11 PARTITION OF ui.rules
    FOR VALUES IN(11);


CREATE TABLE ui.rules_12 PARTITION OF ui.rules
    FOR VALUES IN(12);


CREATE TABLE ui.rules_13 PARTITION OF ui.rules
    FOR VALUES IN(13);


CREATE TABLE ui.rules_14 PARTITION OF ui.rules
    FOR VALUES IN(14);


CREATE TABLE ui.rules_15 PARTITION OF ui.rules
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.rules(
	iruleid, bactive, bcustom, bdelete, dtentrydatetime, dtstartdate, iversion, vcbpmnfilelocation, vcruledescription, vcruledetail, vcrulemapinfo, vcrulename, vcruleorder, vcruleparams, idecisionid, iuserid, iruleavailableid, vclabel, ruledimension, rulestate, vcruletype, iinstance, dtapproverstamp, dtentrystamp, iapproveruserid, ientryuserid, istatus, vcquery, bapicall, bexecutequery, vcqueryresultmap, vcqueryfilterparams, vcresponseapiattribs, itenantid)
SELECT iruleid, bactive, bcustom, bdelete, dtentrydatetime, dtstartdate, iversion, vcbpmnfilelocation, vcruledescription, vcruledetail, vcrulemapinfo, vcrulename, vcruleorder, vcruleparams, idecisionid, iuserid, iruleavailableid, vclabel, ruledimension, rulestate, vcruletype, iinstance, dtapproverstamp, dtentrystamp, iapproveruserid, ientryuserid, istatus, vcquery, bapicall, bexecutequery, vcqueryresultmap, vcqueryfilterparams, vcresponseapiattribs, COALESCE(itenantid,1) itenantid
	FROM ui.old_rules;


-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('ui.rules', 'iruleid'), 
    (SELECT MAX(iruleid) FROM ui.rules)
);



-- 1. rename existing table to old table
ALTER TABLE ui.rulesavailable
    RENAME TO old_rulesavailable;

CREATE TABLE IF NOT EXISTS ui.rulesavailable
(
    iruleavailableid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bcustom boolean,
    bpayee boolean,
    bpayer boolean,
    btransaction boolean,
    bactive boolean,
    bdelete boolean,
    vclabel text COLLATE pg_catalog."default",
    vcruledescription character varying(1000) COLLATE pg_catalog."default",
    vcruledetail text COLLATE pg_catalog."default",
    ruledimension character varying(255) COLLATE pg_catalog."default",
    vcrulename character varying(255) COLLATE pg_catalog."default",
    vcruleparams text COLLATE pg_catalog."default",
    rulestate character varying(255) COLLATE pg_catalog."default",
    vcruletype character varying(255) COLLATE pg_catalog."default",
    itenantid integer NOT NULL,
    CONSTRAINT rulesavailable_pk PRIMARY KEY (itenantid,iruleavailableid),
    CONSTRAINT fkqqf3r7a9dxvh6mdl5xqhdxftl FOREIGN KEY (itenantid)
        REFERENCES ui.tenants (itenantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
PARTITION BY LIST(itenantid);


-- create partitions
CREATE TABLE ui.rulesavailable_1 PARTITION OF ui.rulesavailable
    FOR VALUES IN(1);

CREATE TABLE ui.rulesavailable_2 PARTITION OF ui.rulesavailable
    FOR VALUES IN(2);

CREATE TABLE ui.rulesavailable_3 PARTITION OF ui.rulesavailable
    FOR VALUES IN(3);


CREATE TABLE ui.rulesavailable_4 PARTITION OF ui.rulesavailable
    FOR VALUES IN(4);


CREATE TABLE ui.rulesavailable_5 PARTITION OF ui.rulesavailable
    FOR VALUES IN(5);


CREATE TABLE ui.rulesavailable_6 PARTITION OF ui.rulesavailable
    FOR VALUES IN(6);


CREATE TABLE ui.rulesavailable_7 PARTITION OF ui.rulesavailable
    FOR VALUES IN(7);


CREATE TABLE ui.rulesavailable_8 PARTITION OF ui.rulesavailable
    FOR VALUES IN(8);


CREATE TABLE ui.rulesavailable_9 PARTITION OF ui.rulesavailable
    FOR VALUES IN(9);


CREATE TABLE ui.rulesavailable_10 PARTITION OF ui.rulesavailable
    FOR VALUES IN(10);


CREATE TABLE ui.rulesavailable_11 PARTITION OF ui.rulesavailable
    FOR VALUES IN(11);


CREATE TABLE ui.rulesavailable_12 PARTITION OF ui.rulesavailable
    FOR VALUES IN(12);


CREATE TABLE ui.rulesavailable_13 PARTITION OF ui.rulesavailable
    FOR VALUES IN(13);


CREATE TABLE ui.rulesavailable_14 PARTITION OF ui.rulesavailable
    FOR VALUES IN(14);


CREATE TABLE ui.rulesavailable_15 PARTITION OF ui.rulesavailable
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.rulesavailable(
	iruleavailableid, bcustom, bpayee, bpayer, btransaction, bactive, bdelete, vclabel, vcruledescription, vcruledetail, ruledimension, vcrulename, vcruleparams, rulestate, vcruletype, itenantid)
SELECT iruleavailableid, bcustom, bpayee, bpayer, btransaction, bactive, bdelete, vclabel, vcruledescription, vcruledetail, ruledimension, vcrulename, vcruleparams, rulestate, vcruletype, COALESCE(itenantid,1) itenantid
	FROM ui.old_rulesavailable;


-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('ui.rulesavailable', 'iruleavailableid'), 
    (SELECT MAX(iruleavailableid) FROM ui.rulesavailable)
);



-- 1. rename existing table to old table
ALTER TABLE ui.observationsui
    RENAME TO old_observationsui;

CREATE TABLE IF NOT EXISTS ui.observationsui
(
    oid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dtapproverstamp timestamp without time zone,
    dtentrystamp timestamp without time zone,
    aggregationtype character varying(255) COLLATE pg_catalog."default",
    dtentrydatetime timestamp without time zone,
    irecordstatus integer,
    laststatus character varying(255) COLLATE pg_catalog."default",
    latestremark character varying(255) COLLATE pg_catalog."default",
    ocount integer,
    oduration character varying(255) COLLATE pg_catalog."default",
    oname character varying(255) COLLATE pg_catalog."default",
    wexpr jsonb,
    whereexpr jsonb,
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    wid integer,
    odesc text COLLATE pg_catalog."default",
    itenantid integer,
    CONSTRAINT observationsui_pk PRIMARY KEY (itenantid, wid, oid),
    CONSTRAINT fk4vghsx5gurs4eo2a1lckjpthn FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkdkk8nun2cy8q72w01scu80wo5 FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fksnyjiqo8eldviuaktphwlbc24 FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)PARTITION BY LIST(itenantid);



CREATE TABLE ui.observationsui_1 PARTITION OF ui.observationsui
    FOR VALUES IN(1);

CREATE TABLE ui.observationsui_2 PARTITION OF ui.observationsui
    FOR VALUES IN(2);

CREATE TABLE ui.observationsui_3 PARTITION OF ui.observationsui
    FOR VALUES IN(3);


CREATE TABLE ui.observationsui_4 PARTITION OF ui.observationsui
    FOR VALUES IN(4);


CREATE TABLE ui.observationsui_5 PARTITION OF ui.observationsui
    FOR VALUES IN(5);


CREATE TABLE ui.observationsui_6 PARTITION OF ui.observationsui
    FOR VALUES IN(6);


CREATE TABLE ui.observationsui_7 PARTITION OF ui.observationsui
    FOR VALUES IN(7);


CREATE TABLE ui.observationsui_8 PARTITION OF ui.observationsui
    FOR VALUES IN(8);


CREATE TABLE ui.observationsui_9 PARTITION OF ui.observationsui
    FOR VALUES IN(9);


CREATE TABLE ui.observationsui_10 PARTITION OF ui.observationsui
    FOR VALUES IN(10);


CREATE TABLE ui.observationsui_11 PARTITION OF ui.observationsui
    FOR VALUES IN(11);


CREATE TABLE ui.observationsui_12 PARTITION OF ui.observationsui
    FOR VALUES IN(12);


CREATE TABLE ui.observationsui_13 PARTITION OF ui.observationsui
    FOR VALUES IN(13);


CREATE TABLE ui.observationsui_14 PARTITION OF ui.observationsui
    FOR VALUES IN(14);


CREATE TABLE ui.observationsui_15 PARTITION OF ui.observationsui
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.observationsui(
	oid, dtapproverstamp, dtentrystamp, aggregationtype, dtentrydatetime, irecordstatus, laststatus, latestremark, ocount, oduration, oname, wexpr, whereexpr, iapproveruserid, ientryuserid, istatus, wid, odesc, itenantid)
SELECT oid, dtapproverstamp, dtentrystamp, aggregationtype, dtentrydatetime, irecordstatus, laststatus, latestremark, ocount, oduration, oname, wexpr, whereexpr, iapproveruserid, ientryuserid, istatus, wid, odesc, COALESCE(itenantid,1) itenantid
	FROM ui.old_observationsui;


-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('ui.observationsui', 'oid'), 
    (SELECT MAX(oid) FROM ui.observationsui)
);



-- 1. rename existing table to old table
ALTER TABLE ui.observationwindowsui
    RENAME TO old_observationwindowsui;

CREATE TABLE IF NOT EXISTS ui.observationwindowsui
(
    wid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dtapproverstamp timestamp without time zone,
    dtentrystamp timestamp without time zone,
    dtentrydatetime timestamp without time zone,
    groupbyexpr jsonb,
    irecordstatus integer,
    laststatus character varying(255) COLLATE pg_catalog."default",
    latestremark character varying(255) COLLATE pg_catalog."default",
    selectexpr jsonb,
    wcount integer,
    wduration character varying(255) COLLATE pg_catalog."default",
    wname character varying(255) COLLATE pg_catalog."default",
    whereexpr jsonb,
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    wdesc text COLLATE pg_catalog."default",
    itenantid integer NOT NULL,
    CONSTRAINT observationwindowsui_pk PRIMARY KEY (itenantid, wid),
    CONSTRAINT fk1rmbw11hhfud0o1h6xx2de7x0 FOREIGN KEY (itenantid)
        REFERENCES ui.tenants (itenantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk6awbc9f7i4popolcowfb1o5g3 FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkdi8tuuy5hp48ogjqoofqeykgb FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkdm0kttq2fkb9fxgjkrs8w5upq FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
PARTITION BY LIST(itenantid);



CREATE TABLE ui.observationwindowsui_1 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(1);

CREATE TABLE ui.observationwindowsui_2 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(2);

CREATE TABLE ui.observationwindowsui_3 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(3);


CREATE TABLE ui.observationwindowsui_4 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(4);


CREATE TABLE ui.observationwindowsui_5 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(5);


CREATE TABLE ui.observationwindowsui_6 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(6);


CREATE TABLE ui.observationwindowsui_7 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(7);


CREATE TABLE ui.observationwindowsui_8 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(8);


CREATE TABLE ui.observationwindowsui_9 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(9);


CREATE TABLE ui.observationwindowsui_10 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(10);


CREATE TABLE ui.observationwindowsui_11 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(11);


CREATE TABLE ui.observationwindowsui_12 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(12);


CREATE TABLE ui.observationwindowsui_13 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(13);


CREATE TABLE ui.observationwindowsui_14 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(14);


CREATE TABLE ui.observationwindowsui_15 PARTITION OF ui.observationwindowsui
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.observationwindowsui(
	wid, dtapproverstamp, dtentrystamp, dtentrydatetime, groupbyexpr, irecordstatus, laststatus, latestremark, selectexpr, wcount, wduration, wname, whereexpr, iapproveruserid, ientryuserid, istatus, wdesc, itenantid)
SELECT wid, dtapproverstamp, dtentrystamp, dtentrydatetime, groupbyexpr, irecordstatus, laststatus, latestremark, selectexpr, wcount, wduration, wname, whereexpr, iapproveruserid, ientryuserid, istatus, wdesc, COALESCE(itenantid,1) itenantid
	FROM ui.observationwindowsui;

-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('ui.observationwindowsui', 'wid'), 
    (SELECT MAX(wid) FROM ui.observationwindowsui)
);



-- 1. rename existing table to old table
ALTER TABLE ui.list
    RENAME TO old_list;
CREATE TABLE IF NOT EXISTS ui.list
(
    ilistitemid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dtapproverstamp timestamp without time zone,
    dtentrystamp timestamp without time zone,
    dteffectivefrom timestamp without time zone,
    dtentrydatetime timestamp without time zone,
    dtexpiresat timestamp without time zone,
    ilisttype integer,
    irecordstatus integer,
    vcexternallistitemid character varying(100) COLLATE pg_catalog."default",
    vcfield character varying(100) COLLATE pg_catalog."default",
    vcnote character varying(200) COLLATE pg_catalog."default",
    vcsource character varying(100) COLLATE pg_catalog."default",
    vcvalue character varying(100) COLLATE pg_catalog."default",
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    attribs jsonb,
    itenantid integer NOT NULL,
    CONSTRAINT list_pk PRIMARY KEY (itenantid, ilistitemid),
    CONSTRAINT fk1s18awlcuf0yeliycnaheu49s FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk4owtwwuhts2vkmf8o3dme46ya FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkoxj70uqurx93bv8kc1pauvk3o FOREIGN KEY (ilisttype)
        REFERENCES ui.listmaster (ilistmasterid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkqnebkthmc1aei029j2xupuh68 FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkqpje45spmgcwnptm3yu2ifgt0 FOREIGN KEY (itenantid)
        REFERENCES ui.tenants (itenantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
PARTITION BY LIST(itenantid);

CREATE UNIQUE INDEX IF NOT EXISTS idx_lists_itenantid_vcexternallistitemid
    ON ui.list USING btree
    (itenantid ASC, vcexternallistitemid ASC NULLS LAST);


CREATE TABLE ui.list_1 PARTITION OF ui.list
    FOR VALUES IN(1);

CREATE TABLE ui.list_2 PARTITION OF ui.list
    FOR VALUES IN(2);

CREATE TABLE ui.list_3 PARTITION OF ui.list
    FOR VALUES IN(3);


CREATE TABLE ui.list_4 PARTITION OF ui.list
    FOR VALUES IN(4);


CREATE TABLE ui.list_5 PARTITION OF ui.list
    FOR VALUES IN(5);


CREATE TABLE ui.list_6 PARTITION OF ui.list
    FOR VALUES IN(6);


CREATE TABLE ui.list_7 PARTITION OF ui.list
    FOR VALUES IN(7);


CREATE TABLE ui.list_8 PARTITION OF ui.list
    FOR VALUES IN(8);


CREATE TABLE ui.list_9 PARTITION OF ui.list
    FOR VALUES IN(9);


CREATE TABLE ui.list_10 PARTITION OF ui.list
    FOR VALUES IN(10);


CREATE TABLE ui.list_11 PARTITION OF ui.list
    FOR VALUES IN(11);


CREATE TABLE ui.list_12 PARTITION OF ui.list
    FOR VALUES IN(12);


CREATE TABLE ui.list_13 PARTITION OF ui.list
    FOR VALUES IN(13);


CREATE TABLE ui.list_14 PARTITION OF ui.list
    FOR VALUES IN(14);


CREATE TABLE ui.list_15 PARTITION OF ui.list
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.list(
	ilistitemid, dtapproverstamp, dtentrystamp, dteffectivefrom, dtentrydatetime, dtexpiresat, ilisttype, irecordstatus, vcexternallistitemid, vcfield, vcnote, vcsource, vcvalue, iapproveruserid, ientryuserid, istatus, attribs, itenantid)
SELECT ilistitemid, dtapproverstamp, dtentrystamp, dteffectivefrom, dtentrydatetime, dtexpiresat, ilisttype, irecordstatus, vcexternallistitemid, vcfield, vcnote, vcsource, vcvalue, iapproveruserid, ientryuserid, istatus, attribs, COALESCE(itenantid,1) itenantid
	FROM ui.old_list;


-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('ui.list', 'ilistitemid'), 
    (SELECT MAX(ilistitemid) FROM ui.list)
);



-- 1. rename existing table to old table
ALTER TABLE ui.metadata
    RENAME TO old_metadata;

CREATE TABLE IF NOT EXISTS ui.metadata
(
    imetadataid integer NOT NULL,
    dtapproverstamp timestamp without time zone,
    dtentrystamp timestamp without time zone,
    bml boolean,
    bscore boolean,
    bui boolean,
    irecordstatus integer,
    vcprefix jsonb,
    vccolumnname character varying(1024) COLLATE pg_catalog."default",
    vcdescription character varying(1024) COLLATE pg_catalog."default",
    vcdtype character varying(32) COLLATE pg_catalog."default",
    vcpath character varying(256) COLLATE pg_catalog."default",
    vcquery text COLLATE pg_catalog."default",
    vcroot character varying(99) COLLATE pg_catalog."default",
    iapproveruserid integer,
    ientryuserid integer,
    istatus integer,
    config jsonb,
    itenantid integer,
    CONSTRAINT metadata_pk PRIMARY KEY (itenantid,imetadataid),
    CONSTRAINT fk3f08fljy79orb42hbe2bbomt2 FOREIGN KEY (ientryuserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkep83wispcpxdqsgqntyaiu7yt FOREIGN KEY (itenantid)
        REFERENCES ui.tenants (itenantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkh6f5h5agp78e0qdw8202k0ys5 FOREIGN KEY (iapproveruserid)
        REFERENCES ui.webuser (iuserid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fksny6fpkiotmw9oeirb3s0y8bb FOREIGN KEY (istatus)
        REFERENCES ui.statuscode (istatusid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)PARTITION BY LIST(itenantid);


CREATE TABLE ui.metadata_1 PARTITION OF ui.metadata
    FOR VALUES IN(1);

CREATE TABLE ui.metadata_2 PARTITION OF ui.metadata
    FOR VALUES IN(2);

CREATE TABLE ui.metadata_3 PARTITION OF ui.metadata
    FOR VALUES IN(3);


CREATE TABLE ui.metadata_4 PARTITION OF ui.metadata
    FOR VALUES IN(4);


CREATE TABLE ui.metadata_5 PARTITION OF ui.metadata
    FOR VALUES IN(5);


CREATE TABLE ui.metadata_6 PARTITION OF ui.metadata
    FOR VALUES IN(6);


CREATE TABLE ui.metadata_7 PARTITION OF ui.metadata
    FOR VALUES IN(7);


CREATE TABLE ui.metadata_8 PARTITION OF ui.metadata
    FOR VALUES IN(8);


CREATE TABLE ui.metadata_9 PARTITION OF ui.metadata
    FOR VALUES IN(9);


CREATE TABLE ui.metadata_10 PARTITION OF ui.metadata
    FOR VALUES IN(10);


CREATE TABLE ui.metadata_11 PARTITION OF ui.metadata
    FOR VALUES IN(11);


CREATE TABLE ui.metadata_12 PARTITION OF ui.metadata
    FOR VALUES IN(12);


CREATE TABLE ui.metadata_13 PARTITION OF ui.metadata
    FOR VALUES IN(13);


CREATE TABLE ui.metadata_14 PARTITION OF ui.metadata
    FOR VALUES IN(14);


CREATE TABLE ui.metadata_15 PARTITION OF ui.metadata
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.metadata(
	imetadataid, dtapproverstamp, dtentrystamp, bml, bscore, bui, irecordstatus, vcprefix, vccolumnname, vcdescription, vcdtype, vcpath, vcquery, vcroot, iapproveruserid, ientryuserid, istatus, config, itenantid)
SELECT imetadataid, dtapproverstamp, dtentrystamp, bml, bscore, bui, irecordstatus, vcprefix, vccolumnname, vcdescription, vcdtype, vcpath, vcquery, vcroot, iapproveruserid, ientryuserid, istatus, config, COALESCE(itenantid,1) itenantid
	FROM ui.old_metadata;


-- Altering the dependent fk
-- Drop the existing foreign key constraint
ALTER TABLE ui.metadataaudit
DROP CONSTRAINT fk_audit_imetadataid;

-- Add a new foreign key constraint referencing ui.metadata
ALTER TABLE ui.metadataaudit
ADD CONSTRAINT fk_audit_imetadataid
FOREIGN KEY (itenantid,imetadataid)
REFERENCES ui.metadata (itenantid,imetadataid)
ON UPDATE NO ACTION
ON DELETE NO ACTION;



-- 1. rename existing table to old table
ALTER TABLE ui.rulesdraft
    RENAME TO old_rulesdraft;

CREATE TABLE IF NOT EXISTS ui.rulesdraft
(
    iruledraftid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bcustom boolean,
    bpayee boolean,
    bpayer boolean,
    btransaction boolean,
    bactive boolean,
    bdelete boolean,
    vclabel text COLLATE pg_catalog."default",
    vcruledescription character varying(1000) COLLATE pg_catalog."default",
    vcruledetail text COLLATE pg_catalog."default",
    ruledimension character varying(255) COLLATE pg_catalog."default",
    vcrulename character varying(255) COLLATE pg_catalog."default",
    vcruleparams text COLLATE pg_catalog."default",
    rulestate character varying(255) COLLATE pg_catalog."default",
    vcruletype character varying(255) COLLATE pg_catalog."default",
    itenantid integer,
    CONSTRAINT rulesdraft_pk PRIMARY KEY (itenantid,iruledraftid),
    CONSTRAINT fkart5q33we932uja5t84uuyag9 FOREIGN KEY (itenantid)
        REFERENCES ui.tenants (itenantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)PARTITION BY LIST(itenantid);


CREATE TABLE ui.rulesdraft_1 PARTITION OF ui.rulesdraft
    FOR VALUES IN(1);

CREATE TABLE ui.rulesdraft_2 PARTITION OF ui.rulesdraft
    FOR VALUES IN(2);

CREATE TABLE ui.rulesdraft_3 PARTITION OF ui.rulesdraft
    FOR VALUES IN(3);


CREATE TABLE ui.rulesdraft_4 PARTITION OF ui.rulesdraft
    FOR VALUES IN(4);


CREATE TABLE ui.rulesdraft_5 PARTITION OF ui.rulesdraft
    FOR VALUES IN(5);


CREATE TABLE ui.rulesdraft_6 PARTITION OF ui.rulesdraft
    FOR VALUES IN(6);


CREATE TABLE ui.rulesdraft_7 PARTITION OF ui.rulesdraft
    FOR VALUES IN(7);


CREATE TABLE ui.rulesdraft_8 PARTITION OF ui.rulesdraft
    FOR VALUES IN(8);


CREATE TABLE ui.rulesdraft_9 PARTITION OF ui.rulesdraft
    FOR VALUES IN(9);


CREATE TABLE ui.rulesdraft_10 PARTITION OF ui.rulesdraft
    FOR VALUES IN(10);


CREATE TABLE ui.rulesdraft_11 PARTITION OF ui.rulesdraft
    FOR VALUES IN(11);


CREATE TABLE ui.rulesdraft_12 PARTITION OF ui.rulesdraft
    FOR VALUES IN(12);


CREATE TABLE ui.rulesdraft_13 PARTITION OF ui.rulesdraft
    FOR VALUES IN(13);


CREATE TABLE ui.rulesdraft_14 PARTITION OF ui.rulesdraft
    FOR VALUES IN(14);


CREATE TABLE ui.rulesdraft_15 PARTITION OF ui.rulesdraft
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO ui.rulesdraft(
	iruledraftid, bcustom, bpayee, bpayer, btransaction, bactive, bdelete, vclabel, vcruledescription, vcruledetail, ruledimension, vcrulename, vcruleparams, rulestate, vcruletype, itenantid)
SELECT iruledraftid, bcustom, bpayee, bpayer, btransaction, bactive, bdelete, vclabel, vcruledescription, vcruledetail, ruledimension, vcrulename, vcruleparams, rulestate, vcruletype, 1 as itenantid
	FROM ui.old_rulesdraft;


-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('ui.rulesdraft', 'iruledraftid'), 
    (SELECT MAX(iruledraftid) FROM ui.rulesdraft)
);


-- 1. rename existing table to old table
ALTER TABLE masters.rulesdraft
    RENAME TO old_rulesdraft;

CREATE TABLE IF NOT EXISTS masters.rulesdraft
(
    iruledraftid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bcustom boolean,
    bpayee boolean,
    bpayer boolean,
    btransaction boolean,
    bactive boolean,
    bdelete boolean,
    vclabel text COLLATE pg_catalog."default",
    vcruledescription character varying(1000) COLLATE pg_catalog."default",
    vcruledetail text COLLATE pg_catalog."default",
    ruledimension character varying(255) COLLATE pg_catalog."default",
    vcrulename character varying(255) COLLATE pg_catalog."default",
    vcruleparams text COLLATE pg_catalog."default",
    rulestate character varying(255) COLLATE pg_catalog."default",
    vcruletype character varying(255) COLLATE pg_catalog."default",
    itenantid integer,
    CONSTRAINT rulesdraft_pk PRIMARY KEY (itenantid, iruledraftid)
)PARTITION BY LIST(itenantid);


CREATE TABLE masters.rulesdraft_1 PARTITION OF masters.rulesdraft
    FOR VALUES IN(1);

CREATE TABLE masters.rulesdraft_2 PARTITION OF masters.rulesdraft
    FOR VALUES IN(2);

CREATE TABLE masters.rulesdraft_3 PARTITION OF masters.rulesdraft
    FOR VALUES IN(3);


CREATE TABLE masters.rulesdraft_4 PARTITION OF masters.rulesdraft
    FOR VALUES IN(4);


CREATE TABLE masters.rulesdraft_5 PARTITION OF masters.rulesdraft
    FOR VALUES IN(5);


CREATE TABLE masters.rulesdraft_6 PARTITION OF masters.rulesdraft
    FOR VALUES IN(6);


CREATE TABLE masters.rulesdraft_7 PARTITION OF masters.rulesdraft
    FOR VALUES IN(7);


CREATE TABLE masters.rulesdraft_8 PARTITION OF masters.rulesdraft
    FOR VALUES IN(8);


CREATE TABLE masters.rulesdraft_9 PARTITION OF masters.rulesdraft
    FOR VALUES IN(9);


CREATE TABLE masters.rulesdraft_10 PARTITION OF masters.rulesdraft
    FOR VALUES IN(10);


CREATE TABLE masters.rulesdraft_11 PARTITION OF masters.rulesdraft
    FOR VALUES IN(11);


CREATE TABLE masters.rulesdraft_12 PARTITION OF masters.rulesdraft
    FOR VALUES IN(12);


CREATE TABLE masters.rulesdraft_13 PARTITION OF masters.rulesdraft
    FOR VALUES IN(13);


CREATE TABLE masters.rulesdraft_14 PARTITION OF masters.rulesdraft
    FOR VALUES IN(14);


CREATE TABLE masters.rulesdraft_15 PARTITION OF masters.rulesdraft
    FOR VALUES IN(15);

-- 4. insert into new table from old table
INSERT INTO masters.rulesdraft(
	iruledraftid, bcustom, bpayee, bpayer, btransaction, bactive, bdelete, vclabel, vcruledescription, vcruledetail, ruledimension, vcrulename, vcruleparams, rulestate, vcruletype, itenantid)
SELECT iruledraftid, bcustom, bpayee, bpayer, btransaction, bactive, bdelete, vclabel, vcruledescription, vcruledetail, ruledimension, vcrulename, vcruleparams, rulestate, vcruletype, 1 as itenantid
	FROM masters.old_rulesdraft;


-- 5. set identity sequence to max value
SELECT setval(pg_get_serial_sequence('masters.rulesdraft', 'iruledraftid'), 
    (SELECT MAX(iruledraftid) FROM masters.rulesdraft)
);


-- DROP FK constraint from ui rulesdraftaudit of rulesdraft

ALTER TABLE ui.rulesdraftaudit
DROP CONSTRAINT fkh12dha7bj3nx1nlvm7yuk4bwg;

-- DROP FK constraint from ui metadataaudit of metadata

ALTER TABLE ui.metadataaudit
DROP CONSTRAINT fk_audit_imetadataid;


