UPDATE ui.dashboardquery SET vcdashboardquery='{
	"Account":"select iaccountid, icustomerid, vcexternalaccountid, iaccounttypeid, vcifsc, vcaccountproviderid, vcaccountname, dtonboardingdate, dtexpirydate, imcc, bmerchant, bverified, irecordstatus, dtentrydatetime from masters.accounts order by dtentrydatetime desc limit 50000",
	"VPA": "select ivpaid, iaccountid, vcexternaladdressid, vcaddress, iproductid, vcvpaname, bverified, imcc, dtonboardingdate, dtexpirydate, bmerchant, ivpaproviderid, bprofiled, dtfirsttransaction, dtlasttransaction, irecordstatus, dtentrydatetime from masters.vpa order by dtentrydatetime desc limit 50000",
	"Customer": "SELECT icustomerid, vcexternalcustid, vccustomername, vccustomertype, vcsalutation, vcverifiedname, vcgender, dtdoidob, dtonboardingdate, vcpostalcode, vcemail, vcregisteredmobile, imcc, vcidentitytype1, vcidentitydetails1, vcidentitytype2, vcidentitydetails2, vcregisteredaddressgeolocation, iadm3, iadm2, iadm1, vccountrycode, vcattribs->>''kyc_type'' as \"kyc type\", vcattribs->>''phone_number'' as \"phone number\", vcattribs->>''employment_type'' as \"employment type\", vcattribs->>''onboarding_state'' as \"onboarding state\", vcattribs->>''declared_salary_max'' as \"declared salary_max\", vcattribs->>''declared_salary_min'' as \"declared salary_min\", vcattribs->>''liveness_geolocation'' as \"liveness geolocation\",  vcattribs->>''internal_liveness_score'' as \"internal livness_score\", vcattribs->>''shipping_address_state'' as \"shipping address_state\",  vcattribs->>''mailing_address_postalcode'' as \"mailing address_postalcode\", vcattribs->>''shipping_address_postalcode'' as \"shipping address_postalcode\", irecordstatus, dtentrydatetime FROM masters.customers :AttribsForm order by dtentrydatetime desc limit 50000;"
}'::TEXT, formattingrequiered=false WHERE idashboardqueryid=48;

DELETE FROM ui.masterextractattribs;
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''kyc_type'' ', 'Customer', 'String', 'kyc type');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''phone_number''', 'Customer', 'String', 'phone number');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''employment_type''', 'Customer', 'String', 'employment type');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''declared_salary_max''', 'Customer', 'String', 'declared salary_max');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''onboarding_state''', 'Customer', 'String', 'onboarding state');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''declared_salary_min''', 'Customer', 'String', 'declared salary_min');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''liveness_geolocation''', 'Customer', 'String', 'liveness geolocation');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''internal_liveness_score''', 'Customer', 'String', 'internal liveness_score');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''shipping_address_state''', 'Customer', 'String', 'shipping address_state');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''mailing_address_postalcode''', 'Customer', 'String', 'mailing address_postalcode');
INSERT INTO ui.masterextractattribs (attribpath, level, datatype, displayname) VALUES ('vcattribs->>''shipping_address_postalcode''', 'Customer', 'String', 'shipping address_postalcode');