UPDATE ui.dashboardquery SET
vcdashboardquery = '{
    "Account": {
        "Payer": "with recursive profile as ( SELECT pv.*,v.vcexternalaccountid, v.vcaccountname FROM profiles.account pv left join masters.accounts v on v.iaccountid = pv.iaccountid where tdate = :Date and v.vcexternalaccountid = :VpaAddress and bside = false), flat ( iaccountid,bside, key, value) as ( select iaccountid,bside,'''',cast(format(''{\"Type\":\"%s\",\"ID\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), iaccountid, vcexternalaccountid, tdate, last_updated, vcaccountname) as jsonb) as value from profile union select  iaccountid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(longevity) \n union select  iaccountid, bside,concat( ''frequency.'', key), value from profile, jsonb_each(frequency) \n union select  iaccountid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  iaccountid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  iaccountid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  iaccountid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  iaccountid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select iaccountid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by iaccountid,bside) a;",
        "Payee": "with recursive profile as ( SELECT pv.*,v.vcexternalaccountid, v.vcaccountname FROM profiles.account pv left join masters.accounts v on v.iaccountid = pv.iaccountid where tdate = :Date and v.vcexternalaccountid = :VpaAddress and bside = true), flat ( iaccountid,bside, key, value) as ( select iaccountid,bside,'''',cast(format(''{\"Type\":\"%s\",\"ID\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), iaccountid, vcexternalaccountid, tdate, last_updated, vcaccountname) as jsonb) as value from profile union select  iaccountid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(longevity) \n union select  iaccountid, bside,concat( ''frequency.'', key), value from profile, jsonb_each(frequency) \n union select  iaccountid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  iaccountid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  iaccountid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  iaccountid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  iaccountid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select iaccountid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by iaccountid,bside) a;",
        "Both": "with recursive profile as ( SELECT pv.*,v.vcexternalaccountid, v.vcaccountname FROM profiles.account pv left join masters.accounts v on v.iaccountid = pv.iaccountid where tdate = :Date and v.vcexternalaccountid = :VpaAddress ), flat ( iaccountid,bside, key, value) as ( select iaccountid,bside,'''',cast(format(''{\"Type\":\"%s\",\"ID\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text),iaccountid, vcexternalaccountid, tdate, last_updated, vcaccountname) as jsonb) as value from profile union select  iaccountid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(longevity) \n union select  iaccountid, bside,concat( ''frequency.'', key), value from profile, jsonb_each(frequency) \n union select  iaccountid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  iaccountid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  iaccountid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  iaccountid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  iaccountid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select iaccountid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by iaccountid,bside) a;"


    },
    "VPA": {
        "Payer": "with recursive profile as ( SELECT pv.*,v.vcexternaladdressid, v.vcvpaname FROM profiles.vpa pv left join masters.vpa v on v.ivpaid = pv.ivpaid where tdate = :Date and v.vcexternaladdressid = :VpaAddress and bside = false), flat (ivpaid,bside, key, value) as ( select ivpaid,bside,'''',cast(format(''{\"Type\":\"%s\",\"ID\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), ivpaid, vcexternaladdressid, tdate, last_updated, vcvpaname) as jsonb) as value from profile union select  ivpaid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(longevity) \n union select  ivpaid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(frequency) \n union select  ivpaid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  ivpaid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  ivpaid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  ivpaid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  ivpaid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select ivpaid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by ivpaid,bside) a;",
        "Payee": "with recursive profile as ( SELECT pv.*,v.vcexternaladdressid, v.vcvpaname FROM profiles.vpa pv left join masters.vpa v on v.ivpaid = pv.ivpaid where tdate = :Date and v.vcexternaladdressid = :VpaAddress and bside = true), flat (ivpaid,bside, key, value) as ( select ivpaid,bside,'''',cast(format(''{\"Type\":\"%s\",\"ID\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), ivpaid, vcexternaladdressid, tdate, last_updated, vcvpaname) as jsonb) as value from profile union select  ivpaid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(longevity) \n union select  ivpaid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(frequency) \n union select  ivpaid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  ivpaid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  ivpaid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  ivpaid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  ivpaid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select ivpaid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by ivpaid,bside) a;",
        "Both": "with recursive profile as ( SELECT pv.*,v.vcexternaladdressid, v.vcvpaname FROM profiles.vpa pv left join masters.vpa v on v.ivpaid = pv.ivpaid where tdate = :Date and v.vcexternaladdressid = :VpaAddress ), flat (ivpaid,bside, key, value) as ( select ivpaid,bside,'''',cast(format(''{\"Type\":\"%s\",\"ID\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), ivpaid, vcexternaladdressid, tdate, last_updated, vcvpaname) as jsonb) as value from profile union select  ivpaid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(longevity) \n union select  ivpaid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(frequency) \n union select  ivpaid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  ivpaid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  ivpaid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  ivpaid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  ivpaid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select ivpaid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by ivpaid,bside) a;"
		}
}'::text WHERE
idashboardqueryid = 47;


UPDATE ui.dashboardresultset SET
vcdashboardresultsetschema = '{"ILiveMessageID":"string","UniqueID":"string","Class":"string","Time":"datetime","Payer Account":"string","PayerVPA":"string","PayerName":"string","Payee Account":"string","PayeeVPA":"string","PayeeName":"string","Amount":"float","FRMPass":"string","Score":"integer", "decisiondetails":"string"}'::text WHERE
idashboardresultsetid = 25;



UPDATE ui.dashboardquery SET
vcdashboardquery = '{
      "Account":"with recursive profile as ( SELECT * FROM masters.accounts limit 1000), flat ( iaccountid, key, value) as ( select iaccountid,'''', cast(format(''{\"iaccountid\":\"%s\",\"icustomerid\":\"%s\",\"vcexternalaccountid\":\"%s\",\"iaccounttypeid\":\"%s\" ,\"vcaccount\":\"%s\" ,\"vcifsc\":\"%s\",\"vcaccountproviderid\":\"%s\",\"vcaccountname\":\"%s\",\"dtonboardingdate\":\"%s\",\"dtexpirydate\":\"%s\" ,\"bmerchant\":\"%s\",\"irecordstatus\":\"%s\",\"dtentrydatetime\":\"%s\",\"imcc\":\"%s\",\"bverified\":\"%s\"}'',cast(iaccountid as text),cast(icustomerid as text),vcexternalaccountid, cast(iaccounttypeid as text),vcaccount, vcifsc, vcaccountproviderid, vcaccountname, dtonboardingdate, dtexpirydate, cast(bmerchant as text), irecordstatus,dtentrydatetime, cast(imcc as text), cast(bverified as text)) as jsonb) as value from profile \n union select  iaccountid,concat( ''attrib.'', key), value from profile, jsonb_each(vcattribs) \n union select  iaccountid,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select iaccountid,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by iaccountid) a;",
      "VPA": "with recursive profile as ( SELECT * FROM masters.vpa limit 1000), flat ( ivpaid, key, value) as ( select ivpaid,'''', cast(format(''{\"ivpaid\":\"%s\",\"iaccountid\":\"%s\",\"vcexternaladdressid\":\"%s\",\"vcaddress\":\"%s\" ,\"iproductid\":\"%s\" ,\"vcvpaname\":\"%s\",\"bverified\":\"%s\",\"imcc\":\"%s\",\"dtonboardingdate\":\"%s\",\"dtexpirydate\":\"%s\" ,\"bmerchant\":\"%s\",\"irecordstatus\":\"%s\",\"dtentrydatetime\":\"%s\",\"ivpaproviderid\":\"%s\",\"bprofiled\":\"%s\",\"dtfirsttransaction\":\"%s\" ,\"dtlasttransaction\":\"%s\"}'', cast(ivpaid as text),cast(iaccountid as text), vcexternaladdressid,vcaddress, cast(iproductid as text), vcvpaname,cast(bverified as text), cast(imcc as text),dtonboardingdate, dtexpirydate,  cast(bmerchant as text), irecordstatus, dtentrydatetime,ivpaproviderid, cast(bprofiled as text) ,  dtfirsttransaction,dtlasttransaction) as jsonb) as value from profile \n union select  ivpaid,concat( ''attrib.'', key), value from profile, jsonb_each(vcattribs) \n union select  ivpaid,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select ivpaid,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by ivpaid) a;"
  }'::text WHERE
idashboardqueryid = 48;