
INSERT INTO ui.menustructuredesc (
imenuid, bcollapse, isortorder, vcaction, vccontroller, vclayout, vcmenuname, vcmini, vcpath, iparentmenu, istatus) VALUES (
( select max(imenuid) + 1 from ui.menustructuredesc )::integer, false::boolean, '3'::integer, 'FileUpload'::character varying, 'FileUpload'::character varying, '/user'::character varying, 'File Upload'::character varying, 'FU'::character varying, '/admin/file-upload'::character varying, '482'::integer, '1'::integer)
 returning imenuid;


INSERT INTO ui.masterconfig (
iconfigid, bdelete, configjson, configname) VALUES (
(select max(iconfigid) + 1 from ui.masterconfig)::integer, false::boolean, '{
   "list":{
      "fileName":"List_Upload_template",
      "sheets":[
         {
            "sheet":"Whitelist Template",
            "columns":[
               {
                  "label":"vcexternallistitemid",
                  "value":"vcexternallistitemid",
                  "bodyKey":"externalId"
               },
               {
                  "label":"ilisttype",
                  "value":"ilisttype",
                  "type":"integer",
                  "bodyKey":"listType"
               },
               {
                  "label":"vcfield",
                  "value":"vcfield",
                  "bodyKey":"itemField"
               },
               {
                  "label":"vcvalue",
                  "value":"vcvalue",
                  "bodyKey":"itemValue"
               },
               {
                  "label":"vcsource",
                  "value":"vcsource",
                  "bodyKey":"source"
               },
               {
                  "label":"dteffectivefrom",
                  "value":"dteffectivefrom",
                  "bodyKey":"effectiveFrom",
                  "type":"startofdaydate"
               },
               {
                  "label":"dtexpiresat",
                  "value":"dtexpiresat",
                  "bodyKey":"expiresAt",
                  "type":"endofdaydate"
               },
               {
                  "label":"attribs",
                  "value":"attribs",
                  "type":"jsonb"
               }
            ],
            "content":[
               {
                  "vcexternallistitemid":"L-1716798175051",
                  "ilisttype":2,
                  "vcfield":"payee_account_external_id",
                  "vcvalue":"account_123",
                  "vcsource":"FRM",
                  "dteffectivefrom":"2024-06-28",
                  "dtexpiresat":"2024-07-28",
                  "attribs":"{\"rule\":true,\"action\":[]}"
               }
            ]
         },
         {
            "sheet":"Blacklist Template",
            "columns":[
               {
                  "label":"vcexternallistitemid",
                  "value":"vcexternallistitemid",
                  "bodyKey":"externalId"
               },
               {
                  "label":"ilisttype",
                  "value":"ilisttype",
                  "type":"integer",
                  "bodyKey":"listType"
               },
               {
                  "label":"vcfield",
                  "value":"vcfield",
                  "bodyKey":"itemField"
               },
               {
                  "label":"vcvalue",
                  "value":"vcvalue",
                  "bodyKey":"itemValue"
               },
               {
                  "label":"vcsource",
                  "value":"vcsource",
                  "bodyKey":"source"
               },
               {
                  "label":"dteffectivefrom",
                  "value":"dteffectivefrom",
                  "bodyKey":"effectiveFrom",
                  "type":"startofdaydate"
               },
               {
                  "label":"dtexpiresat",
                  "value":"dtexpiresat",
                  "bodyKey":"expiresAt",
                  "type":"endofdaydate"
               }
            ],
            "content":[
               {
                  "vcexternallistitemid":"L-1716798175051",
                  "ilisttype":0,
                  "vcfield":"payer_account_external_id",
                  "vcvalue":"account_123",
                  "vcsource":"FRM",
                  "dteffectivefrom":"2024-06-28",
                  "dtexpiresat":"2024-07-28"
               }
            ]
         },
         {
            "sheet":"Greylist Template",
            "columns":[
               {
                  "label":"vcexternallistitemid",
                  "value":"vcexternallistitemid",
                  "bodyKey":"externalId"
               },
               {
                  "label":"ilisttype",
                  "value":"ilisttype",
                  "type":"integer",
                  "bodyKey":"listType"
               },
               {
                  "label":"vcfield",
                  "value":"vcfield",
                  "bodyKey":"itemField"
               },
               {
                  "label":"vcvalue",
                  "value":"vcvalue",
                  "bodyKey":"itemValue"
               },
               {
                  "label":"vcsource",
                  "value":"vcsource",
                  "bodyKey":"source"
               },
               {
                  "label":"dteffectivefrom",
                  "value":"dteffectivefrom",
                  "bodyKey":"effectiveFrom",
                  "type":"startofdaydate"
               },
               {
                  "label":"dtexpiresat",
                  "value":"dtexpiresat",
                  "bodyKey":"expiresAt",
                  "type":"endofdaydate"
               }
            ],
            "content":[
               {
                  "vcexternallistitemid":"L-1716798175051",
                  "ilisttype":1,
                  "vcfield":"payee_account_external_id",
                  "vcvalue":"account_123",
                  "vcsource":"FRM",
                  "dteffectivefrom":"2024-06-28",
                  "dtexpiresat":"2024-07-28"
               }
            ]
         },
         {
            "sheet":"Field Mapping Enum",
            "columns":[
               {
                  "label":"Display Name",
                  "value":"Display Name"
               },
               {
                  "label":"vcvalue",
                  "value":"value"
               }
            ],
            "content":[
               {
                  "Display Name":"Payer Account",
                  "value":"payer_account_external_id"
               },
               {
                  "Display Name":"Payee Account",
                  "value":"payee_account_external_id"
               },
               {
                  "Display Name":"Transaction Amount",
                  "value":"instructed_amount"
               },
               {
                  "Display Name":"Payer Pincode",
                  "value":"pin_code"
               },
               {
                  "Display Name":"Payee Pincode",
                  "value":"pin_code"
               },
               {
                  "Display Name":"Country Code",
                  "value":"country"
               },
               {
                  "Display Name":"Device Location",
                  "value":"location"
               },
               {
                  "Display Name":"Payee Email",
                  "value":"identity_emailID"
               },
               {
                  "Display Name":"Device IP",
                  "value":"device_ip"
               },
               {
                  "Display Name":"Payee VPA",
                  "value":"payee_vpa"
               },
               {
                  "Display Name":"Payer VPA",
                  "value":"payer_vpa"
               },
               {
                  "Display Name":"Payer Card",
                  "value":"card_number"
               },
               {
                  "Display Name":"Payee Card",
                  "value":"card_number"
               },
               {
                  "Display Name":"Merchant Category Code",
                  "value":"default_mcc"
               },
               {
                  "Display Name":"Payer Address",
                  "value":"payer_addr"
               },
               {
                  "Display Name":"Payee Address",
                  "value":"payee_addr"
               },
               {
                  "Display Name":"Payee Card",
                  "value":"card_number"
               },
               {
                  "Display Name":"Payer Card",
                  "value":"card_number"
               },
               {
                  "Display Name":"Payer Address Watch List",
                  "value":"payer_addr_watch"
               },
               {
                  "Display Name":"Payer Address Suspicious",
                  "value":"payer_addr_suspicious"
               },
               {
                  "Display Name":"Payer Country Code",
                  "value":"device_location"
               },
               {
                  "Display Name":"Payer Mobile number",
                  "value":"mobile_num"
               },
               {
                  "Display Name":"Payee Country Code",
                  "value":"device_location"
               },
               {
                  "Display Name":"Payee Mobile number",
                  "value":"mobile_num"
               },
               {
                  "Display Name":"Device IMEI",
                  "value":"device_imei"
               },
               {
                  "Display Name":"Payer Email",
                  "value":"identity_emailID"
               }
            ]
         }
      ]
   },
   "simple_customer":{
      "fileName":"Simple_Customer_template",
      "sheets":[
         {
            "sheet":"Template",
            "columns":[
               {
                  "label":"ifsc*",
                  "value":"ifsc*"
               },
               {
                  "label":"email*",
                  "value":"email*"
               },
               {
                  "label":"merchant",
                  "value":"merchant"
               },
               {
                  "label":"externalId*",
                  "value":"externalId*"
               },
               {
                  "label":"accountType*",
                  "value":"accountType*",
                  "type":"integer"
               },
               {
                  "label":"customerType",
                  "value":"customerType"
               },
               {
                  "label":"default_mcc*",
                  "value":"default_mcc*",
                  "type":"integer"
               },
               {
                  "label":"postal_code*",
                  "value":"postal_code*",
                  "type":"integer"
               },
               {
                  "label":"verifiedName",
                  "value":"verifiedName"
               },
               {
                  "label":"customerName*",
                  "value":"customerName*"
               },
               {
                  "label":"accountNumber*",
                  "value":"accountNumber*",
                  "type":"integer"
               },
               {
                  "label":"cust_categories",
                  "value":"cust_categories"
               },
               {
                  "label":"onboarding_date*",
                  "value":"onboarding_date*"
               },
               {
                  "label":"payment_address*",
                  "value":"payment_address*"
               },
               {
                  "label":"iso_country_code*",
                  "value":"iso_country_code*"
               },
               {
                  "label":"registered_mobile*",
                  "value":"registered_mobile*",
                  "type":"integer"
               },
               {
                  "label":"address_geolocation",
                  "value":"address_geolocation"
               },
               {
                  "label":"attribs__ip",
                  "value":"attribs__ip"
               },
               {
                  "label":"attribs__kyc_status",
                  "value":"attribs__kyc_status"
               },
               {
                  "label":"attribs__postal_code",
                  "value":"attribs__postal_code"
               },
               {
                  "label":"attribs__business_type",
                  "value":"attribs__business_type"
               },
               {
                  "label":"attribs__merchant_type",
                  "value":"attribs__merchant_type"
               },
               {
                  "label":"attribs__daily_txn_count",
                  "value":"attribs__daily_txn_count",
                  "type":"integer"
               },
               {
                  "label":"attribs__mcc_description",
                  "value":"attribs__mcc_description"
               },
               {
                  "label":"attribs__pob_expiry_date",
                  "value":"attribs__pob_expiry_date"
               },
               {
                  "label":"attribs__daily_txn_amount",
                  "value":"attribs__daily_txn_amount",
                  "type":"integer"
               },
               {
                  "label":"attribs__business_division",
                  "value":"attribs__business_division"
               },
               {
                  "label":"attribs__open_refund_limit",
                  "value":"attribs__open_refund_limit",
                  "type":"integer"
               },
               {
                  "label":"attribs__closed_refund_limit",
                  "value":"attribs__closed_refund_limit",
                  "type":"integer"
               },
               {
                  "label":"attribs__proof_business_type",
                  "value":"attribs__proof_business_type"
               },
               {
                  "label":"attribs__open_daily_txn_count",
                  "value":"attribs__open_daily_txn_count",
                  "type":"integer"
               },
               {
                  "label":"attribs__open_daily_txn_amount",
                  "value":"attribs__open_daily_txn_amount",
                  "type":"integer"
               },
               {
                  "label":"attribs__closed_daily_txn_count",
                  "value":"attribs__closed_daily_txn_count",
                  "type":"integer"
               },
               {
                  "label":"attribs__closed_daily_txn_amount",
                  "value":"attribs__closed_daily_txn_amount",
                  "type":"integer"
               },
               {
                  "label":"attribs__internationalFlagUpdate",
                  "value":"attribs__internationalFlagUpdate"
               },
               {
                  "label":"attribs__open_daily_txn_refund_count",
                  "value":"attribs__open_daily_txn_refund_count",
                  "type":"integer"
               },
               {
                  "label":"attribs__closed_daily_txn_refund_count",
                  "value":"attribs__closed_daily_txn_refund_count",
                  "type":"integer"
               }
            ],
            "content":[
               {
                  "ifsc*":"HDFC0001",
                  "email*":"jogn.doe@gmail.con",
                  "merchant":"FALSE",
                  "attribs__ip":"",
                  "externalId*":"dhkh338983082",
                  "accountType*":1,
                  "customerType":"PERSON",
                  "default_mcc*":0,
                  "postal_code*":400671,
                  "verifiedName":"",
                  "customerName*":"JOHN DOE",
                  "accountNumber*":6700023456,
                  "cust_categories":"",
                  "onboarding_date*":"2019-09-07T15:50-04:00",
                  "payment_address*":"john_doe",
                  "iso_country_code*":"IN",
                  "attribs__kyc_status":"",
                  "registered_mobile*":9123412345,
                  "address_geolocation":"",
                  "attribs__postal_code":"",
                  "attribs__business_type":"",
                  "attribs__merchant_type":"",
                  "attribs__daily_txn_count":"",
                  "attribs__mcc_description":"",
                  "attribs__pob_expiry_date":"",
                  "attribs__daily_txn_amount":"",
                  "attribs__business_division":"",
                  "attribs__open_refund_limit":"",
                  "attribs__closed_refund_limit":"",
                  "attribs__proof_business_type":"",
                  "attribs__open_daily_txn_count":"",
                  "attribs__open_daily_txn_amount":"",
                  "attribs__closed_daily_txn_count":"",
                  "attribs__closed_daily_txn_amount":"",
                  "attribs__internationalFlagUpdate":"",
                  "attribs__open_daily_txn_refund_count":"",
                  "attribs__closed_daily_txn_refund_count":""
               },
               {
                  "ifsc*":"SBI112304",
                  "email*":"seller@ybl.com",
                  "merchant":"TRUE",
                  "externalId*":"YB12345",
                  "accountType*":2,
                  "customerType":"ENTITY",
                  "default_mcc*":5000,
                  "postal_code*":400671,
                  "verifiedName":"",
                  "customerName*":"SELLER",
                  "accountNumber*":6700023456,
                  "cust_categories":"",
                  "onboarding_date*":"2019-09-07T15:50-04:00",
                  "payment_address*":"YBB1234",
                  "iso_country_code*":"IN",
                  "registered_mobile*":9123412345,
                  "address_geolocation":"12.913046, 77.596858",
                  "attribs__ip":"101.188.67.134",
                  "attribs__kyc_status":"ACTIVE",
                  "attribs__postal_code":"400080",
                  "attribs__business_type":"XYZ",
                  "attribs__merchant_type":"PROPRIETARY",
                  "attribs__daily_txn_count":100,
                  "attribs__mcc_description":"Description of MCC",
                  "attribs__pob_expiry_date":"EXPIRY_DATE",
                  "attribs__daily_txn_amount":5000,
                  "attribs__business_division":"ABC",
                  "attribs__open_refund_limit":50,
                  "attribs__closed_refund_limit":100,
                  "attribs__proof_business_type":"286918236",
                  "attribs__open_daily_txn_count":20,
                  "attribs__open_daily_txn_amount":2000,
                  "attribs__closed_daily_txn_count":70,
                  "attribs__closed_daily_txn_amount":3000,
                  "attribs__internationalFlagUpdate":"Y",
                  "attribs__open_daily_txn_refund_count":30,
                  "attribs__closed_daily_txn_refund_count":20
               }
            ]
         }
      ]
   }
}'::jsonb, 'Bulk Upload Config'::character varying)
 returning iconfigid;



INSERT INTO batch.batch_job_types (
jobtypeid, jobtype, maxrecords, maxrowsize, numthreads, processing_url, iserverid) VALUES (
'3'::integer, 'List'::character varying, '1'::integer, '500'::integer, '8'::integer, '/api/v1/testing/batch/job/list'::character varying, '3'::integer)
 returning jobtypeid;