-- Password history and email

-- Table: ui.passwordhistory

-- DROP TABLE IF EXISTS ui.passwordhistory;

CREATE TABLE IF NOT EXISTS ui.passwordhistory
(
    ipasswordid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    iuserid integer NOT NULL,
    iorgid integer NOT NULL,
    vcpassword character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dtentrystamp timestamp(6) with time zone,
    bdelete boolean,
    CONSTRAINT passwordhistory_pk PRIMARY KEY (ipasswordid, iuserid, iorgid),
    CONSTRAINT fkauwaeio0r1wbpppnuufh4mg5tk FOREIGN KEY (iuserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
) PARTITION BY LIST (iorgid);

-- PROCEDURE: masters.partition_for_orgs(integer)

-- DROP PROCEDURE IF EXISTS masters.partition_for_orgs(integer);

CREATE OR REPLACE PROCEDURE masters.partition_for_orgs(
	IN _org integer)
LANGUAGE 'plpgsql'
AS $BODY$
DECLARE 
    _tbl text;
    _sql text;
    -- org RECORD;
BEGIN
	
    FOR _tbl IN 
        SELECT table_schema || '.' || table_name AS table
        FROM information_schema.tables
        WHERE  table_type = 'BASE TABLE'
        AND table_name NOT LIKE '%_1%'
		AND table_schema || '.' || table_name IN 
        ('ui.webuser','ui.webuseraudit','ui.webusermapping',
        'ui.webusermappingaudit', 'ui.activelogintokens','ui.activitylog','ui.passwordhistory')
        AND table_name IN (
            SELECT relname
            FROM pg_class
            WHERE relkind = 'p'
        )
    LOOP
        
         
            _sql := 'CREATE TABLE IF NOT EXISTS ' || _tbl || '_' || _org || ' PARTITION OF ' || _tbl || ' FOR VALUES IN(' || _org || ');';
            
            -- Raise Notice
            RAISE NOTICE '%', _sql;
            
            -- Execute
            IF _sql IS NOT NULL THEN 
                EXECUTE _sql;
            END IF;
       
    END LOOP;
END 
$BODY$;

CALL masters.partition_for_orgs(0);
CALL masters.partition_for_orgs(1);
CALL masters.partition_for_orgs(2);
CALL masters.partition_for_orgs(3);
CALL masters.partition_for_orgs(4);
CALL masters.partition_for_orgs(5);
CALL masters.partition_for_orgs(6);
CALL masters.partition_for_orgs(7);
CALL masters.partition_for_orgs(8);
CALL masters.partition_for_orgs(9);
CALL masters.partition_for_orgs(10);
CALL masters.partition_for_orgs(11);


-- PROCEDURE: masters.partition_for_tenants(integer)

-- DROP PROCEDURE IF EXISTS masters.partition_for_tenants(integer);

CREATE OR REPLACE PROCEDURE masters.partition_for_tenants(
	IN _org integer)
LANGUAGE 'plpgsql'
AS $BODY$
DECLARE 
    _tbl text;
    _sql text;
    tenant RECORD;
BEGIN
    FOR _tbl IN 
        SELECT table_schema || '.' || table_name AS table
        FROM information_schema.tables
        WHERE  table_type = 'BASE TABLE'
        AND table_name NOT LIKE '%_1%' AND table_name NOT LIKE '%trans\_%'
		AND table_schema || '.' || table_name NOT IN 
        ('ui.scorerequests','analytics.trans', 'ui.webuser','ui.webuseraudit','ui.webusermapping',
        'ui.webusermappingaudit', 'ui.activelogintokens','ui.activitylog','transactions.trans', 'analytics.trans','ui.passwordhistory')
        AND table_name IN (
            SELECT relname
            FROM pg_class
            WHERE relkind = 'p'
        )
    LOOP
        FOR tenant IN
            SELECT itenantid FROM masters.tenants WHERE iorgid = _org ORDER BY itenantid
        LOOP
            _sql := 'CREATE TABLE IF NOT EXISTS ' || _tbl || '_' || tenant.itenantid || ' PARTITION OF ' || _tbl || ' FOR VALUES IN(' || tenant.itenantid || ');';
            
            -- Raise Notice
            RAISE NOTICE '%', _sql;
            
            -- Execute
                EXECUTE _sql;         
        END LOOP;
    END LOOP;
END 
$BODY$;

-- Reset password

--ui.webuser

ALTER TABLE IF EXISTS ui.webuser
    ADD COLUMN "dtlastpasswordemailsentat" timestamp with time zone;