-- Table: ui.aiagentsaudit

-- DROP TABLE IF EXISTS ui.aiagentsaudit;

CREATE TABLE IF NOT EXISTS ui.aiagentsaudit
(
    iagentauditid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bclosed boolean NOT NULL,
    vcagentname character varying(255) COLLATE pg_catalog."default",
    vcagentdescription text COLLATE pg_catalog."default",
    ientryuserid integer,
    dtentrystamp timestamp with time zone NOT NULL DEFAULT now(),
    iapproveruserid integer,
    dtapproverstamp timestamp with time zone,
    vcremark text COLLATE pg_catalog."default",
    iversion integer NOT NULL,
    vcinitiation character varying(255) COLLATE pg_catalog."default",
    vcpolicy text COLLATE pg_catalog."default",
    vcprompt text COLLATE pg_catalog."default",
    vcconfig jsonb,
    irecordstatus integer DEFAULT 1,
    vcaction character(1) COLLATE pg_catalog."default" NOT NULL,
    itenantid integer NOT NULL,
    istatus integer,
    iorgid integer NOT NULL,
    iagentid bigint,
    CONSTRAINT aiagentsaudit_pkey PRIMARY KEY (itenantid, iagentauditid),
    CONSTRAINT aiagentsaudit_iapproveruserid_iorgid_fkey FOREIGN KEY (iapproveruserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT aiagentsaudit_ientryuserid_iorgid_fkey FOREIGN KEY (ientryuserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT aiagentsaudit_vcaction_check CHECK (vcaction = ANY (ARRAY['A'::bpchar, 'M'::bpchar, 'X'::bpchar, 'N'::bpchar]))
) PARTITION BY LIST (itenantid);


ALTER TABLE IF EXISTS ui.aiagentsaudit
    OWNER to dronapay;



-- Table: ui.aiagents

-- DROP TABLE IF EXISTS ui.aiagents;

CREATE TABLE IF NOT EXISTS ui.aiagents
(
    iagentid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 3 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    vcagentname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vcagentdescription text COLLATE pg_catalog."default",
    vcinitiation character varying(255) COLLATE pg_catalog."default",
    vcpolicy text COLLATE pg_catalog."default",
    vcprompt text COLLATE pg_catalog."default",
    vcconfig jsonb,
    dtentrystamp timestamp with time zone NOT NULL DEFAULT now(),
    dtapproverstamp timestamp with time zone,
    laststatus character varying(100) COLLATE pg_catalog."default",
    vcremark text COLLATE pg_catalog."default",
    irecordstatus integer DEFAULT 1,
    iapproveruserid integer,
    ientryuserid integer,
    itenantid integer NOT NULL,
    istatus integer,
    iorgid integer NOT NULL,
    iversion integer NOT NULL,
    CONSTRAINT aiagents_pkey PRIMARY KEY (itenantid, iagentid),
    CONSTRAINT aiagents_iapproveruserid_iorgid_fkey FOREIGN KEY (iapproveruserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT aiagents_ientryuserid_iorgid_fkey FOREIGN KEY (ientryuserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
) PARTITION BY LIST (itenantid);

ALTER TABLE IF EXISTS ui.aiagents
    OWNER to dronapay;


-- Table: ui.mlmodelsaudit

-- DROP TABLE IF EXISTS ui.mlmodelsaudit;

CREATE TABLE IF NOT EXISTS ui.mlmodelsaudit
(
    imodelid bigint,
    vcmlflowmodelname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vcmlflowmodeldescription text COLLATE pg_catalog."default",
    ientryuserid integer,
    dtentrystamp timestamp with time zone NOT NULL DEFAULT now(),
    iapproveruserid integer,
    dtapproverstamp timestamp with time zone,
    vcremark text COLLATE pg_catalog."default",
    imlversion double precision NOT NULL,
    vcmodeldetail jsonb,
    irecordstatus integer DEFAULT 1,
    vctype character varying(50) COLLATE pg_catalog."default",
    vcaction character(1) COLLATE pg_catalog."default" NOT NULL,
    itenantid integer NOT NULL,
    istatus integer,
    bclosed boolean NOT NULL,
    imodelauditid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    iorgid integer NOT NULL,
    CONSTRAINT mlmodelsaudit_pkey PRIMARY KEY (itenantid, imodelauditid),
    CONSTRAINT mlmodelsaudit_iapproveruserid_iorgid_fkey FOREIGN KEY (iapproveruserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT mlmodelsaudit_ientryuserid_iorgid_fkey FOREIGN KEY (ientryuserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT mlmodelsaudit_vcaction_check CHECK (vcaction = ANY (ARRAY['A'::bpchar, 'M'::bpchar, 'X'::bpchar, 'N'::bpchar]))
) PARTITION BY LIST (itenantid);

ALTER TABLE IF EXISTS ui.mlmodelsaudit
    OWNER to dronapay;


-- Table: ui.mlmodels

-- DROP TABLE IF EXISTS ui.mlmodels;

CREATE TABLE IF NOT EXISTS ui.mlmodels
(
    imodelid bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    vcmlflowmodelname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    vcmlflowmodeldescription text COLLATE pg_catalog."default",
    vcmodeldetail jsonb,
    imlversion double precision NOT NULL,
    vctype character varying(100) COLLATE pg_catalog."default",
    dtentrystamp timestamp with time zone NOT NULL DEFAULT now(),
    dtapproverstamp timestamp with time zone,
    laststatus character varying(100) COLLATE pg_catalog."default",
    vcremark text COLLATE pg_catalog."default",
    irecordstatus integer DEFAULT 1,
    iapproveruserid integer,
    ientryuserid integer NOT NULL,
    iorgid integer NOT NULL,
    itenantid integer NOT NULL,
    istatus integer,
    CONSTRAINT mlmodels_pkey PRIMARY KEY (itenantid, imodelid),
    CONSTRAINT mlmodels_iapproveruserid_iorgid_fkey FOREIGN KEY (iapproveruserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT mlmodels_ientryuserid_iorgid_fkey FOREIGN KEY (ientryuserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
) PARTITION BY LIST (itenantid);

ALTER TABLE IF EXISTS ui.mlmodels
    OWNER to dronapay;

-- Table: ui.agentchats

-- DROP TABLE IF EXISTS ui.agentchats;

CREATE TABLE IF NOT EXISTS ui.agentchats
(
    imessageid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    iagentid bigint NOT NULL,
    bagentmsg boolean NOT NULL,
    vcmessage text COLLATE pg_catalog."default" NOT NULL,
    dttimestamp timestamp with time zone NOT NULL DEFAULT now(),
    iuserid bigint NOT NULL,
    iorgid integer NOT NULL,
    itenantid integer NOT NULL,
    CONSTRAINT agentchats_pkey PRIMARY KEY (itenantid, imessageid),
    CONSTRAINT agentchats_iagentid_itenantid_fkey FOREIGN KEY (iagentid, itenantid)
        REFERENCES ui.aiagents (iagentid, itenantid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT agentchats_iuserid_iorgid_fkey FOREIGN KEY (iuserid, iorgid)
        REFERENCES ui.webuser (iuserid, iorgid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
) PARTITION BY LIST (itenantid);

ALTER TABLE IF EXISTS ui.agentchats
    OWNER to dronapay;

--Tenant partitions procedure

CALL masters.partition_for_tenants(0);
CALL masters.partition_for_tenants(1);
CALL masters.partition_for_tenants(3);
CALL masters.partition_for_tenants(4);
CALL masters.partition_for_tenants(5);
CALL masters.partition_for_tenants(6);
CALL masters.partition_for_tenants(7);
CALL masters.partition_for_tenants(8);
CALL masters.partition_for_tenants(9);
CALL masters.partition_for_tenants(10);
CALL masters.partition_for_tenants(11);
CALL masters.partition_for_tenants(12);
CALL masters.partition_for_tenants(13);