INSERT INTO ui.dashboard(idashboardid, bactive, bdelete, vcdashboardname, iorder, irowcount) VALUES (15, true, false, 'Party Profile New', 15,1);

INSERT INTO ui.dashboardfilters (idashboardfilterid, ifilterorder, vcdashboardfiltername, idashboardid, vcdashboardfiltertype, idashboardqueryidfordefaultvalue, idashboardqueryidforoptions, vcdashboardfilterdisplayname) VALUES (34, 0, 'Date', 15, 'DatePicker', 32, NULL, 'Date');
INSERT INTO ui.dashboardfilters (idashboardfilterid, ifilterorder, vcdashboardfiltername, idashboardid, vcdashboardfiltertype, idashboardqueryidfordefaultvalue, idashboardqueryidforoptions, vcdashboardfilterdisplayname) VALUES (35, 1, 'Party', 15, 'Select', NULL, 27, 'Level');
INSERT INTO ui.dashboardfilters (idashboardfilterid, ifilterorder, vcdashboardfiltername, idashboardid, vcdashboardfiltertype, idashboardqueryidfordefaultvalue, idashboardqueryidforoptions, vcdashboardfilterdisplayname) VALUES (36, 2, 'Type', 15, 'Select', NULL, 25, 'Type');
INSERT INTO ui.dashboardfilters (idashboardfilterid, ifilterorder, vcdashboardfiltername, idashboardid, vcdashboardfiltertype, idashboardqueryidfordefaultvalue, idashboardqueryidforoptions, vcdashboardfilterdisplayname) VALUES (37, 3, 'VpaAddress', 15, 'Input', NULL, NULL, 'Address');


INSERT INTO ui.dashboardquery (idashboardqueryid, bparametersrequired, vcfilterparametersjson, vcdashboardquery, formattingrequiered, runonanalytics, transposerequired) VALUES (47, true, '{"Date" : null, "VpaAddress":null, "Type":null, "Party": null}', '{
    "Account": {
        "Payer": "with recursive profile as ( SELECT pv.*,v.vcexternalaccountid, v.vcaccountname FROM profiles.account pv left join masters.accounts v on v.iaccountid = pv.iaccountid where tdate = :Date and v.vcexternalaccountid = :VpaAddress and bside = false), flat ( iaccountid,bside, key, value) as ( select iaccountid,bside,'''',cast(format(''{\"Type\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), vcexternalaccountid, tdate, last_updated, vcaccountname) as jsonb) as value from profile union select  iaccountid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(longevity) \n union select  iaccountid, bside,concat( ''longevity.'', key), value from profile, jsonb_each(frequency) \n union select  iaccountid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  iaccountid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  iaccountid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  iaccountid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  iaccountid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select iaccountid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by iaccountid,bside) a;",
        "Payee": "with recursive profile as ( SELECT pv.*,v.vcexternalaccountid, v.vcaccountname FROM profiles.account pv left join masters.accounts v on v.iaccountid = pv.iaccountid where tdate = :Date and v.vcexternalaccountid = :VpaAddress and bside = true), flat ( iaccountid,bside, key, value) as ( select iaccountid,bside,'''',cast(format(''{\"Type\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), vcexternalaccountid, tdate, last_updated, vcaccountname) as jsonb) as value from profile union select  iaccountid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(longevity) \n union select  iaccountid, bside,concat( ''longevity.'', key), value from profile, jsonb_each(frequency) \n union select  iaccountid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  iaccountid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  iaccountid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  iaccountid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  iaccountid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select iaccountid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by iaccountid,bside) a;",
        "Both": "with recursive profile as ( SELECT pv.*,v.vcexternalaccountid, v.vcaccountname FROM profiles.account pv left join masters.accounts v on v.iaccountid = pv.iaccountid where tdate = :Date and v.vcexternalaccountid = :VpaAddress ), flat ( iaccountid,bside, key, value) as ( select iaccountid,bside,'''',cast(format(''{\"Type\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), vcexternalaccountid, tdate, last_updated, vcaccountname) as jsonb) as value from profile union select  iaccountid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(longevity) \n union select  iaccountid, bside,concat( ''longevity.'', key), value from profile, jsonb_each(frequency) \n union select  iaccountid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  iaccountid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  iaccountid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  iaccountid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  iaccountid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select iaccountid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by iaccountid,bside) a;"


    },
    "VPA": {
        "Payer": "with recursive profile as ( SELECT pv.*,v.vcexternaladdressid, v.vcvpaname FROM profiles.vpa pv left join masters.vpa v on v.ivpaid = pv.ivpaid where tdate = :Date and v.vcexternaladdressid = :VpaAddress and bside = false), flat (ivpaid,bside, key, value) as ( select ivpaid,bside,'''',cast(format(''{\"Type\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), vcexternaladdressid, tdate, last_updated, vcvpaname) as jsonb) as value from profile union select  ivpaid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(longevity) \n union select  ivpaid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(frequency) \n union select  ivpaid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  ivpaid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  ivpaid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  ivpaid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  ivpaid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select ivpaid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by ivpaid,bside) a;",
        "Payee": "with recursive profile as ( SELECT pv.*,v.vcexternaladdressid, v.vcvpaname FROM profiles.vpa pv left join masters.vpa v on v.ivpaid = pv.ivpaid where tdate = :Date and v.vcexternaladdressid = :VpaAddress and bside = true), flat (ivpaid,bside, key, value) as ( select ivpaid,bside,'''',cast(format(''{\"Type\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), vcexternaladdressid, tdate, last_updated, vcvpaname) as jsonb) as value from profile union select  ivpaid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(longevity) \n union select  ivpaid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(frequency) \n union select  ivpaid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  ivpaid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  ivpaid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  ivpaid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  ivpaid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select ivpaid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by ivpaid,bside) a;",
        "Both": "with recursive profile as ( SELECT pv.*,v.vcexternaladdressid, v.vcvpaname FROM profiles.vpa pv left join masters.vpa v on v.ivpaid = pv.ivpaid where tdate = :Date and v.vcexternaladdressid = :VpaAddress ), flat (ivpaid,bside, key, value) as ( select ivpaid,bside,'''',cast(format(''{\"Type\":\"%s\",\"Address\":\"%s\",\"Date\":\"%s\",\"Last Update\":\"%s\" ,\"Name\":\"%s\"}'', cast(CASE WHEN bside = true THEN ''Payee'' WHEN bside = false THEN ''Payer'' ELSE null END as text), vcexternaladdressid, tdate, last_updated, vcvpaname) as jsonb) as value from profile union select  ivpaid,bside,concat( ''frequency.'', key), value from profile, jsonb_each(longevity) \n union select  ivpaid,bside,concat( ''longevity.'', key), value from profile, jsonb_each(frequency) \n union select  ivpaid,bside,concat( ''velocity.'', key), value from profile, jsonb_each(velocity) \n union select  ivpaid,bside,concat( ''engagement.'', key), value from profile, jsonb_each(engagement) \n union select  ivpaid,bside,concat( ''geospatial.'', key), value from profile, jsonb_each(geospatial) \n union select  ivpaid,bside,concat( ''events.'', key), value from profile, jsonb_each(events) \n union select  ivpaid,bside,concat(f.key, '''', j.key), j.value from flat f, jsonb_each(f.value) j where jsonb_typeof(f.value) = ''object'' ) \n select cast(json_agg(data) as text) from ( select ivpaid,bside,jsonb_object_agg(key, value  ) as data from flat where jsonb_typeof(value)<>''object'' group by ivpaid,bside) a;"
		}
}', true, false, false);

INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (69, 'Party', 'JsonPath', 47, 0);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (70, 'Type', 'JsonPath', 47, 1);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (71, 'VpaAddress', 'String', 47, NULL);
INSERT INTO ui.dashboardqueryparameters (idashboardparameterid, vcparametername, vcparametertype, idashboardqueryid, iorder) VALUES (72, 'Date', 'Date', 47, NULL);

 INSERT INTO ui.dashboardresultset (
	 idashboardresultsetid, iresultsetorder, vcdashboardresultsetcolumnjson,
	 vcdashboardresultsetlayout, vcdashboardresultsetname, idashboardqueryid,
	 idashboardid, vcdashboardresultsetschema, icolsize, irowno) VALUES (23, NULL, NULL, ' {
  	"sizes": [
  		1
  	],
  	"master": {
  		"widgets": ["PERSPECTIVE_GENERATED_ID_1"]
  	},
  	"viewers": {
  		"PERSPECTIVE_GENERATED_ID_1": {
                         "settings":false,
  			"selectable": false,
  			"plugin": "datagrid",
  			"master": true,
  			"name": "Party Profile",
  			"table": "partyprofile",
  			"linked": false
  		}
  	}
  }', 'partyprofile', 47, 15, NULL, NUll, 1);



